"""Generate a complete Skyrim LE creature behavior project from Oblivion data.

Emits per creature (all via packfile XML → hkxcmd, layouts copied from the
vanilla deer project dumps):

  (P = actors/tes4/<plugin namespace>/<name>, S = tes4<namespace>_<name>;
   project_layout() explains why the owning plugin is part of the path)
  P/<S>project.hkx                              (hkbProjectData boilerplate)
  P/characters/<S>character.hkx                 (hkbCharacterData: rig +
                                                 animation list + controller)
  P/behaviors/<S>behavior.hkx                   (GENERATED state machine)
  P/character assets/skeleton.hkx               (from hkx_skeleton)
  P/animations/*.hkx                            (from hkx_anim)
  P/motion_data.json                            (root motion per clip —
                                                 consumed by the future
                                                 animationdata emitter)

v1 graph: one root hkbStateMachine — Idle (start, looping) + locomotion states
(forward/backward/turns/swim, looping) + one single-play state per attack /
recoil / stagger clip, entered by the standard engine events (wildcard
transitions) and exited by clip-end triggers (attackStop etc. → Idle). This is
the Oblivion animation-selection convention expressed as a graph; ragdoll
death, foot IK, look-at, and speed-blended gaits are later refinements
(vanilla wrapper-graph features).

Event names follow the vanilla creature vocabulary (quadrupedbehavior.hkx),
so RACE ATKD/ATKE records generated by tes5_import must use the same
`attackStart_TES4_<clip>` strings (build_attack_events()).
"""

import json
import os

from asset_convert.game_paths import current_namespace

from asset_convert.havok.behavior_clips import (
    CAST_PHASES,
    backward_blend_plan,
    build_attack_events,
    cast_anim_stems,
    cast_phase_defs,
    classify_clips,
    clip_state_name,
    run_blend_plan,
    speed_blend_plan,
    state_defs,
    swim_blend_plan,
)


from asset_convert.havok.behavior_attacks import (
    RootStates,
    attack_modifier_list,
    add_attacks,
    add_equips,
    add_interrupts,
    add_vocal_idles,
    equip_dispatch_modifier,
)
from asset_convert.havok.behavior_locomotion import build_default
from asset_convert.havok.behavior_vocabulary import (
    graph_events,
    graph_variables,
    movement_type_names,
)
from asset_convert.havok.behavior_actions import (
    begin_cast_modifier,
    build_block,
    build_cast,
    build_swim,
    combat_idle_generator,
    swim_state_modifier,
)
from asset_convert.havok.behavior_ragdoll import (
    RAGDOLL_RELEASE_T,
    death_states,
    live_tracking,
)
from asset_convert.havok.behavior_nodes import F_GLOBAL, GraphBuilder
from asset_convert.havok.behavior_root import behavior_graph, graph_data
from asset_convert.havok.behavior_root import root_generator
from asset_convert.havok.hkx_xml import HkxPackfile, compile_hkx

# hkxcmd emits these signatures for hk_2010; needed by our emitter
from asset_convert.havok import hkx_xml
hkx_xml.SIGNATURES.update({
    'hkbBehaviorGraph': '0xb1218f86',
    'hkbBehaviorGraphData': '0x95aca5d',
    'hkbBehaviorGraphStringData': '0xc713064e',
    'hkbStateMachine': '0x816c1dcb',
    'hkbStateMachineStateInfo': '0xed7f9d0',
    'hkbStateMachineTransitionInfoArray': '0xe397b11e',
    'hkbClipGenerator': '0x333b85b9',
    'hkbClipTriggerArray': '0x59c23a0f',
    'hkbBlendingTransitionEffect': '0xfd8584fe',
    'hkbVariableValueSet': '0x27812d8d',
    'hkbVariableBindingSet': '0x338ad4ff',
    'hkbModifierGenerator': '0x1f81fae6',
    'hkbModifierList': '0xa4180ca1',
    'BSSpeedSamplerModifier': '0xd297fda9',
    'hkbCharacterData': '0x300d6808',
    'hkbCharacterStringData': '0x655b42bc',
    'hkbMirroredSkeletonInfo': '0xc6c2da4f',
    'hkbEventDrivenModifier': '0x7ed3f44e',
    'hkbEvaluateExpressionModifier': '0xf900f6be',
    'hkbExpressionDataArray': '0x4b9ee1a2',
    'hkbBlenderGenerator': '0x22df7147',
    'hkbBlenderGeneratorChild': '0xe2b384b0',
    'hkbPoweredRagdollControlsModifier': '0x7cb54065',
    'BSRagdollContactListenerModifier': '0x8003d8ce',
    'hkbKeyframeBonesModifier': '0x95f66629',
    'hkbRigidBodyRagdollControlsModifier': '0xaa87d1eb',
    'hkbBoneIndexArray': '0xaa8619',
    'hkbBoneWeightArray': '0xcd902b77',
    'BSIsActiveModifier': '0xb0fde45a',
    'hkbStateMachineEventPropertyArray': '0xb07b4388',
})


# ---------------------------------------------------------------------------
# XML builders
# ---------------------------------------------------------------------------

def build_project_xml(character_file: str) -> str:
    pf = HkxPackfile(first_id=9)
    sd = pf.add('hkbProjectStringData')
    pd = pf.add('hkbProjectData')
    top = pf.add('hkRootLevelContainer')

    sd.param_array('animationFilenames', [])
    sd.param_array('behaviorFilenames', [])
    sd.param_strings('characterFilenames', [character_file])
    sd.param_array('eventNames', [])
    sd.param('animationPath', '')
    sd.param('behaviorPath', '')
    sd.param('characterPath', '')
    sd.param('fullPathToSource', '')

    pd.param('worldUpWS', '(0.000000 0.000000 1.000000 0.000000)')
    pd.param('stringData', sd.ref)
    pd.param('defaultEventMode', 'EVENT_MODE_IGNORE_FROM_GENERATOR')

    top.param_structs('namedVariants', [
        [('name', 'hkbProjectData'), ('className', 'hkbProjectData'),
         ('variant', pd.ref)]])
    return pf.render(top)


def build_character_xml(name: str, anim_files: list, behavior_file: str,
                        n_bones: int, capsule_height: float = 1.7,
                        capsule_radius: float = 0.4) -> str:
    pf = HkxPackfile(first_id=27)
    mirror = pf.add('hkbMirroredSkeletonInfo')
    strings = pf.add('hkbCharacterStringData')
    values = pf.add('hkbVariableValueSet')
    cdata = pf.add('hkbCharacterData')
    top = pf.add('hkRootLevelContainer')

    mirror.param('mirrorAxis', '(1.000000 0.000000 0.000000 0.000000)')
    mirror.param_array('bonePairMap', list(range(n_bones)))

    # Ragdoll-driver feedback config (vanilla dog character, verbatim): the
    # engine reads these character properties to couple the MODEL to the
    # RAGDOLL (worldFromModel feedback while ragdolled / hit-reacting).
    # Without them every gain defaults to 0 — the actor never follows its
    # ragdoll.  Values are IEEE-754 bit patterns in wordVariableValues:
    # 0.6 / 0.25 / 0.4 / 0.25.
    _DRIVER_PROPS = [
        ('m_worldFromModelFeedbackGain', 1058642330),   # 0.6
        ('m_alignWorldFromModelGain', 1048576000),      # 0.25
        ('m_errorUpDownBias', 1053609165),              # 0.4
        ('m_ankleOrientationGain', 1048576000),         # 0.25
    ]

    strings.param_array('deformableSkinNames', [])
    strings.param_array('rigidSkinNames', [])
    strings.param_strings('animationNames', anim_files)
    strings.param_array('animationFilenames', [])
    strings.param_strings('characterPropertyNames',
                          [n for n, _v in _DRIVER_PROPS])
    strings.param_array('retargetingSkeletonMapperFilenames', [])
    strings.param_array('lodNames', [])
    strings.param_array('mirroredSyncPointSubstringsA', [])
    strings.param_array('mirroredSyncPointSubstringsB', [])
    strings.param('name', name)
    strings.param('rigName', 'Character Assets\\skeleton.HKX')
    strings.param('ragdollName', 'Character Assets\\skeleton.HKX')
    strings.param('behaviorFilename', behavior_file)

    values.param_structs('wordVariableValues',
                         [[('value', v)] for _n, v in _DRIVER_PROPS])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    cdata.param_raw('characterControllerInfo', (
        '<hkobject>\n'
        f'\t<hkparam name="capsuleHeight">{capsule_height:.6f}</hkparam>\n'
        f'\t<hkparam name="capsuleRadius">{capsule_radius:.6f}</hkparam>\n'
        '\t<hkparam name="collisionFilterInfo">1</hkparam>\n'
        '\t<hkparam name="characterControllerCinfo">null</hkparam>\n'
        '</hkobject>'))
    cdata.param('modelUpMS', '(0.000000 0.000000 1.000000 0.000000)')
    cdata.param('modelForwardMS', '(0.000000 1.000000 0.000000 0.000000)')
    cdata.param('modelRightMS', '(1.000000 -0.000000 -0.000000 0.000000)')
    cdata.param_raw('characterPropertyInfos', '\n'.join(
        '<hkobject>\n'
        '\t<hkparam name="role">\n'
        '\t\t<hkobject>\n'
        '\t\t\t<hkparam name="role">ROLE_DEFAULT</hkparam>\n'
        '\t\t\t<hkparam name="flags">0</hkparam>\n'
        '\t\t</hkobject>\n'
        '\t</hkparam>\n'
        '\t<hkparam name="type">VARIABLE_TYPE_REAL</hkparam>\n'
        '</hkobject>' for _p in _DRIVER_PROPS),
        numelements=len(_DRIVER_PROPS))
    cdata.param_array('numBonesPerLod', [])
    cdata.param('characterPropertyValues', values.ref)
    cdata.param('footIkDriverInfo', 'null')
    cdata.param('handIkDriverInfo', 'null')
    cdata.param('stringData', strings.ref)
    cdata.param('mirroredSkeletonInfo', mirror.ref)
    cdata.param('scale', '1.000000')

    top.param_structs('namedVariants', [
        [('name', 'hkbCharacterData'), ('className', 'hkbCharacterData'),
         ('variant', cdata.ref)]])
    return pf.render(top)


def build_behavior_xml(behavior_name: str, clips: dict,
                       hit_times: dict = None,
                       movement_types: list = None,
                       speeds: dict = None,
                       ragdoll: dict = None,
                       sound_events: list = None,
                       vocal_states: list = None) -> str:
    """The generated v1 state machine (see module docstring).

    hit_times: {state_name: [seconds]} — Oblivion 'Hit' text-key times for
    attack clips, emitted as preHitFrame/HitFrame triggers (the engine's
    attack-damage contract; without HitFrame an attack never deals damage).

    sound_events: the FULLY-QUALIFIED `SoundPlay.<SNDR EditorID>` names this
    creature's clips trigger. Every one must be declared in the graph's own
    event table or the annotation resolves to no event and is dropped — an
    animationdata trigger is dispatched by matching its text against this
    table, NOT by parsing the payload at play time. Vanilla does exactly this:
    chickenbehavior.hkx declares `SoundPlay.NPCChickenPeck` /
    `SoundPlay.NPCChickenScratch`, wolfbehavior.hkx declares
    `SoundPlay.NPCDogPantLPMSD` + `SoundStop.NPCDogPantLPMSD`, matching their
    animationdata triggers verbatim. The bare `SoundPlay` entry those graphs
    also carry is the inert leftover, not the mechanism.

    vocal_states: [(state_name, enter_event, anim_stem)] single-play vocal
    idle states (CSDT Idle/Aware slots), entered via the engine's idle
    system (ActionIdle/ActionIdleWarn IDLE records) and returning through
    returnToDefault. Each plays its OWN annotation-carrying copy of the
    idle animation so the sound fires once per entry, never per loop.

    movement_types: MOVT MNAM strings (movement_type_names()) declared as
    `iState_<X>` INT32 variables — the engine's movement-type registration
    contract; without them the actor cannot move at all.

    speeds: {'walk': u/s, 'run': u/s, ...} clip root-motion speeds — anchor
    weights for the MoveForward parametric walk/run blend (vanilla
    ForwardWalkBlend: children weighted by natural clip speed, blend
    parameter bound to SpeedSampled, flags=17 SYNC|PARAMETRIC).

    ragdoll: hkx_ragdoll.ragdoll_info() dict — enables the Fully Ragdoll
    death state (DeathAnimation/Ragdoll/RagdollInstant routing, a
    structural clone of the vanilla dogbehavior root SM state 4). Oblivion
    creatures have no death animations: death IS the ragdoll.
    """
    hit_times = hit_times or {}
    movement_types = movement_types or []
    speeds = speeds or {}
    events = graph_events(clips, vocal_states, sound_events)
    cast_defs = cast_phase_defs(clips)
    eid = {n: i for i, n in enumerate(events)}
    if not clips['idle']:
        raise ValueError('creature has no idle clip')

    # variable table is fixed up-front so bindings can reference indices.
    variables = graph_variables(clips, movement_types)
    has_swim_mt = any(mt.endswith('Swim') for mt in movement_types)
    var_values = [30 if n == 'iState' else iv for n, _t, iv in variables]
    gb = GraphBuilder(events, variables)

    default_sm, loco_sm, gait_eem = build_default(gb, clips, speeds)

    attack_ml = attack_modifier_list(gb)
    root = RootStates()
    add_interrupts(gb, root, clips, hit_times)
    root.extend(*build_swim(gb, clips, speeds, root.next_id))
    add_attacks(gb, root, clips, hit_times, attack_ml)
    equip_dispatch = add_equips(gb, root, clips, hit_times)
    root.extend(*build_cast(gb, cast_defs, clips, hit_times, root.next_id))
    root.extend(*build_block(gb, clips, root.next_id))
    add_vocal_idles(gb, root, clips, hit_times, vocal_states)
    equip_eem = equip_dispatch_modifier(gb, equip_dispatch)
    root_states_inner = root.states
    root_wilds = root.wilds
    default_trans = root.default_trans

    cast_eem = begin_cast_modifier(gb, cast_defs)
    swim_eem = swim_state_modifier(gb, movement_types, has_swim_mt)
    default_gen_ref = combat_idle_generator(gb, cast_defs, default_sm)

    default_state = gb.state(0, 'DefaultState', default_gen_ref,
                           transitions=default_trans or None)
    root_states_inner.insert(0, default_state)

    root_wilds.append((eid['returnToDefault'], 0, F_GLOBAL))
    wild = gb.trans_array(root_wilds)

    sm = gb.state_machine(f'{behavior_name}Root', root_states_inner,
                  start_id=0, wildcard_ref=wild.ref)

    gdata = graph_data(gb, events, variables, var_values)
    mod_gen = root_generator(gb, sm, live_tracking(gb, ragdoll),
                             [equip_eem, cast_eem, swim_eem, gait_eem])
    root_states = [gb.root_state(0, 'Root', mod_gen.ref)]
    death, root_wild_ref = death_states(gb, ragdoll, clips)
    return behavior_graph(gb, behavior_name, root_states + death,
                          root_wild_ref, gdata)


def _write_and_compile(xml: str, out_hkx: str):
    xml_path = out_hkx + '.xml'
    os.makedirs(os.path.dirname(os.path.abspath(out_hkx)), exist_ok=True)
    with open(xml_path, 'w', encoding='ascii', errors='replace',
              newline='\n') as f:
        f.write(xml)
    compile_hkx(xml_path, out_hkx)
    os.remove(xml_path)


def _apply_sound_slots(clip_meta: list, clips: dict, sound_slots: dict) -> int:
    """Turn a creature's CSDT sound slots into clip sound triggers.

    Oblivion keeps a creature's whole voice on the CREA record (idle, aware,
    attack, hit, death, footsteps) and its .kf files carry almost no sound text
    keys — exactly 1 of the goblin's 56, and that one is the bow string. Skyrim
    is the other way round: the actor record is nearly empty (36 CSDT entries
    across all 5118 vanilla NPC_, none of them Idle/Aware/Death) and the voice
    comes from `SoundPlay.<SNDR EditorID>` annotations in the animations. So
    the record data has to be replayed as annotations or the creature is
    silent.

    Only SINGLE-PLAY moments are handled here (attack swings, the death anim,
    plus footfall events on the gait cycle, which ARE per-cycle by nature).
    The Idle/Aware slots go through dedicated vocal states instead
    (generate_creature_project) — annotating the looping Idle/CombatStance
    clips fired them every cycle, in life and after death.

    A clip that already carries an authored sound key for a slot keeps it — the
    source is always the better authority when it exists.

    Returns the number of triggers added.
    """
    if not sound_slots:
        return 0
    from asset_convert.havok.creature_pipeline import CSDT_TO_CLIP

    by_name = {c['name']: c for c in clip_meta}

    def add(clip, t, edid):
        # The annotation MUST carry a descriptor name. Disassembly of the SSE
        # handler (0x140565c90, GOG build) settles it: after matching the
        # "SoundPlay" keyword it calls the string-length helper 0x140c60eb0 on
        # the payload and `je` straight to the exit when the length is ZERO —
        # a bare `SoundPlay:` is parsed, found empty, and dropped. Only on a
        # non-empty payload does it reach the lookup at 0x140c260f0, which
        # resolves the sound BY NAME. So `SoundPlay.<SNDR EditorID>` is the
        # only form that can ever produce audio; vanilla's bare `SoundPlay:`
        # entries are inert (they are leftovers from Bethesda's own pipeline).
        if any(abs(t0 - t) < 1e-3 and s0 == edid for t0, s0 in clip['sounds']):
            return 0
        clip['sounds'].append((t, edid))
        return 1

    added = 0
    for csdt, edid in sorted(sound_slots.items()):
        role = CSDT_TO_CLIP.get(csdt)
        if role is None:
            continue
        kind, where = role
        if kind == 'death':
            c = by_name.get('Death')
            if c:
                added += add(c, 0.0, edid)
        elif kind == 'attacks':
            for c in clip_meta:
                if not c['name'].startswith('Attack_'):
                    continue
                # On the swing, not the wind-up: use the hit frame when the
                # source marked one, else a quarter into the clip.
                t = (max(0.0, min(c['hits']) - 0.2) if c.get('hits')
                     else c['duration'] * 0.25)
                added += add(c, t, edid)
        elif kind == 'locomotion' and where == 'foot':
            # Footfalls do NOT go through SoundPlay at all: vanilla creature
            # projects fire the engine's own footstep events (wolf 140/142
            # FootFront/FootBack, bear 56/59), which route through the race's
            # footstep set rather than a sound descriptor. The event name
            # must be EXACTLY a tag creature_footsteps put in FSTP.ANAM —
            # both derive from creature_pipeline.foot_tags. Clips with
            # authored 'Enum:' footfall keys keep them; the rest get two
            # contact points per cycle placed from the clip duration.
            from asset_convert.havok.creature_pipeline import foot_tags
            tags = foot_tags(sound_slots)
            if not tags:
                continue
            if 'FootLeft' in tags:
                pair = [(0.25, 'FootLeft'), (0.75, 'FootRight')]
            else:
                pair = [(0.25, 'FootFront' if 'FootFront' in tags
                         else 'FootBack'), (0.75, 'FootBack')]
            for c in clip_meta:
                if not c['name'].startswith('Move') or c.get('feet'):
                    continue
                d = c['duration']
                if d <= 0:
                    continue
                c['feet'] = [(d * f, tag) for f, tag in pair]
                added += 2
    for c in clip_meta:
        c['sounds'].sort()
    return added


def behavior_graph_name(layout: dict) -> str:
    """The hkbBehaviorGraph name, which IS the behavior file's basename."""
    return f'{current_namespace()}{layout["stem"]}behavior'


def project_layout(name: str, namespace: str = '') -> dict:
    """Where a creature's project lives and what its files are called.

    `namespace` is the owning PLUGIN's tag (creature_pipeline.plugin_namespace)
    and is part of both the directory and every project file stem:

        meshes\\actors\\<game>\\<namespace>\\<folder>\\
            <game><namespace>_<folder>project.hkx
            characters\\<game><namespace>_<folder>character.hkx
            behaviors\\<game><namespace>_<folder>behavior.hkx

    `<game>` is the source game's asset namespace, so two games' creature
    projects cannot collide either. Record-side identity (RACE / ARMA / IDLE
    EditorIDs and FormID keys) stays on the leaf name, so both namespaces move
    files only — no FormID drifts.
    See: docs/commentary/asset_convert_creature.md#animdata-plugin-collision
    """
    lname = name.lower()
    game = current_namespace()
    stem = f'{namespace}_{lname}' if namespace else lname
    rel = f'{game}\\{namespace}\\{lname}' if namespace else f'{game}\\{lname}'
    return {
        'stem': stem,
        'dir_rel': rel,                             # under meshes\\actors
        'fs_dir': os.path.join('actors', *rel.lower().split('\\')),
        'project_hkx': f'Actors\\{rel}\\{game}{stem}project.hkx',
        'project_txt': f'{game}{stem}project.txt',
        'character_file': f'Characters\\{game}{stem}character.hkx',
        'behavior_file': f'Behaviors\\{game}{stem}behavior.hkx',
        'behavior_hkx': f'Actors\\{rel}\\Behaviors\\{game}{stem}behavior.hkx',
        'anim_dir': f'meshes\\actors\\{rel.lower()}\\animations',
        'skeleton_nif': f'actors\\{rel.lower()}\\character assets\\skeleton.nif',
        'body_dir': f'Actors\\{rel}',
    }


# Nodes Oblivion uses to hold an actor's own SKIN (the body proper).  A death
# animation that hides one of these is dissolving the creature rather than
# laying it down -- see detect_dissolve.
_SKIN_HOLDER_NODES = ('skinattachment',)


def detect_dissolve(decoded):
    """What a creature's death clip does, when it dissolves rather than falls.

    Returns {'dissolves': bool, 'duration': float, 'reveals': [node],
             'offsets': {node: (dx, dy, dz)}}.

    THE AUTHORED INDICATOR.  Oblivion's ghost and wraith do not fall over on
    death: their death.kf keeps `Bip01 NonAccum` at standing height for the
    whole clip and makes the body disappear with NiVisController toggles --
    hiding `SkinAttachment` (the actor's own skin holder) while REVEALING an
    ectoplasm holder.  A Havok clip carries bone transforms only, so all of
    that is lost in conversion and the corpse stands in mid-air for ever.

    `reveals` are the nodes the clip turns ON (0 -> 1).  For the ghost that is
    `AttachmentsBip`, whose subtree holds the authored ectoplasm pile that
    nif_converter.extract_death_pile lifts out; the wraith reveals
    `Attachments`, whose `Cloak06:0` is a flat slab parked UNDER the body --
    its remains, despite the name -- and ships as that creature's pile.

    `offsets` is each revealed node's LOCAL TRANSLATION on the clip's last
    frame (not a delta -- see the code).  The pile is authored at body height and the clip LOWERS it to the
    ground (ghost `AttachmentsBip`: z +14.04 -> -56.80), so a pile baked
    without this floats at chest height.

    Measured over every creature folder in all three test plugins, the
    dissolve test fires on exactly the ghost/wraith family and nothing else --
    and correctly REJECTS willothewisp, which has a `Bip01 ContainerGoo01`
    node but never hides its body.
    """
    empty = {'dissolves': False, 'duration': 0.0, 'reveals': [], 'offsets': {}}
    entry = (decoded or {}).get('death')
    if not entry:
        return empty
    clip = entry[0]
    duration = float(getattr(clip, 'duration', 0.0) or 0.0)
    vis = list(getattr(clip, 'vis_tracks', ()) or ())
    if not vis:
        return dict(empty, duration=duration)

    hides = any(bone.lower() in _SKIN_HOLDER_NODES
                and len(curve) and float(curve[0]) == 1.0
                and float(curve[-1]) == 0.0
                for bone, curve in vis)
    if not hides:
        return dict(empty, duration=duration)

    reveals = [bone for bone, curve in vis
               if len(curve) and float(curve[0]) == 0.0
               and float(curve[-1]) == 1.0]

    offsets = {}
    by_bone = {}
    for tr in getattr(clip, 'tracks', ()) or ():
        by_bone.setdefault(tr.bone, tr)
    for bone in reveals:
        tr = by_bone.get(bone)
        t = getattr(tr, 'translations', None) if tr is not None else None
        if t is not None and len(t):
            # The clip's LAST-FRAME position, not a delta.  A .kf track
            # is the node's full local translation, so the final sample IS
            # where the pile comes to rest.  (A delta only works when the
            # node's rest translation is zero: the ghost's AttachmentsBip
            # animates 14.04 -> -56.80 from rest 0, but the wraith's
            # Attachments sits at a CONSTANT -41.6 with rest 0, so its
            # delta is 0 and the pile floated at world Z 43-58.)
            #
            # X/Y ARE DELIBERATELY DROPPED.  They are where the ectoplasm
            # drifted to under the collapsing body (ghost: 10.45, 2.11) --
            # meaningful inside the creature's own skeleton, meaningless
            # for a placed object.  Actor.AttachAshPile already puts the
            # pile at the actor's feet, so keeping the drift shifts the
            # mesh ~10 units off the point the engine places, and the
            # activation box (built from the record's OBND about the
            # origin) ends up beside the visible pile.  Only Z is real:
            # it is what lowers the pile from body height to the ground.
            offsets[bone] = (0.0, 0.0, float(t[-1][2]))

    return {'dissolves': True, 'duration': duration,
            'reveals': reveals, 'offsets': offsets}


def generate_creature_project(creature_dir: str, name: str, out_root: str,
                              fps: float = 30.0, sound_slots: dict = None,
                              sound_chances: dict = None,
                              attr_speed: int = 0,
                              namespace: str = '') -> dict:
    """Full project generation for one creature.

    Writes the hkx project tree plus `project_manifest.json` — the manifest
    is the contract consumed by asset_convert/havok/animation_data.py (singlefile
    registration) and tes5_import (RACE ATKE/behavior-graph paths).

    namespace: the owning plugin's tag — see project_layout().

    sound_slots: {CSDT type: SOUN EditorID} for this creature's folder. Skyrim
    voices creatures through animation annotations rather than the actor
    record, so these become `SoundPlay.<SNDR>` clip triggers — see
    creature_pipeline._CSDT_TO_CLIP — except the Idle/Aware slots, which
    become dedicated single-play vocal states so they cannot fire per loop.
    sound_chances: {CSDT type: authored CSDC chance 0-100}, carried into the
    manifest's vocal_events for the import-side IDLE record conditions.

    attr_speed: the folder's MAX TES4 DATA.Speed attribute. Oblivion moved a
    creature at the GMST formula speed (walk = fMoveCreatureWalkMin +
    (Max−Min)×Speed/100, run = walk×fMoveRunMult; 5.0/300.0/3.0 from the
    export) regardless of the animation's root motion — the clips just slid.
    Skyrim ties commanded speed to the animation, so the speed-up is BAKED
    into the walk/run clips here (timescale_clip, capped ×1.4 walk / ×2.0
    run) and everything downstream — root-motion `speeds`, blend anchors,
    MOVT SPED — is derived from the baked files and agrees at rate 1.0,
    exactly like every vanilla creature (chaurus: MOVT run == blend top
    anchor == clip natural speed).
    """
    from asset_convert.havok.creature_pipeline import foot_enum_map
    from asset_convert.havok.hkx_anim import (decode_clip, event_annotations,
                                        parse_kf_events, speed_bake_factor,
                                        speed_bake_targets, timescale_clip,
                                        write_clip_hkx)
    from asset_convert.havok.hkx_ragdoll import ragdoll_info
    from asset_convert.havok.hkx_skeleton import generate_skeleton_hkx

    skeleton_nif = os.path.join(creature_dir, 'skeleton.nif')
    lname = name.lower()
    layout = project_layout(name, namespace)
    proj_dir = os.path.join(out_root, layout['fs_dir'])
    clips = classify_clips(creature_dir)

    bones = generate_skeleton_hkx(
        skeleton_nif, os.path.join(proj_dir, 'character assets',
                                   'skeleton.hkx'))
    ragdoll = ragdoll_info(skeleton_nif, bones)

    # convert every clip the graph uses, collecting per-clip metadata
    # (the run gait clip is not a state — it feeds the MoveForward
    # parametric speed blend — but still needs conversion + registration)
    convert_list = list(state_defs(clips))
    if clips.get('run'):
        convert_list.append(('MoveForwardRun', clips['run'], True, None,
                             None))
    if clips.get('run_back'):
        convert_list.append(('MoveBackwardRun', clips['run_back'], True,
                             None, None))
    attack_kfs = set(clips['attacks'])
    enum_map = foot_enum_map(sound_slots)

    _bake = speed_bake_targets(clips, attr_speed)

    def _bake_factor(stem, clip, motion):
        return speed_bake_factor(_bake.get(stem), clip, motion, fps)

    # Phase 1 — DECODE every clip and collect its translated events
    # (parse_kf_events: 'Sound: X' → SoundPlay descriptor names, authored
    # 'Enum: Left/...' footfalls → engine foot events, 'Hit' → hit times).
    # Compilation waits until _apply_sound_slots has folded the CREA CSDT
    # slots in, because the events must be EMBEDDED in the animation hkx as
    # annotations — the channel the engine dispatches at runtime (vanilla:
    # 58/74 wolf animations carry SoundPlay./FootFront/FootBack annotations
    # inside the .hkx; animationdata triggers alone stayed silent in game).
    decoded, decode_failed = {}, {}         # stem -> (clip, motion) / error
    clip_meta, motions, failures = [], {}, []
    cast_stem_map = cast_anim_stems(clips)
    cast_release_offset = None
    for st_name, kf, looping, _enter, end_evt in convert_list:
        src_stem = clip_state_name(kf)
        # A cast state plays a SLICE of its source clip, not the whole thing
        # (In/Loop/Out — see hkx_anim.split_cast_clip), so it decodes under
        # its own per-phase stem.
        stem = cast_stem_map.get(st_name, src_stem)
        if src_stem not in decoded and src_stem not in decode_failed:
            try:
                d_clip, d_motion = decode_clip(kf, fps)
                factor = _bake_factor(src_stem, d_clip, d_motion)
                if factor > 1.0:
                    d_clip, d_motion = timescale_clip(d_clip, d_motion,
                                                      factor)
                decoded[src_stem] = (d_clip, d_motion)
            except Exception as e:  # keep going; report at the end
                decode_failed[src_stem] = f'{type(e).__name__}: {e}'
        if src_stem in decode_failed:
            failures.append((kf, decode_failed[src_stem]))
            if st_name == 'MoveForwardRun':
                clips['run'] = None     # blender must not reference it
            continue
        clip, motion = decoded[src_stem]
        if st_name in cast_stem_map and stem not in decoded:
            from asset_convert.havok.hkx_anim import split_cast_clip
            in_c, loop_c, out_c, rel_off = split_cast_clip(clip)
            cast_release_offset = rel_off
            # no root motion for the slices: a cast is an in-place gesture,
            # and the full clip's motion curve would outrun the slice anyway
            for ph, part in zip(CAST_PHASES, (in_c, loop_c, out_c)):
                ph_stem = cast_stem_map.get(f'Mag_FF_{ph}')
                if ph_stem:
                    decoded[ph_stem] = (part, None)
        if stem in decoded:
            clip, motion = decoded[stem]
        events = parse_kf_events(clip.text_keys, enum_map)
        if st_name in cast_stem_map:
            # a cast is not a melee swing: no weaponSwing/HitFrame damage
            # window; the release is the Out clip's SpellFire trigger
            events['hits'] = []
        if kf in attack_kfs and not events['hits']:
            # Keyless attack: the damage contract (weaponSwing/preHitFrame/
            # HitFrame, fired by the graph's clip triggers) still needs a hit
            # moment. ~40% in is where vanilla one-shot attacks put it.
            events['hits'] = [float(clip.duration) * 0.4]
        clip_meta.append({
            'name': st_name,
            'stem': stem,
            'anim': 'Animations\\' + stem + '.hkx',
            'duration': float(clip.duration),
            'looping': looping,
            'end_event': end_evt,
            # The SOUN EDID must survive: both the hkx annotation and the
            # animationdata trigger are 'SoundPlay.<SNDR EDID>' and the
            # engine resolves that name at playback.  Keeping only the
            # timestamp emitted a bare 'SoundPlay' naming no descriptor,
            # which plays nothing.
            'sounds': events['sounds'],
            # Authored Oblivion footfall keys, already translated to the
            # engine's own footstep events (FSTP.ANAM match).
            'feet': events['feet'],
            # Oblivion 'Hit' text keys → HitFrame triggers (damage contract)
            'hits': events['hits'],
        })
        if motion and stem not in motions:
            motions[stem] = {
                'bone': motion['bone'],
                'duration': float(clip.duration),
                'times': motion['times'].tolist(),
                'translations': (motion['translations'].tolist()
                                 if motion['translations'] is not None
                                 else None),
                'rotations': (motion['rotations'].tolist()
                              if motion['rotations'] is not None else None),
            }

    # The cast Out's release trigger, mirrored into animationdata exactly as
    # vanilla ships it (atronachflame.txt: `MLh_SpellFire_Event:0.233334` +
    # `Spell_Stop:<end>` on Mag_FF_RH_Out). The graph fires the same pair
    # from its clip trigger array — both channels must agree.
    if cast_release_offset is not None:
        for c in clip_meta:
            if c['name'] == 'Mag_FF_Out':
                c['events'] = [(cast_release_offset, 'MLh_SpellFire_Event'),
                               (cast_release_offset, 'MRh_SpellFire_Event')]

    # CREA CSDT sound slots → SoundPlay/footstep events on the right clips,
    # BEFORE compiling, so they land inside the animation hkx too.
    _apply_sound_slots(clip_meta, clips, sound_slots)

    # Vocal state for the CSDT Aware(5) slot. It CANNOT be an annotation on
    # the looping Idle/CombatStance clips — an annotation fires every loop
    # cycle, so the creature squeaked non-stop, and kept squeaking after
    # death because the ragdoll wrapper states loop the idle clip as their
    # pose source. Instead it is a single-play state playing its OWN copy of
    # the idle animation with the sound annotation, entered through the
    # engine's ActionIdleWarn IDLE record — the exact vanilla WolfIdleWarn
    # layout (leaf under the action, ENAM, aggroWarning lifecycle), and it
    # only ever fires during an aggro warning.
    #
    # The Idle(4) slot is DELIVERED NOWHERE for now — both candidate
    # channels are disqualified:
    #   * an annotation on the looping base idle fires every cycle (the
    #     confirmed squeak-spam bug; vanilla only does this for cow/goat
    #     cud-chewing — predators' mt_idle carries no SoundPlay at all);
    #   * an IDLE record under ActionIdle sent the actor into an
    #     engine-tracked dynamic idle over and over (authored chance 75+ per
    #     idle poll), and creatures stopped walking and floated in their
    #     idle — vanilla routes ActionIdle through deep per-creature
    #     NonCombatIdle chains whose lifecycle our minimal graph does not
    #     implement. Restoring idle chatter needs that full chain first.
    idle_stem = clip_state_name(clips['idle']) if clips['idle'] else None
    vocal_states, vocal_events = [], []
    if idle_stem and idle_stem in decoded:
        idle_clip, _m = decoded[idle_stem]
        d = float(idle_clip.duration)
        edid = (sound_slots or {}).get(5)
        if edid:
            st_name, evt, stem = 'AwareVocal', 'awareVocalStart', 'awarevocal'
            decoded[stem] = decoded[idle_stem]
            clip_meta.append({
                'name': st_name, 'stem': stem,
                'anim': 'Animations\\' + stem + '.hkx',
                'duration': d, 'looping': False,
                'end_event': 'returnToDefault',
                'sounds': [(min(0.25, d * 0.25), edid)],
                'feet': [], 'hits': [],
            })
            vocal_states.append((st_name, evt, stem))
            vocal_events.append({
                'state': st_name, 'event': evt, 'slot': 5,
                'chance': (sound_chances or {}).get(5, 100),
            })
        # The ragdoll death state needs an annotation-free pose source (an
        # annotation in a looping corpse clip voices the corpse forever —
        # the squeaking-dead-rat bug), so 'ragdollpose' is a clean COPY of
        # the converted idle.  It must be the REAL converted clip, NOT a
        # synthesized frozen frame: the 2026-08-07 static_pose_clip
        # experiment shipped a hand-built 2-frame clip and the corpse
        # teleported on death (user-confirmed regression; the synthesized
        # root placement did not match the pipeline-converted clips).
        #
        # The clip_meta entry is REQUIRED, not bookkeeping: it is what
        # registers the 'FullyRagdollPose' clip generator in animationdata
        # and puts ragdollpose.hkx in the animationsetdata CRC preload list.
        # The engine binds creature clips exclusively through that cache —
        # every OTHER generator in the graph is registered (vanilla
        # registers its death/getup clips the same way: dogproject.txt
        # carries DeathPose, GetUpLeft, ...), and this one was not, so the
        # death state ran with a pose source that could never bind and the
        # entire ragdoll handoff died with it (2026-08-07 static-corpse /
        # sideways-teleport / misaligned-hitbox report).  No sounds/feet ->
        # its hkx annotation union stays empty, so corpses stay silent.
        if ragdoll:
            decoded['ragdollpose'] = (idle_clip, None)
            # rate 1.0 single-play, matching the graph clip (vanilla
            # death-clip semantics; the cache and graph playback speeds
            # must agree).  The `Ragdoll` event trigger is the release
            # into the limp ragdoll — see the pose_clip comment in
            # build_behavior_xml; it must be in BOTH the graph and here.
            clip_meta.append({
                'name': 'FullyRagdollPose', 'stem': 'ragdollpose',
                'anim': 'Animations\\ragdollpose.hkx', 'rate': 1.0,
                'duration': d, 'looping': False, 'end_event': None,
                'sounds': [], 'feet': [], 'hits': [],
                'events': [(RAGDOLL_RELEASE_T, 'Ragdoll')],
            })

    # Phase 2 — COMPILE, embedding each animation FILE's full event union as
    # annotations (states sharing one file share its annotations; blend
    # children reuse base files, whose annotation times are file-local, so
    # only rate-1 entries contribute). Hits stay OUT of the annotations: the
    # graph already fires weaponSwing/preHitFrame/HitFrame through its
    # hkbClipTriggerArray and double-firing would double the damage window.
    # 'ragdollpose' has no clip_meta entry, so it compiles annotation-free.
    ann_by_stem = {}
    for c in clip_meta:
        ann = ann_by_stem.setdefault(c['stem'], set())
        ann.update(event_annotations(
            {'sounds': c['sounds'], 'feet': c.get('feet', [])},
            include_hits=False))
    # A cast source clip is only ever played as its In/Loop/Out slices, so
    # the uncut original is never referenced — don't ship it.
    referenced = {c['stem'] for c in clip_meta}
    for stem in sorted(decoded):
        if stem not in referenced:
            continue
        clip, _motion = decoded[stem]
        out_hkx = os.path.join(proj_dir, 'animations', stem + '.hkx')
        try:
            write_clip_hkx(clip, bones, out_hkx,
                           sorted(ann_by_stem.get(stem, ())))
        except Exception as e:  # drop every state that used this file
            failures.append((stem + '.hkx', f'{type(e).__name__}: {e}'))
            dropped = {c['name'] for c in clip_meta if c['stem'] == stem}
            clip_meta = [c for c in clip_meta if c['stem'] != stem]
            motions.pop(stem, None)
            if 'MoveForwardRun' in dropped:
                clips['run'] = None

    # natural clip speeds (game units/sec) from root-motion endpoints —
    # ck-cmd calculateMOVTs: forwardWalk = |end translation| / duration.
    # These anchor both the MOVT SPED columns (tes5_import) and the
    # MoveForward parametric blend, so commanded speed == animation speed.
    def _speed_of(kf_path):
        if not kf_path:
            return None
        m = motions.get(clip_state_name(kf_path))
        if not m or not m['translations'] or not m['duration']:
            return None
        end = m['translations'][-1]
        v = (end[0] ** 2 + end[1] ** 2) ** 0.5 / m['duration']
        return round(v, 3) if v > 1.0 else None

    speeds = {
        'walk': _speed_of(clips['locomotion'].get('MoveForward')),
        'run': _speed_of(clips.get('run')),
        'back': _speed_of(clips['locomotion'].get('MoveBackward')),
        # Strafes: the MOVT left/right columns must carry the strafe clips'
        # own root-motion speed for the same reason forward/back do --
        # commanded speed != animation speed makes the actor slide.
        'left': _speed_of(clips['locomotion'].get('StrafeLeft')),
        'right': _speed_of(clips['locomotion'].get('StrafeRight')),
        'swim': _speed_of(clips.get('swim', {}).get('forward')),
        'swimfast': _speed_of(clips.get('swim', {}).get('fast')),
        'swimback': _speed_of(clips.get('swim', {}).get('backward')),
    }
    # a "run" clip that isn't actually faster than the walk (wraith:
    # runforward has LESS root motion than forward) breaks the parametric
    # blend's increasing-anchor contract and the MOVT columns — treat the
    # run gait as absent (MOVT run falls back to walk).
    if (speeds['run'] and speeds['walk']
            and speeds['run'] <= speeds['walk'] * 1.05):
        speeds['run'] = None
        clips['run'] = None

    # register the parametric-blend children (same clips at scaled
    # playbackSpeeds — see speed_blend_plan) in the animationdata cache:
    # every hkbClipGenerator name in the graph needs a cache entry with its
    # playback rate, trigger times in playback-local time (vanilla
    # dogproject.txt convention).
    base_of = {c['name']: c for c in clip_meta}
    for plan in (speed_blend_plan(clips, speeds) or [],
                 run_blend_plan(clips, speeds) or [],
                 backward_blend_plan(clips, speeds) or [],
                 swim_blend_plan(clips, speeds) or []):
        for cnm, kf, rate, _anchor in plan:
            if cnm in base_of:
                continue
            stem = clip_state_name(kf)
            base = next((c for c in clip_meta if c['stem'] == stem
                         and c.get('rate', 1) == 1), None)
            if base is None:
                continue
            entry = {
                'name': cnm, 'stem': stem, 'anim': base['anim'],
                'duration': base['duration'], 'looping': True,
                'end_event': None, 'rate': rate,
                'sounds': [(t / rate, s) for t, s in base['sounds']],
                'feet': [(t / rate, n) for t, n in base.get('feet', [])],
                'hits': [],
            }
            clip_meta.append(entry)
            base_of[cnm] = entry

    behavior_name = behavior_graph_name(layout)
    move_types = movement_type_names(
        layout['stem'],
        has_swim=bool(clips.get('swim', {}).get('forward')
                      and speeds.get('swim')))
    # The graph must declare every qualified sound event its clips trigger,
    # exactly as animation_data.project_block_lines writes it — the engine
    # dispatches annotations through this table by name.
    sound_events = sorted({f'SoundPlay.TES4_{edid}_SNDR'
                           for c in clip_meta
                           for _t, edid in c.get('sounds', []) if edid})
    # A vocal state whose animation failed to compile must not reach the
    # graph (its clip would reference a missing file).
    surviving = {c['name'] for c in clip_meta}
    vocal_states = [v for v in vocal_states if v[0] in surviving]
    vocal_events = [v for v in vocal_events if v['state'] in surviving]
    graph_hit_times = {c['name']: c['hits'] for c in clip_meta if c['hits']}
    if cast_release_offset is not None:
        # the Out state's SpellFire trigger moment (not a damage HitFrame —
        # cast states keep 'hits' empty; see the decode loop)
        graph_hit_times['Mag_FF_Out'] = [cast_release_offset]
    _write_and_compile(
        build_behavior_xml(behavior_name, clips,
                           hit_times=graph_hit_times,
                           movement_types=move_types,
                           speeds=speeds, ragdoll=ragdoll,
                           sound_events=sound_events,
                           vocal_states=vocal_states),
        os.path.join(proj_dir, 'behaviors', behavior_name.lower() + '.hkx'))
    # dedupe: states can share one animation file (Idle + CombatStance);
    # ragdollpose.hkx arrives through its FullyRagdollPose clip_meta entry
    anim_files = list(dict.fromkeys(c['anim'] for c in clip_meta))
    _write_and_compile(
        build_character_xml(
            f'{current_namespace()}{layout["stem"]}character', anim_files,
            layout['behavior_file'], n_bones=len(bones)),
        os.path.join(proj_dir, 'characters',
                     os.path.basename(layout['character_file'])))
    _write_and_compile(
        build_project_xml(layout['character_file']),
        os.path.join(proj_dir, os.path.basename(layout['project_hkx'])))

    attack_states = [(evt, f'Attack_{clip_state_name(kf)}')
                     for kf, evt in zip(clips['attacks'],
                                        build_attack_events(clips))]
    converted = {c['name'] for c in clip_meta}
    dissolve_info = detect_dissolve(decoded)
    manifest = {
        'name': lname,
        'namespace': namespace,
        'dir': layout['fs_dir'],
        'project_hkx': layout['project_hkx'],
        'project_txt': layout['project_txt'],
        # the root behavior path the engine's idle manager matches IDLE
        # DNAMs against (creature_idles)
        'behavior_hkx': layout['behavior_hkx'],
        'body_dir': layout['body_dir'],
        'skeleton_nif': layout['skeleton_nif'],
        'project_files': [layout['behavior_file'],
                          layout['character_file'],
                          'Character Assets\\skeleton.HKX'],
        'anim_dir': layout['anim_dir'],
        'clips': clip_meta,
        'attacks': [[e, s] for e, s in attack_states if s in converted],
        # whether the graph carries the FireForget cast chain (records side:
        # SPLO spells + the touch-spell melee ATKDs are independent of this)
        'has_cast': 'Mag_FF_Out' in converted,
        # whether the graph carries the block states (drives the block IDLE
        # action routing in tes5_import/creature_idles)
        'has_block': 'Block' in converted,
        'movement_types': move_types,
        'speeds': speeds,
        'has_ragdoll': bool(ragdoll),
        # Authored DISSOLVE: the death clip hides the actor's own skin
        # holder via NiVisController instead of dropping the body (an
        # Oblivion ghost/wraith -- `Bip01 NonAccum` never leaves standing
        # height).  Those channels cannot survive into a Havok clip, so
        # tes5_import attaches TES4_GhostDissolve, which reproduces the
        # effect with Skyrim's native Actor.AttachAshPile + a faded
        # Disable.  Detected from the ANIMATION, never from a name.
        'dissolves_on_death': dissolve_info['dissolves'],
        'death_duration': dissolve_info['duration'],
        # nodes the death clip REVEALS, and how far it moves them
        # by the last frame -- the authored ectoplasm pile lives
        # under one of these and has to be baked where the clip
        # leaves it (on the ground, not at body height)
        'death_reveals': dissolve_info['reveals'],
        'death_offsets': dissolve_info['offsets'],
        # ragdoll part bone names -> the race's generated BPTD (body part
        # data); node names must exist in THIS skeleton or the engine's
        # ragdoll/hit binding has nothing to attach to
        'ragdoll_bones': (ragdoll or {}).get('part_bones', []),
        # Vocal idle states: tes5_import/creature_idles generates the
        # ActionIdle/ActionIdleWarn IDLE records that let the engine enter
        # them (event = the IDLE's ENAM; chance = authored TES4 CSDC).
        'vocal_events': vocal_events,
        'motions': motions,
        'bones': len(bones),
        'failures': failures,
    }
    with open(os.path.join(proj_dir, 'project_manifest.json'), 'w',
              encoding='utf-8') as f:
        json.dump(manifest, f)
    return manifest


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(
        description='Generate a full Skyrim LE behavior project from an '
                    'Oblivion creature folder')
    ap.add_argument('creature_dir')
    ap.add_argument('out_root')
    ap.add_argument('--name', help='creature name (default: folder name)')
    ap.add_argument('--fps', type=float, default=30.0)
    args = ap.parse_args()

    name = args.name or os.path.basename(os.path.normpath(args.creature_dir))
    manifest = generate_creature_project(args.creature_dir, name,
                                         args.out_root, fps=args.fps)
    print(f"project: {manifest['project_hkx']}")
    print(f"bones: {manifest['bones']}, "
          f"animations: {len(manifest['clips'])}")
    for evt, state in manifest['attacks']:
        print('  attack event:', evt, '->', state)
    for kf, err in manifest['failures']:
        print('  FAILED:', os.path.basename(kf), err)
