"""bhkCompressedMeshShape building for Skyrim collision (replaces MOPP_RL).

Builds the full bhkMoppBvTreeShape → bhkCompressedMeshShape →
bhkCompressedMeshShapeData chain from a plain triangle soup, with the MOPP
bytecode and welding info generated by Havok's own compiler
(dovah_hkp_mesh_mopp_bridge.exe: hkpMoppUtility::buildCode with chunk
subdivision disabled + hkpMeshWeldingUtility TWO_SIDED welding, terminal
keys self-validated by Havok's find-all-keys VM).

Every byte of the output is authored here or by real Havok — nothing is
inherited from MOPP_RL.exe, whose ancient-Havok CMS/MOPP output produced
intermittent invalid-shape-key hits at runtime (Collision Sentinel
key=0xFFFFFFFF → CTD in hkpCollisionDispatcher).

Layout conventions (verified field-by-field against vanilla Skyrim meshes):
  - bits_per_index=17 / bits_per_w_index=18, error=0.001, layer=1 (static)
  - one identity bhkCMSDTransform; chunk translation = chunk min corner
  - chunk vertices are u16 offsets in 1/1000 hu steps from the translation
  - triangles are emitted as independent index triples (num_strips=0 —
    engine key decode is identical to the strip form, just simpler):
        key = (chunk_index + 1) << 18 | first_index_offset
  - triangles whose own extent exceeds the u16 chunk span become big tris
    (float verts, key = big-tri index)
  - welding u16 per triangle stored at the triangle's first index slot in
    the chunk welding array (indices_2), matching the key offset

Input triangles must be in Skyrim havok units in the FINAL shape frame:
the caller bakes any bhkRigidBodyT transform into the vertices and ships a
plain identity bhkRigidBody, because vanilla Skyrim never pairs a
transformed body with CMS collision (0 of 6341 vanilla CMS meshes) and the
engine's CMS/MOPP query path intermittently produces invalid shape keys
when one is present (the AnvilCastleGreatHall CTDs — every Sentinel
culprit was a rotated-root mesh converted to bhkRigidBodyT + CMS).
"""
import json
import math
import os
import subprocess
import uuid
from pathlib import Path

from .cms import decode_cms
from .mopp import walk_mopp

_ASSET_DIR = Path(__file__).parent
_MOPP_BRIDGE = str(_ASSET_DIR / 'dovah_hkp_mesh_mopp_bridge.exe')

_BITS_PER_INDEX = 17
_BITS_PER_W_INDEX = 18
_QUANT = 1000.0            # u16 chunk offsets are v*1000 (0.001 hu steps)
_MAX_CHUNK_EXTENT = 60.0   # hu; hard u16 span limit is 65.535
_MAX_CHUNK_TRIS = 2000     # keep chunks in the vanilla size range


def run_mopp_bridge(vertices, triangles, shape_keys, timeout=300):
    """Run the Havok MOPP bridge over an indexed triangle soup.

    vertices: [(x, y, z), ...] havok units; triangles: [(a, b, c), ...];
    shape_keys: engine shape key per triangle (unique).
    Returns the report dict (mopp_origin/mopp_scale/mopp_data_hex/
    welding_info), or None on any failure.
    """
    if not os.path.exists(_MOPP_BRIDGE):
        return None
    temp_dir = os.path.join(_ASSET_DIR.parent, 'temp')
    os.makedirs(temp_dir, exist_ok=True)
    uid = uuid.uuid4().hex
    tmp_in = os.path.join(temp_dir, f'moppbridge_{uid}.json')
    tmp_out = os.path.join(temp_dir, f'moppbridge_{uid}_report.json')
    try:
        with open(tmp_in, 'w', encoding='utf-8') as f:
            json.dump({
                'vertices': [c for v in vertices for c in v],
                'triangles': [i for tri in triangles for i in tri],
                'shape_keys': list(shape_keys),
            }, f)
        result = subprocess.run(
            [_MOPP_BRIDGE, '--input', tmp_in, '--output', tmp_out,
             '--no-stdout'],
            capture_output=True, timeout=timeout,
        )
        if result.returncode != 0 or not os.path.exists(tmp_out):
            return None
        with open(tmp_out, 'r', encoding='utf-8') as f:
            report = json.load(f)
        if (report.get('status') != 'ok'
                or not report.get('mopp_keys_match_shape_keys')):
            return None
        return report
    except Exception:
        return None
    finally:
        for p in (tmp_in, tmp_out):
            try:
                os.unlink(p)
            except OSError:
                pass


def _tri_extent(tri):
    """Largest axis extent of a triangle's AABB."""
    return max(
        max(v[i] for v in tri) - min(v[i] for v in tri) for i in range(3)
    )


def _split_buckets(tris):
    """Recursively split triangles into chunk buckets.

    Splits by triangle centroid at the AABB midpoint of the longest axis
    until every bucket's vertex AABB fits the u16 quantization span and the
    triangle count stays in the vanilla chunk range.
    """
    out = []
    stack = [tris]
    while stack:
        bucket = stack.pop()
        if not bucket:
            continue
        lo = [min(v[i] for t in bucket for v in t) for i in range(3)]
        hi = [max(v[i] for t in bucket for v in t) for i in range(3)]
        extents = [hi[i] - lo[i] for i in range(3)]
        if max(extents) <= _MAX_CHUNK_EXTENT and len(bucket) <= _MAX_CHUNK_TRIS:
            out.append(bucket)
            continue
        axis = extents.index(max(extents))
        mid = (lo[axis] + hi[axis]) / 2.0
        a = [t for t in bucket
             if (t[0][axis] + t[1][axis] + t[2][axis]) / 3.0 <= mid]
        b = [t for t in bucket
             if (t[0][axis] + t[1][axis] + t[2][axis]) / 3.0 > mid]
        if not a or not b:  # degenerate split (all centroids equal) — force
            half = len(bucket) // 2
            a, b = bucket[:half], bucket[half:]
        stack.append(a)
        stack.append(b)
    return out


def build_cms_collision(tris, sk_material, NifFormat):
    """Build a complete bhkMoppBvTreeShape+CMS from a triangle soup.

    tris: [((x,y,z), (x,y,z), (x,y,z)), ...] in Skyrim havok units, final
    shape frame (identity rigid body).  sk_material: Skyrim material CRC.
    Returns the bhkMoppBvTreeShape (caller sets the CMS target node), or
    None on failure (caller falls back to a packed shape without MOPP).
    """
    tris = [t for t in tris
            if all(math.isfinite(c) for v in t for c in v)
            and _tri_extent(t) > 0.0]
    if not tris:
        return None

    big, small = [], []
    for t in tris:
        (big if _tri_extent(t) >= _MAX_CHUNK_EXTENT else small).append(t)

    data = NifFormat.bhkCompressedMeshShapeData()
    data.bits_per_index = _BITS_PER_INDEX
    data.bits_per_w_index = _BITS_PER_W_INDEX
    data.mask_index = (1 << _BITS_PER_INDEX) - 1
    data.mask_w_index = (1 << _BITS_PER_W_INDEX) - 1
    data.error = 1.0 / _QUANT
    data.unknown_int_3 = 1  # constant 1 in vanilla and MOPP_RL output alike

    data.num_materials = 1
    data.chunk_materials.update_size()
    mat = data.chunk_materials[0]
    mat.material = int(sk_material)  # SkyrimHavokMaterial CRC
    mat.layer = 1                    # SKYL_STATIC
    mat.byte_set_to_0 = 0
    mat.short_set_to_0 = 0

    data.num_transforms = 1
    data.chunk_transforms.update_size()
    t0 = data.chunk_transforms[0]
    t0.translation.x = t0.translation.y = t0.translation.z = 0.0
    t0.translation.w = 0.0
    t0.rotation.x = t0.rotation.y = t0.rotation.z = 0.0
    t0.rotation.w = 1.0

    # --- big triangles (float verts, key = index) --------------------------
    big_vert_index = {}
    big_verts = []
    big_tri_rows = []
    for t in big:
        idx = []
        for v in t:
            key = (round(v[0], 6), round(v[1], 6), round(v[2], 6))
            i = big_vert_index.get(key)
            if i is None:
                i = len(big_verts)
                big_vert_index[key] = i
                big_verts.append(key)
            idx.append(i)
        if idx[0] == idx[1] or idx[1] == idx[2] or idx[0] == idx[2]:
            continue
        big_tri_rows.append(idx)

    data.num_big_verts = len(big_verts)
    data.big_verts.update_size()
    for i, (x, y, z) in enumerate(big_verts):
        bv = data.big_verts[i]
        bv.x, bv.y, bv.z, bv.w = float(x), float(y), float(z), 0.0
    data.num_big_tris = len(big_tri_rows)
    data.big_tris.update_size()
    for i, (a, b, c) in enumerate(big_tri_rows):
        bt = data.big_tris[i]
        bt.triangle_1, bt.triangle_2, bt.triangle_3 = a, b, c
        bt.unknown_int_1 = 0    # material index (single-material list)
        bt.unknown_short_1 = 0  # welding — filled from the bridge below

    # --- chunks (u16 quantized verts, independent triples) -----------------
    buckets = _split_buckets(small)
    data.num_chunks = len(buckets)
    data.chunks.update_size()
    for ci, bucket in enumerate(buckets):
        ch = data.chunks[ci]
        base = [min(v[i] for t in bucket for v in t) for i in range(3)]
        vert_index = {}
        offs = []      # flat u16 scalars
        indices = []
        for t in bucket:
            idx = []
            for v in t:
                q = tuple(
                    max(0, min(65535, int(round((v[i] - base[i]) * _QUANT))))
                    for i in range(3)
                )
                i = vert_index.get(q)
                if i is None:
                    i = len(vert_index)
                    vert_index[q] = i
                    offs.extend(q)
                idx.append(i)
            if idx[0] == idx[1] or idx[1] == idx[2] or idx[0] == idx[2]:
                continue  # collapsed by quantization
            indices.extend(idx)
        ch.translation.x, ch.translation.y, ch.translation.z = base
        ch.translation.w = 0.0
        ch.material_index = 0
        ch.transform_index = 0
        ch.unknown_short_1 = 65535  # constant in vanilla (Reference=0xFFFF)
        ch.num_vertices = len(offs)
        ch.vertices.update_size()
        for i, o in enumerate(offs):
            ch.vertices[i] = o
        ch.num_indices = len(indices)
        ch.indices.update_size()
        for i, ix in enumerate(indices):
            ch.indices[i] = ix
        ch.num_strips = 0
        ch.strips.update_size()
        ch.num_indices_2 = len(indices)  # welding array parallels indices
        ch.indices_2.update_size()
        for i in range(len(indices)):
            ch.indices_2[i] = 0

    # Bounds over the decoded (quantized) geometry — vanilla stored bounds
    # equal the decoded extents exactly.
    keyed = decode_cms(data)
    if not keyed:
        return None
    lo = [min(v[i] for _k, t in keyed for v in t) for i in range(3)]
    hi = [max(v[i] for _k, t in keyed for v in t) for i in range(3)]
    data.bounds_min.x, data.bounds_min.y, data.bounds_min.z = lo
    data.bounds_min.w = 0.0
    data.bounds_max.x, data.bounds_max.y, data.bounds_max.z = hi
    data.bounds_max.w = 0.0

    # --- MOPP + welding from Havok ------------------------------------------
    vert_index = {}
    vertices = []
    triangles = []
    shape_keys = []
    for key, tri in keyed:
        idx = []
        for v in tri:
            i = vert_index.get(v)
            if i is None:
                i = len(vertices)
                vert_index[v] = i
                vertices.append(v)
            idx.append(i)
        triangles.append(idx)
        shape_keys.append(key)

    report = run_mopp_bridge(vertices, triangles, shape_keys)
    if report is None:
        return None
    code = bytes.fromhex(report['mopp_data_hex'])
    if not code:
        return None

    # Independent verification with our own symbolic VM: clean walk and the
    # terminal key set must equal the CMS key set.
    walked = walk_mopp(code, len(code))
    if walked['errors'] or walked['tris'] != set(shape_keys):
        return None

    welding = report.get('welding_info') or []
    if len(welding) == len(shape_keys):
        for key, w in zip(shape_keys, welding):
            if not w:
                continue
            part = key >> _BITS_PER_W_INDEX
            if part == 0:
                data.big_tris[key].unknown_short_1 = int(w)
            else:
                offset = key & data.mask_index
                data.chunks[part - 1].indices_2[offset] = int(w)

    # --- wrap in bhkCompressedMeshShape + bhkMoppBvTreeShape ----------------
    cms = NifFormat.bhkCompressedMeshShape()
    cms.radius = 0.005
    cms.unknown_float_1 = 0.005
    cms.unknown_floats_1.x = 1.0
    cms.unknown_floats_1.y = 1.0
    cms.unknown_floats_1.z = 1.0
    cms.unknown_floats_1.w = 0.0
    cms.scale = 1.0
    cms.unknown_float_3 = 1.0
    cms.unknown_float_4 = 1.0
    cms.unknown_float_5 = 0.0
    cms.data = data

    mopp = NifFormat.bhkMoppBvTreeShape()
    mopp.shape = cms
    mopp.unknown_float = 1.0
    mopp.build_type = 1  # BUILT_WITHOUT_CHUNK_SUBDIVISION (vanilla standard)
    origin = report['mopp_origin']
    mopp.origin.x, mopp.origin.y, mopp.origin.z = origin[0], origin[1], origin[2]
    mopp.scale = report['mopp_scale']
    mopp.mopp_data_size = len(code)
    mopp.mopp_data.update_size()
    for i, b in enumerate(code):
        mopp.mopp_data[i] = b
    return mopp
