"""Generate a complete Skyrim LE creature behavior project from Oblivion data.

Emits per creature (all via packfile XML → hkxcmd, layouts copied from the
vanilla deer project dumps):

  actors/tes4/<name>/<name>project.hkx          (hkbProjectData boilerplate)
  actors/tes4/<name>/characters/<name>character.hkx  (hkbCharacterData: rig +
                                                 animation list + controller)
  actors/tes4/<name>/behaviors/<name>behavior.hkx    (GENERATED state machine)
  actors/tes4/<name>/character assets/skeleton.hkx   (from hkx_skeleton)
  actors/tes4/<name>/animations/*.hkx                (from hkx_anim)
  actors/tes4/<name>/motion_data.json                (root motion per clip —
                                                 consumed by the future
                                                 animationdata emitter)

v1 graph: one root hkbStateMachine — Idle (start, looping) + locomotion states
(forward/backward/turns/swim, looping) + one single-play state per attack /
recoil / stagger clip, entered by the standard engine events (wildcard
transitions) and exited by clip-end triggers (attackStop etc. → Idle). This is
the Oblivion animation-selection convention expressed as a graph; ragdoll
death, foot IK, look-at, and speed-blended gaits are later refinements
(vanilla wrapper-graph features).

Event names follow the vanilla creature vocabulary (quadrupedbehavior.hkx),
so RACE ATKD/ATKE records generated by tes5_import must use the same
`attackStart_TES4_<clip>` strings (build_attack_events()).
"""

import json
import os
import re
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO)

from asset_convert.hkx_xml import HkxPackfile, compile_hkx  # noqa: E402

# hkxcmd emits these signatures for hk_2010; needed by our emitter
from asset_convert import hkx_xml  # noqa: E402
hkx_xml.SIGNATURES.update({
    'hkbBehaviorGraph': '0xb1218f86',
    'hkbBehaviorGraphData': '0x95aca5d',
    'hkbBehaviorGraphStringData': '0xc713064e',
    'hkbStateMachine': '0x816c1dcb',
    'hkbStateMachineStateInfo': '0xed7f9d0',
    'hkbStateMachineTransitionInfoArray': '0xe397b11e',
    'hkbClipGenerator': '0x333b85b9',
    'hkbClipTriggerArray': '0x59c23a0f',
    'hkbBlendingTransitionEffect': '0xfd8584fe',
    'hkbVariableValueSet': '0x27812d8d',
    'hkbVariableBindingSet': '0x338ad4ff',
    'hkbModifierGenerator': '0x1f81fae6',
    'hkbModifierList': '0xa4180ca1',
    'BSSpeedSamplerModifier': '0xd297fda9',
    'hkbCharacterData': '0x300d6808',
    'hkbCharacterStringData': '0x655b42bc',
    'hkbMirroredSkeletonInfo': '0xc6c2da4f',
})


# ---------------------------------------------------------------------------
# Clip classification (the Oblivion filename convention)
# ---------------------------------------------------------------------------

LOCOMOTION_STATES = {
    # state name -> (kf basenames in priority order, enter event, exit event)
    'MoveForward': (['forward', 'runforward', 'fastforward'],
                    'moveStart', 'moveStop'),
    'MoveBackward': (['backward'], 'moveBackward', 'moveStop'),
    'TurnLeft': (['turnleft'], 'turnLeft', 'turnStop'),
    'TurnRight': (['turnright'], 'turnRight', 'turnStop'),
    'Swim': (['swimforward'], 'swimStart', 'swimStop'),
}
IDLE_CANDIDATES = ['idle']
SINGLE_PLAY = {
    'Recoil': (['recoil'], 'recoilStart', 'recoilStop'),
    'Stagger': (['stagger'], 'staggerStart', 'staggerStop'),
    # no end event: the clip holds its last pose (dead on the ground) —
    # ragdoll death is a later refinement of the skeleton.hkx stage
    'Death': (['death', 'dies'], 'deathStart', None),
}


def classify_clips(creature_dir: str) -> dict:
    """Scan an Oblivion creature folder into the v1 graph's clip roles.

    Returns {'idle': path, 'locomotion': {state: path}, 'attacks': [paths],
             'single': {state: path}, 'extra': [paths]}.
    """
    kfs = {}
    for fn in os.listdir(creature_dir):
        if fn.lower().endswith('.kf'):
            kfs[os.path.splitext(fn)[0].lower()] = os.path.join(
                creature_dir, fn)

    out = {'idle': None, 'locomotion': {}, 'attacks': [], 'single': {},
           'extra': []}
    used = set()
    for cand in IDLE_CANDIDATES:
        if cand in kfs:
            out['idle'] = kfs[cand]
            used.add(cand)
            break
    for state, (names, _e, _x) in LOCOMOTION_STATES.items():
        for n in names:
            if n in kfs:
                out['locomotion'][state] = kfs[n]
                used.add(n)
                break
    for state, (names, _e, _x) in SINGLE_PLAY.items():
        for n in names:
            if n in kfs:
                out['single'][state] = kfs[n]
                used.add(n)
                break
    for name, path in kfs.items():
        if name in used:
            continue
        if 'attack' in name:
            out['attacks'].append(path)
        else:
            out['extra'].append(path)
    out['attacks'].sort()
    return out


def _clip_state_name(kf_path: str) -> str:
    base = os.path.splitext(os.path.basename(kf_path))[0]
    return re.sub(r'[^A-Za-z0-9]', '', base)


def build_attack_events(clips: dict) -> list:
    """attackStart event names, shared verbatim with RACE ATKE generation."""
    return [f'attackStart_TES4_{_clip_state_name(p)}'
            for p in clips['attacks']]


def state_defs(clips: dict) -> list:
    """The graph's state list, shared by the behavior XML and the
    animationdata manifest: (state_name, kf_path, looping, enter_evt,
    end_evt) tuples, Idle first (state id 0).

    CombatStance is a looping idle-clip state entered on combatStanceStart
    (routed from the engine's ActionDraw): the combat controller "draws"
    before attacking and waits for the graph to confirm with a weaponDraw
    event (sent as the state's enterNotifyEvent) — without the handshake it
    never sends the RACE's attackStart_* events."""
    defs = []
    if clips['idle']:
        defs.append(('Idle', clips['idle'], True, None, None))
    for st, (_names, enter, _exit) in LOCOMOTION_STATES.items():
        if st in clips['locomotion']:
            defs.append((st, clips['locomotion'][st], True, enter, None))
    if clips['idle']:
        defs.append(('CombatStance', clips['idle'], True,
                     'combatStanceStart', None))
    for st, (_names, enter, end_evt) in SINGLE_PLAY.items():
        if st in clips['single']:
            defs.append((st, clips['single'][st], False, enter, end_evt))
    for kf, evt in zip(clips['attacks'], build_attack_events(clips)):
        defs.append((f'Attack_{_clip_state_name(kf)}', kf, False, evt,
                     'attackStop'))
    return defs


# ---------------------------------------------------------------------------
# XML builders
# ---------------------------------------------------------------------------

def build_project_xml(character_file: str) -> str:
    pf = HkxPackfile(first_id=9)
    sd = pf.add('hkbProjectStringData')
    pd = pf.add('hkbProjectData')
    top = pf.add('hkRootLevelContainer')

    sd.param_array('animationFilenames', [])
    sd.param_array('behaviorFilenames', [])
    sd.param_strings('characterFilenames', [character_file])
    sd.param_array('eventNames', [])
    sd.param('animationPath', '')
    sd.param('behaviorPath', '')
    sd.param('characterPath', '')
    sd.param('fullPathToSource', '')

    pd.param('worldUpWS', '(0.000000 0.000000 1.000000 0.000000)')
    pd.param('stringData', sd.ref)
    pd.param('defaultEventMode', 'EVENT_MODE_IGNORE_FROM_GENERATOR')

    top.param_structs('namedVariants', [
        [('name', 'hkbProjectData'), ('className', 'hkbProjectData'),
         ('variant', pd.ref)]])
    return pf.render(top)


def build_character_xml(name: str, anim_files: list, behavior_file: str,
                        n_bones: int, capsule_height: float = 1.7,
                        capsule_radius: float = 0.4) -> str:
    pf = HkxPackfile(first_id=27)
    mirror = pf.add('hkbMirroredSkeletonInfo')
    strings = pf.add('hkbCharacterStringData')
    values = pf.add('hkbVariableValueSet')
    cdata = pf.add('hkbCharacterData')
    top = pf.add('hkRootLevelContainer')

    mirror.param('mirrorAxis', '(1.000000 0.000000 0.000000 0.000000)')
    mirror.param_array('bonePairMap', list(range(n_bones)))

    strings.param_array('deformableSkinNames', [])
    strings.param_array('rigidSkinNames', [])
    strings.param_strings('animationNames', anim_files)
    strings.param_array('animationFilenames', [])
    strings.param_array('characterPropertyNames', [])
    strings.param_array('retargetingSkeletonMapperFilenames', [])
    strings.param_array('lodNames', [])
    strings.param_array('mirroredSyncPointSubstringsA', [])
    strings.param_array('mirroredSyncPointSubstringsB', [])
    strings.param('name', name)
    strings.param('rigName', 'Character Assets\\skeleton.HKX')
    strings.param('ragdollName', 'Character Assets\\skeleton.HKX')
    strings.param('behaviorFilename', behavior_file)

    values.param_structs('wordVariableValues', [])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    cdata.param_raw('characterControllerInfo', (
        '<hkobject>\n'
        f'\t<hkparam name="capsuleHeight">{capsule_height:.6f}</hkparam>\n'
        f'\t<hkparam name="capsuleRadius">{capsule_radius:.6f}</hkparam>\n'
        '\t<hkparam name="collisionFilterInfo">1</hkparam>\n'
        '\t<hkparam name="characterControllerCinfo">null</hkparam>\n'
        '</hkobject>'))
    cdata.param('modelUpMS', '(0.000000 0.000000 1.000000 0.000000)')
    cdata.param('modelForwardMS', '(0.000000 1.000000 0.000000 0.000000)')
    cdata.param('modelRightMS', '(1.000000 -0.000000 -0.000000 0.000000)')
    cdata.param_structs('characterPropertyInfos', [])
    cdata.param_array('numBonesPerLod', [])
    cdata.param('characterPropertyValues', values.ref)
    cdata.param('footIkDriverInfo', 'null')
    cdata.param('handIkDriverInfo', 'null')
    cdata.param('stringData', strings.ref)
    cdata.param('mirroredSkeletonInfo', mirror.ref)
    cdata.param('scale', '1.000000')

    top.param_structs('namedVariants', [
        [('name', 'hkbCharacterData'), ('className', 'hkbCharacterData'),
         ('variant', cdata.ref)]])
    return pf.render(top)


_TRANSITION_TMPL = '''<hkobject>
\t<hkparam name="triggerInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="initiateInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="transition">{effect}</hkparam>
\t<hkparam name="condition">null</hkparam>
\t<hkparam name="eventId">{event_id}</hkparam>
\t<hkparam name="toStateId">{to_state}</hkparam>
\t<hkparam name="fromNestedStateId">0</hkparam>
\t<hkparam name="toNestedStateId">0</hkparam>
\t<hkparam name="priority">0</hkparam>
\t<hkparam name="flags">FLAG_IS_LOCAL_WILDCARD|FLAG_DISABLE_CONDITION</hkparam>
</hkobject>'''

_TRIGGER_TMPL = '''<hkobject>
\t<hkparam name="localTime">{time:.6f}</hkparam>
\t<hkparam name="event">
\t\t<hkobject>
\t\t\t<hkparam name="id">{event_id}</hkparam>
\t\t\t<hkparam name="payload">null</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="relativeToEndOfClip">{rel}</hkparam>
\t<hkparam name="acyclic">false</hkparam>
\t<hkparam name="isAnnotation">false</hkparam>
</hkobject>'''

_VARIABLE_INFO_TMPL = '''<hkobject>
\t<hkparam name="role">
\t\t<hkobject>
\t\t\t<hkparam name="role">ROLE_DEFAULT</hkparam>
\t\t\t<hkparam name="flags">0</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="type">VARIABLE_TYPE_{vtype}</hkparam>
</hkobject>'''

_BINDING_TMPL = '''<hkobject>
\t<hkparam name="memberPath">{member}</hkparam>
\t<hkparam name="variableIndex">{var_index}</hkparam>
\t<hkparam name="bitIndex">-1</hkparam>
\t<hkparam name="bindingType">BINDING_TYPE_VARIABLE</hkparam>
</hkobject>'''

# The engine-side graph interface: SSE's movement controller / combat / AI
# bind these by name at graph init (every vanilla creature behavior declares
# them — vanilla dogbehavior has 65 variables; this is the engine-set/read
# subset).  A graph with NO variables leaves the movement hookup dead: the
# actor plays its start state forever and never walks or reacts.
# All word defaults are 0 (= 0.0 for REALs).
ENGINE_VARIABLES = [
    ('Speed', 'REAL'), ('Direction', 'REAL'), ('TurnDelta', 'REAL'),
    ('TurnDeltaDamped', 'REAL'), ('SpeedSampled', 'REAL'),
    ('staggerMagnitude', 'REAL'), ('staggerDirection', 'REAL'),
    ('iState', 'INT32'), ('iGetUpType', 'INT32'),
    ('iCharacterSelector', 'INT32'),
    ('IsAttacking', 'BOOL'), ('IsAttackReady', 'BOOL'),
    ('IsRecoiling', 'BOOL'), ('IsStaggering', 'BOOL'),
    ('IsBleedingOut', 'BOOL'), ('IsBashing', 'BOOL'),
    ('bAnimationDriven', 'BOOL'), ('bAllowRotation', 'BOOL'),
    ('bHeadTracking', 'BOOL'), ('bCanHeadTrack', 'BOOL'),
    ('bDisableHeadTrack', 'BOOL'), ('bForceIdleStop', 'BOOL'),
]


def movement_type_names(name: str) -> list:
    """The creature's engine movement-type names — the CONTRACT that makes an
    actor movable at all (2026-07-09, the tc-can't-move root cause).

    The engine registers an actor's movement types by enumerating the ROOT
    behavior graph's variables named `iState_<X>` and looking up the MOVT
    record whose MNAM == <X> (ck-cmd RetargetCreature.cpp does exactly this
    rename+MOVT-clone when retargeting creatures; vanilla dogbehavior
    declares iState_DogDefault/iState_DogRun matching MOVT MNAM DogDefault/
    DogRun). A graph with NO iState_* variables gives the movement
    controller ZERO movement types: the actor cannot move even under
    console `tc` control, no locomotion events are ever sent, and it idles
    forever — records, packages, clips and cache all being correct.

    These names are declared as INT32 graph variables here AND emitted as
    MOVT records by tes5_import/creature_races.py (via the manifest), so
    consistency is by construction, like the ATKE attack events.
    """
    base = f'TES4{name.lower()}'
    return [f'{base}Default', f'{base}Run']


def build_behavior_xml(behavior_name: str, clips: dict,
                       hit_times: dict = None,
                       movement_types: list = None) -> str:
    """The generated v1 state machine (see module docstring).

    hit_times: {state_name: [seconds]} — Oblivion 'Hit' text-key times for
    attack clips, emitted as preHitFrame/HitFrame triggers (the engine's
    attack-damage contract; without HitFrame an attack never deals damage).

    movement_types: MOVT MNAM strings (movement_type_names()) declared as
    `iState_<X>` INT32 variables — the engine's movement-type registration
    contract; without them the actor cannot move at all.
    """
    hit_times = hit_times or {}
    movement_types = movement_types or []
    # ---- event vocabulary: standard + per-attack ----
    events = ['moveStart', 'moveStop', 'moveForward', 'moveBackward',
              'turnLeft', 'turnRight', 'turnStop', 'swimStart', 'swimStop',
              'recoilStart', 'recoilStop', 'recoilLargeStart',
              'staggerStart', 'staggerStop',
              'combatStanceStart', 'combatStanceStop',
              'weaponDraw', 'weaponSheathe',
              'attackStop', 'returnToDefault', 'deathStart', 'IdleStop',
              'SoundPlay', 'preHitFrame', 'HitFrame', 'FootFront', 'FootBack']
    attack_events = build_attack_events(clips)
    events += attack_events
    eid = {n: i for i, n in enumerate(events)}

    pf = HkxPackfile(first_id=80)

    # blend effects: smooth 0.3s for locomotion, snappier 0.2s reset for hits
    fx_smooth = pf.add('hkbBlendingTransitionEffect')
    for obj, nm, dur, mode in ((fx_smooth, 'BlendSmooth', 0.3,
                                'SELF_TRANSITION_MODE_CONTINUE_IF_CYCLIC'),):
        obj.param('variableBindingSet', 'null')
        obj.param('userData', 0)
        obj.param('name', nm)
        obj.param('selfTransitionMode', mode)
        obj.param('eventMode', 'EVENT_MODE_DEFAULT')
        obj.param('duration', f'{dur:.6f}')
        obj.param('toGeneratorStartTimeFraction', '0.000000')
        obj.param('flags', 'FLAG_IGNORE_FROM_WORLD_FROM_MODEL')
        obj.param('endMode', 'END_MODE_NONE')
        obj.param('blendCurve', 'BLEND_CURVE_SMOOTH')

    # ---- states ----
    defs = state_defs(clips)
    if not defs:
        raise ValueError('creature has no usable clips')

    state_objs = []
    wildcards = []
    for state_id, (st_name, kf_path, looping, enter_evt, end_evt) in \
            enumerate(defs):
        anim_file = 'Animations\\' + _clip_state_name(kf_path) + '.hkx'
        trigger_items = []
        for t in hit_times.get(st_name, []):
            trigger_items.append(_TRIGGER_TMPL.format(
                time=max(0.0, t - 0.1), event_id=eid['preHitFrame'],
                rel='false'))
            trigger_items.append(_TRIGGER_TMPL.format(
                time=t, event_id=eid['HitFrame'], rel='false'))
        if end_evt:
            trigger_items.append(_TRIGGER_TMPL.format(
                time=0.0, event_id=eid[end_evt], rel='true'))
        triggers_ref = 'null'
        if trigger_items:
            trig = pf.add('hkbClipTriggerArray')
            trig.param_raw('triggers', '\n'.join(trigger_items),
                           numelements=len(trigger_items))
            triggers_ref = trig.ref
        clip = pf.add('hkbClipGenerator')
        clip.param('variableBindingSet', 'null')
        clip.param('userData', 0)
        clip.param('name', st_name)
        clip.param('animationName', anim_file)
        clip.param('triggers', triggers_ref)
        clip.param('cropStartAmountLocalTime', '0.000000')
        clip.param('cropEndAmountLocalTime', '0.000000')
        clip.param('startTime', '0.000000')
        clip.param('playbackSpeed', '1.000000')
        clip.param('enforcedDuration', '0.000000')
        clip.param('userControlledTimeFraction', '0.000000')
        clip.param('animationBindingIndex', -1)
        clip.param('mode', 'MODE_LOOPING' if looping else 'MODE_SINGLE_PLAY')
        clip.param('flags', 0)

        # CombatStance confirms the engine's draw request (ActionDraw →
        # combatStanceStart) by notifying weaponDraw on entry — the combat
        # controller waits for it before sending any attackStart_* event.
        enter_ref = exit_ref = 'null'
        if st_name == 'CombatStance':
            for evt_name, which in (('weaponDraw', 'enter'),
                                    ('weaponSheathe', 'exit')):
                arr = pf.add('hkbStateMachineEventPropertyArray')
                arr.param_raw('events', (
                    '<hkobject>\n'
                    f'\t<hkparam name="id">{eid[evt_name]}</hkparam>\n'
                    '\t<hkparam name="payload">null</hkparam>\n'
                    '</hkobject>'), numelements=1)
                if which == 'enter':
                    enter_ref = arr.ref
                else:
                    exit_ref = arr.ref

        state = pf.add('hkbStateMachineStateInfo')
        state.param('variableBindingSet', 'null')
        state.param_array('listeners', [])
        state.param('enterNotifyEvents', enter_ref)
        state.param('exitNotifyEvents', exit_ref)
        state.param('transitions', 'null')
        state.param('generator', clip.ref)
        state.param('name', st_name)
        state.param('stateId', state_id)
        state.param('probability', '1.000000')
        state.param('enable', True)
        state_objs.append(state)

        if enter_evt:
            wildcards.append((eid[enter_evt], state_id))

    # exits back to Idle
    idle_id = 0
    for evt in ('moveStop', 'turnStop', 'swimStop', 'attackStop',
                'recoilStop', 'staggerStop', 'returnToDefault',
                'combatStanceStop', 'IdleStop'):
        wildcards.append((eid[evt], idle_id))

    # extra engine-sent aliases: moveForward re-enters forward locomotion
    # (sent on direction changes while moving), recoilLargeStart shares the
    # single recoil clip
    state_ids = {d[0]: i for i, d in enumerate(defs)}
    if 'MoveForward' in state_ids:
        wildcards.append((eid['moveForward'], state_ids['MoveForward']))
    if 'Recoil' in state_ids:
        wildcards.append((eid['recoilLargeStart'], state_ids['Recoil']))

    wild = pf.add('hkbStateMachineTransitionInfoArray')
    wild.param_raw(
        'transitions',
        '\n'.join(_TRANSITION_TMPL.format(effect=fx_smooth.ref,
                                          event_id=e, to_state=s)
                  for e, s in wildcards),
        numelements=len(wildcards))

    sm = pf.add('hkbStateMachine')
    sm.param('variableBindingSet', 'null')
    sm.param('userData', 0)
    sm.param('name', f'{behavior_name}Root')
    sm.param_raw('eventToSendWhenStateOrTransitionChanges', (
        '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
        '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
    sm.param('startStateChooser', 'null')
    sm.param('startStateId', idle_id)
    sm.param('returnToPreviousStateEventId', -1)
    sm.param('randomTransitionEventId', -1)
    sm.param('transitionToNextHigherStateEventId', -1)
    sm.param('transitionToNextLowerStateEventId', -1)
    sm.param('syncVariableIndex', -1)
    sm.param('wrapAroundStateId', False)
    sm.param('maxSimultaneousTransitions', 32)
    sm.param('startStateMode', 'START_STATE_MODE_DEFAULT')
    sm.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
    sm.param_array('states', [s.ref for s in state_objs])
    sm.param('wildcardTransitions', wild.ref)

    # ---- variables: engine interface + movement-type registration ----
    # iState_<MOVT MNAM> variables are how the engine discovers the actor's
    # movement types (see movement_type_names). Vanilla pairs each with a
    # locomotion-state id and initializes iState to the default type's value
    # (dogbehavior: iState=30, iState_DogDefault=30, iState_DogRun=31); our
    # flat graph uses the MoveForward state id for all of them.
    loco_id = next((i for i, d in enumerate(defs) if d[0] == 'MoveForward'), 0)
    variables = ENGINE_VARIABLES + [(f'iState_{mt}', 'INT32')
                                    for mt in movement_types]
    var_values = [loco_id if (n == 'iState' or n.startswith('iState_')) else 0
                  for n, _t in variables]

    strings = pf.add('hkbBehaviorGraphStringData')
    strings.param_strings('eventNames', events)
    strings.param_array('attributeNames', [])
    strings.param_strings('variableNames', [n for n, _t in variables])
    strings.param_array('characterPropertyNames', [])

    values = pf.add('hkbVariableValueSet')
    values.param_structs('wordVariableValues',
                         [[('value', v)] for v in var_values])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    gdata = pf.add('hkbBehaviorGraphData')
    gdata.param_array('attributeDefaults', [])
    gdata.param_raw('variableInfos',
                    '\n'.join(_VARIABLE_INFO_TMPL.format(vtype=t)
                              for _n, t in variables),
                    numelements=len(variables))
    gdata.param_structs('characterPropertyInfos', [])
    gdata.param_structs('eventInfos', [[('flags', 0)]] * len(events))
    gdata.param('variableInitialValues', values.ref)
    gdata.param('stringData', strings.ref)

    # ---- engine movement hookup (mirrors the vanilla quadruped root) ----
    # The engine samples the graph's animation-driven movement speed through
    # a BSSpeedSamplerModifier bound to iState/Direction/Speed/SpeedSampled.
    # Without it AI pathing has no speed to drive, the actor never receives
    # movement, and it stands in its idle forever (combat can't approach
    # either).  Vanilla wraps the whole locomotion state machine in a
    # hkbModifierGenerator under a single-state root state machine; copy
    # that layout verbatim (userData values included).
    vidx = {n: i for i, (n, _t) in enumerate(ENGINE_VARIABLES)}
    sampler_binds = pf.add('hkbVariableBindingSet')
    sampler_binds.param_raw(
        'bindings',
        '\n'.join(_BINDING_TMPL.format(member=m, var_index=vidx[v])
                  for m, v in (('state', 'iState'),
                               ('direction', 'Direction'),
                               ('goalSpeed', 'Speed'),
                               ('speedOut', 'SpeedSampled'))),
        numelements=4)
    sampler_binds.param('indexOfBindingToEnable', -1)

    sampler = pf.add('BSSpeedSamplerModifier')
    sampler.param('variableBindingSet', sampler_binds.ref)
    sampler.param('userData', 2)
    sampler.param('name', 'BSSpeedSamplerModifier')
    sampler.param('enable', True)
    sampler.param('state', -1)
    sampler.param('direction', '0.000000')
    sampler.param('goalSpeed', '0.000000')
    sampler.param('speedOut', '0.000000')

    mod_list = pf.add('hkbModifierList')
    mod_list.param('variableBindingSet', 'null')
    mod_list.param('userData', 1)
    mod_list.param('name', 'RootModifierList')
    mod_list.param('enable', True)
    mod_list.param_array('modifiers', [sampler.ref])

    mod_gen = pf.add('hkbModifierGenerator')
    mod_gen.param('variableBindingSet', 'null')
    mod_gen.param('userData', 1)
    mod_gen.param('name', 'RootModifierGenerator')
    mod_gen.param('modifier', mod_list.ref)
    mod_gen.param('generator', sm.ref)

    root_state = pf.add('hkbStateMachineStateInfo')
    root_state.param('variableBindingSet', 'null')
    root_state.param_array('listeners', [])
    root_state.param('enterNotifyEvents', 'null')
    root_state.param('exitNotifyEvents', 'null')
    root_state.param('transitions', 'null')
    root_state.param('generator', mod_gen.ref)
    root_state.param('name', 'Root')
    root_state.param('stateId', 0)
    root_state.param('probability', '1.000000')
    root_state.param('enable', True)

    root_sm = pf.add('hkbStateMachine')
    root_sm.param('variableBindingSet', 'null')
    root_sm.param('userData', 0)
    root_sm.param('name', f'{behavior_name}RootBehavior')
    root_sm.param_raw('eventToSendWhenStateOrTransitionChanges', (
        '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
        '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
    root_sm.param('startStateChooser', 'null')
    root_sm.param('startStateId', 0)
    root_sm.param('returnToPreviousStateEventId', -1)
    root_sm.param('randomTransitionEventId', -1)
    root_sm.param('transitionToNextHigherStateEventId', -1)
    root_sm.param('transitionToNextLowerStateEventId', -1)
    root_sm.param('syncVariableIndex', -1)
    root_sm.param('wrapAroundStateId', False)
    root_sm.param('maxSimultaneousTransitions', 32)
    root_sm.param('startStateMode', 'START_STATE_MODE_DEFAULT')
    root_sm.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
    root_sm.param_array('states', [root_state.ref])
    root_sm.param('wildcardTransitions', 'null')

    graph = pf.add('hkbBehaviorGraph')
    graph.param('variableBindingSet', 'null')
    graph.param('userData', 0)
    graph.param('name', f'{behavior_name}.hkb')
    graph.param('variableMode', 'VARIABLE_MODE_DISCARD_WHEN_INACTIVE')
    graph.param('rootGenerator', root_sm.ref)
    graph.param('data', gdata.ref)

    top = pf.add('hkRootLevelContainer')
    top.param_structs('namedVariants', [
        [('name', 'hkbBehaviorGraph'), ('className', 'hkbBehaviorGraph'),
         ('variant', graph.ref)]])
    return pf.render(top)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def _write_and_compile(xml: str, out_hkx: str):
    xml_path = out_hkx + '.xml'
    os.makedirs(os.path.dirname(os.path.abspath(out_hkx)), exist_ok=True)
    with open(xml_path, 'w', encoding='ascii', errors='replace',
              newline='\n') as f:
        f.write(xml)
    compile_hkx(xml_path, out_hkx)
    os.remove(xml_path)


def generate_creature_project(creature_dir: str, name: str, out_root: str,
                              fps: float = 30.0) -> dict:
    """Full project generation for one creature.

    Writes the hkx project tree plus `project_manifest.json` — the manifest
    is the contract consumed by asset_convert/animation_data.py (singlefile
    registration) and tes5_import (RACE ATKE/behavior-graph paths).
    """
    from asset_convert.hkx_anim import convert_clip_hkx
    from asset_convert.hkx_skeleton import generate_skeleton_hkx

    skeleton_nif = os.path.join(creature_dir, 'skeleton.nif')
    lname = name.lower()
    proj_dir = os.path.join(out_root, 'actors', 'tes4', lname)
    clips = classify_clips(creature_dir)

    bones = generate_skeleton_hkx(
        skeleton_nif, os.path.join(proj_dir, 'character assets',
                                   'skeleton.hkx'))

    # convert every clip the graph uses, collecting per-clip metadata
    clip_meta, motions, failures = [], {}, []
    for st_name, kf, looping, _enter, end_evt in state_defs(clips):
        stem = _clip_state_name(kf)
        out_hkx = os.path.join(proj_dir, 'animations', stem + '.hkx')
        try:
            clip, motion = convert_clip_hkx(kf, bones, out_hkx, fps=fps)
        except Exception as e:  # keep going; report at the end
            failures.append((kf, f'{type(e).__name__}: {e}'))
            continue
        clip_meta.append({
            'name': st_name,
            'stem': stem,
            'anim': 'Animations\\' + stem + '.hkx',
            'duration': float(clip.duration),
            'looping': looping,
            'end_event': end_evt,
            'sounds': [float(t) for t, s in clip.text_keys
                       if s.strip().lower().startswith('sound')],
            # Oblivion 'Hit' text keys → HitFrame triggers (damage contract)
            'hits': [float(t) for t, s in clip.text_keys
                     if s.strip().lower() == 'hit'],
        })
        if motion:
            motions[stem] = {
                'bone': motion['bone'],
                'duration': float(clip.duration),
                'times': motion['times'].tolist(),
                'translations': (motion['translations'].tolist()
                                 if motion['translations'] is not None
                                 else None),
                'rotations': (motion['rotations'].tolist()
                              if motion['rotations'] is not None else None),
            }

    behavior_name = f'TES4{name.capitalize()}Behavior'
    move_types = movement_type_names(lname)
    _write_and_compile(
        build_behavior_xml(behavior_name, clips,
                           hit_times={c['name']: c['hits']
                                      for c in clip_meta if c['hits']},
                           movement_types=move_types),
        os.path.join(proj_dir, 'behaviors', behavior_name.lower() + '.hkx'))
    # dedupe: states can share one animation file (Idle + CombatStance)
    anim_files = list(dict.fromkeys(c['anim'] for c in clip_meta))
    _write_and_compile(
        build_character_xml(
            f'TES4{name.capitalize()}Character', anim_files,
            f'Behaviors\\{behavior_name.lower()}.hkx', n_bones=len(bones)),
        os.path.join(proj_dir, 'characters', f'tes4{lname}character.hkx'))
    _write_and_compile(
        build_project_xml(f'Characters\\tes4{lname}character.hkx'),
        os.path.join(proj_dir, f'tes4{lname}project.hkx'))

    attack_states = [(evt, f'Attack_{_clip_state_name(kf)}')
                     for kf, evt in zip(clips['attacks'],
                                        build_attack_events(clips))]
    converted = {c['name'] for c in clip_meta}
    manifest = {
        'name': lname,
        'project_hkx': f'Actors\\TES4\\{lname}\\tes4{lname}project.hkx',
        'project_txt': f'tes4{lname}project.txt',
        'project_files': [f'Behaviors\\{behavior_name.lower()}.hkx',
                          f'Characters\\tes4{lname}character.hkx',
                          'Character Assets\\skeleton.HKX'],
        'anim_dir': f'meshes\\actors\\tes4\\{lname}\\animations',
        'clips': clip_meta,
        'attacks': [[e, s] for e, s in attack_states if s in converted],
        'movement_types': move_types,
        'motions': motions,
        'bones': len(bones),
        'failures': failures,
    }
    with open(os.path.join(proj_dir, 'project_manifest.json'), 'w',
              encoding='utf-8') as f:
        json.dump(manifest, f)
    return manifest


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(
        description='Generate a full Skyrim LE behavior project from an '
                    'Oblivion creature folder')
    ap.add_argument('creature_dir')
    ap.add_argument('out_root')
    ap.add_argument('--name', help='creature name (default: folder name)')
    ap.add_argument('--fps', type=float, default=30.0)
    args = ap.parse_args()

    name = args.name or os.path.basename(os.path.normpath(args.creature_dir))
    manifest = generate_creature_project(args.creature_dir, name,
                                         args.out_root, fps=args.fps)
    print(f"project: {manifest['project_hkx']}")
    print(f"bones: {manifest['bones']}, "
          f"animations: {len(manifest['clips'])}")
    for evt, state in manifest['attacks']:
        print('  attack event:', evt, '->', state)
    for kf, err in manifest['failures']:
        print('  FAILED:', os.path.basename(kf), err)
