"""Generate a complete Skyrim LE creature behavior project from Oblivion data.

Emits per creature (all via packfile XML → hkxcmd, layouts copied from the
vanilla deer project dumps):

  actors/tes4/<name>/<name>project.hkx          (hkbProjectData boilerplate)
  actors/tes4/<name>/characters/<name>character.hkx  (hkbCharacterData: rig +
                                                 animation list + controller)
  actors/tes4/<name>/behaviors/<name>behavior.hkx    (GENERATED state machine)
  actors/tes4/<name>/character assets/skeleton.hkx   (from hkx_skeleton)
  actors/tes4/<name>/animations/*.hkx                (from hkx_anim)
  actors/tes4/<name>/motion_data.json                (root motion per clip —
                                                 consumed by the future
                                                 animationdata emitter)

v1 graph: one root hkbStateMachine — Idle (start, looping) + locomotion states
(forward/backward/turns/swim, looping) + one single-play state per attack /
recoil / stagger clip, entered by the standard engine events (wildcard
transitions) and exited by clip-end triggers (attackStop etc. → Idle). This is
the Oblivion animation-selection convention expressed as a graph; ragdoll
death, foot IK, look-at, and speed-blended gaits are later refinements
(vanilla wrapper-graph features).

Event names follow the vanilla creature vocabulary (quadrupedbehavior.hkx),
so RACE ATKD/ATKE records generated by tes5_import must use the same
`attackStart_TES4_<clip>` strings (build_attack_events()).
"""

import json
import os
import re
import sys

_REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, _REPO)

from asset_convert.hkx_xml import HkxPackfile, compile_hkx  # noqa: E402

# hkxcmd emits these signatures for hk_2010; needed by our emitter
from asset_convert import hkx_xml  # noqa: E402
hkx_xml.SIGNATURES.update({
    'hkbBehaviorGraph': '0xb1218f86',
    'hkbBehaviorGraphData': '0x95aca5d',
    'hkbBehaviorGraphStringData': '0xc713064e',
    'hkbStateMachine': '0x816c1dcb',
    'hkbStateMachineStateInfo': '0xed7f9d0',
    'hkbStateMachineTransitionInfoArray': '0xe397b11e',
    'hkbClipGenerator': '0x333b85b9',
    'hkbClipTriggerArray': '0x59c23a0f',
    'hkbBlendingTransitionEffect': '0xfd8584fe',
    'hkbVariableValueSet': '0x27812d8d',
    'hkbVariableBindingSet': '0x338ad4ff',
    'hkbModifierGenerator': '0x1f81fae6',
    'hkbModifierList': '0xa4180ca1',
    'BSSpeedSamplerModifier': '0xd297fda9',
    'hkbCharacterData': '0x300d6808',
    'hkbCharacterStringData': '0x655b42bc',
    'hkbMirroredSkeletonInfo': '0xc6c2da4f',
    'hkbEventDrivenModifier': '0x7ed3f44e',
    'hkbEvaluateExpressionModifier': '0xf900f6be',
    'hkbExpressionDataArray': '0x4b9ee1a2',
    'hkbBlenderGenerator': '0x22df7147',
    'hkbBlenderGeneratorChild': '0xe2b384b0',
    'hkbPoweredRagdollControlsModifier': '0x7cb54065',
    'BSRagdollContactListenerModifier': '0x8003d8ce',
    'hkbBoneIndexArray': '0xaa8619',
    'hkbBoneWeightArray': '0xcd902b77',
})


# ---------------------------------------------------------------------------
# Clip classification (the Oblivion filename convention)
# ---------------------------------------------------------------------------

LOCOMOTION_STATES = {
    # state name -> (kf basenames in priority order, enter event, exit event)
    'MoveForward': (['forward', 'runforward', 'fastforward'],
                    'moveStart', 'moveStop'),
    'MoveBackward': (['backward'], 'moveBackward', 'moveStop'),
    'TurnLeft': (['turnleft'], 'turnLeft', 'turnStop'),
    'TurnRight': (['turnright'], 'turnRight', 'turnStop'),
    'Swim': (['swimforward'], 'swimStart', 'swimStop'),
}
IDLE_CANDIDATES = ['idle']
SINGLE_PLAY = {
    'Recoil': (['recoil'], 'recoilStart', 'recoilStop'),
    'Stagger': (['stagger'], 'staggerStart', 'staggerStop'),
    # no end event: the clip holds its last pose (dead on the ground) —
    # ragdoll death is a later refinement of the skeleton.hkx stage
    'Death': (['death', 'dies'], 'deathStart', None),
}


def classify_clips(creature_dir: str) -> dict:
    """Scan an Oblivion creature folder into the v1 graph's clip roles.

    Returns {'idle': path, 'locomotion': {state: path}, 'attacks': [paths],
             'single': {state: path}, 'extra': [paths]}.
    """
    kfs = {}
    for fn in os.listdir(creature_dir):
        if fn.lower().endswith('.kf'):
            kfs[os.path.splitext(fn)[0].lower()] = os.path.join(
                creature_dir, fn)

    out = {'idle': None, 'locomotion': {}, 'attacks': [], 'single': {},
           'extra': [], 'run': None}
    used = set()
    for cand in IDLE_CANDIDATES:
        if cand in kfs:
            out['idle'] = kfs[cand]
            used.add(cand)
            break
    for state, (names, _e, _x) in LOCOMOTION_STATES.items():
        for n in names:
            if n in kfs:
                out['locomotion'][state] = kfs[n]
                used.add(n)
                break
    # run gait: a faster forward clip distinct from the walk clip — feeds the
    # MoveForward parametric speed blend (vanilla ForwardWalkBlend layout)
    if 'forward' in used:
        for n in ('runforward', 'fastforward'):
            if n in kfs and n not in used:
                out['run'] = kfs[n]
                used.add(n)
                break
    for state, (names, _e, _x) in SINGLE_PLAY.items():
        for n in names:
            if n in kfs:
                out['single'][state] = kfs[n]
                used.add(n)
                break
    for name, path in kfs.items():
        if name in used:
            continue
        if 'attack' in name:
            out['attacks'].append(path)
        else:
            out['extra'].append(path)
    out['attacks'].sort()
    return out


def _clip_state_name(kf_path: str) -> str:
    base = os.path.splitext(os.path.basename(kf_path))[0]
    return re.sub(r'[^A-Za-z0-9]', '', base)


def build_attack_events(clips: dict) -> list:
    """attackStart event names, shared verbatim with RACE ATKE generation."""
    return [f'attackStart_TES4_{_clip_state_name(p)}'
            for p in clips['attacks']]


def state_defs(clips: dict) -> list:
    """The graph's state list, shared by the behavior XML and the
    animationdata manifest: (state_name, kf_path, looping, enter_evt,
    end_evt) tuples, Idle first (state id 0).

    CombatStance is a looping idle-clip state entered on combatStanceStart
    (routed from the engine's ActionDraw) — the combat-facing stance pose.
    The weaponDraw reply the combat controller waits for is sent by the
    root-level StartCombat/StopCombat expression-modifier pair (vanilla
    quadruped layout), not by this state."""
    defs = []
    if clips['idle']:
        defs.append(('Idle', clips['idle'], True, None, None))
    for st, (_names, enter, _exit) in LOCOMOTION_STATES.items():
        if st in clips['locomotion']:
            defs.append((st, clips['locomotion'][st], True, enter, None))
    if clips['idle']:
        defs.append(('CombatStance', clips['idle'], True,
                     'combatStanceStart', None))
    for st, (_names, enter, end_evt) in SINGLE_PLAY.items():
        if st in clips['single']:
            defs.append((st, clips['single'][st], False, enter, end_evt))
    for kf, evt in zip(clips['attacks'], build_attack_events(clips)):
        defs.append((f'Attack_{_clip_state_name(kf)}', kf, False, evt,
                     'attackStop'))
    return defs


# ---------------------------------------------------------------------------
# XML builders
# ---------------------------------------------------------------------------

def build_project_xml(character_file: str) -> str:
    pf = HkxPackfile(first_id=9)
    sd = pf.add('hkbProjectStringData')
    pd = pf.add('hkbProjectData')
    top = pf.add('hkRootLevelContainer')

    sd.param_array('animationFilenames', [])
    sd.param_array('behaviorFilenames', [])
    sd.param_strings('characterFilenames', [character_file])
    sd.param_array('eventNames', [])
    sd.param('animationPath', '')
    sd.param('behaviorPath', '')
    sd.param('characterPath', '')
    sd.param('fullPathToSource', '')

    pd.param('worldUpWS', '(0.000000 0.000000 1.000000 0.000000)')
    pd.param('stringData', sd.ref)
    pd.param('defaultEventMode', 'EVENT_MODE_IGNORE_FROM_GENERATOR')

    top.param_structs('namedVariants', [
        [('name', 'hkbProjectData'), ('className', 'hkbProjectData'),
         ('variant', pd.ref)]])
    return pf.render(top)


def build_character_xml(name: str, anim_files: list, behavior_file: str,
                        n_bones: int, capsule_height: float = 1.7,
                        capsule_radius: float = 0.4) -> str:
    pf = HkxPackfile(first_id=27)
    mirror = pf.add('hkbMirroredSkeletonInfo')
    strings = pf.add('hkbCharacterStringData')
    values = pf.add('hkbVariableValueSet')
    cdata = pf.add('hkbCharacterData')
    top = pf.add('hkRootLevelContainer')

    mirror.param('mirrorAxis', '(1.000000 0.000000 0.000000 0.000000)')
    mirror.param_array('bonePairMap', list(range(n_bones)))

    strings.param_array('deformableSkinNames', [])
    strings.param_array('rigidSkinNames', [])
    strings.param_strings('animationNames', anim_files)
    strings.param_array('animationFilenames', [])
    strings.param_array('characterPropertyNames', [])
    strings.param_array('retargetingSkeletonMapperFilenames', [])
    strings.param_array('lodNames', [])
    strings.param_array('mirroredSyncPointSubstringsA', [])
    strings.param_array('mirroredSyncPointSubstringsB', [])
    strings.param('name', name)
    strings.param('rigName', 'Character Assets\\skeleton.HKX')
    strings.param('ragdollName', 'Character Assets\\skeleton.HKX')
    strings.param('behaviorFilename', behavior_file)

    values.param_structs('wordVariableValues', [])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    cdata.param_raw('characterControllerInfo', (
        '<hkobject>\n'
        f'\t<hkparam name="capsuleHeight">{capsule_height:.6f}</hkparam>\n'
        f'\t<hkparam name="capsuleRadius">{capsule_radius:.6f}</hkparam>\n'
        '\t<hkparam name="collisionFilterInfo">1</hkparam>\n'
        '\t<hkparam name="characterControllerCinfo">null</hkparam>\n'
        '</hkobject>'))
    cdata.param('modelUpMS', '(0.000000 0.000000 1.000000 0.000000)')
    cdata.param('modelForwardMS', '(0.000000 1.000000 0.000000 0.000000)')
    cdata.param('modelRightMS', '(1.000000 -0.000000 -0.000000 0.000000)')
    cdata.param_structs('characterPropertyInfos', [])
    cdata.param_array('numBonesPerLod', [])
    cdata.param('characterPropertyValues', values.ref)
    cdata.param('footIkDriverInfo', 'null')
    cdata.param('handIkDriverInfo', 'null')
    cdata.param('stringData', strings.ref)
    cdata.param('mirroredSkeletonInfo', mirror.ref)
    cdata.param('scale', '1.000000')

    top.param_structs('namedVariants', [
        [('name', 'hkbCharacterData'), ('className', 'hkbCharacterData'),
         ('variant', cdata.ref)]])
    return pf.render(top)


_TRANSITION_TMPL = '''<hkobject>
\t<hkparam name="triggerInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="initiateInterval">
\t\t<hkobject>
\t\t\t<hkparam name="enterEventId">-1</hkparam>
\t\t\t<hkparam name="exitEventId">-1</hkparam>
\t\t\t<hkparam name="enterTime">0.000000</hkparam>
\t\t\t<hkparam name="exitTime">0.000000</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="transition">{effect}</hkparam>
\t<hkparam name="condition">null</hkparam>
\t<hkparam name="eventId">{event_id}</hkparam>
\t<hkparam name="toStateId">{to_state}</hkparam>
\t<hkparam name="fromNestedStateId">0</hkparam>
\t<hkparam name="toNestedStateId">0</hkparam>
\t<hkparam name="priority">0</hkparam>
\t<hkparam name="flags">FLAG_IS_LOCAL_WILDCARD|FLAG_DISABLE_CONDITION</hkparam>
</hkobject>'''

_TRIGGER_TMPL = '''<hkobject>
\t<hkparam name="localTime">{time:.6f}</hkparam>
\t<hkparam name="event">
\t\t<hkobject>
\t\t\t<hkparam name="id">{event_id}</hkparam>
\t\t\t<hkparam name="payload">null</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="relativeToEndOfClip">{rel}</hkparam>
\t<hkparam name="acyclic">false</hkparam>
\t<hkparam name="isAnnotation">false</hkparam>
</hkobject>'''

_VARIABLE_INFO_TMPL = '''<hkobject>
\t<hkparam name="role">
\t\t<hkobject>
\t\t\t<hkparam name="role">ROLE_DEFAULT</hkparam>
\t\t\t<hkparam name="flags">0</hkparam>
\t\t</hkobject>
\t</hkparam>
\t<hkparam name="type">VARIABLE_TYPE_{vtype}</hkparam>
</hkobject>'''

_BINDING_TMPL = '''<hkobject>
\t<hkparam name="memberPath">{member}</hkparam>
\t<hkparam name="variableIndex">{var_index}</hkparam>
\t<hkparam name="bitIndex">-1</hkparam>
\t<hkparam name="bindingType">BINDING_TYPE_VARIABLE</hkparam>
</hkobject>'''

# The engine-side graph interface: SSE's movement controller / combat / AI
# bind these by name at graph init (every vanilla creature behavior declares
# them — vanilla dogbehavior has 65 variables; this is the engine-set/read
# subset).  A graph with NO variables leaves the movement hookup dead: the
# actor plays its start state forever and never walks or reacts.
# Third field = initial word value.  Vanilla dogbehavior inits IsAttackReady
# and bEquipOK to 1 — the combat controller reads them before ever sending
# an attackStart_* event, so a 0 default means the actor follows its target
# but NEVER attacks (2026-07-09 no-attacks root cause, with the weaponDraw
# reply below).  iCombatStance is engine-written on stance changes and
# drives the StartCombat/StopCombat expression pair.
ENGINE_VARIABLES = [
    ('Speed', 'REAL', 0), ('Direction', 'REAL', 0), ('TurnDelta', 'REAL', 0),
    ('TurnDeltaDamped', 'REAL', 0), ('SpeedSampled', 'REAL', 0),
    ('staggerMagnitude', 'REAL', 0), ('staggerDirection', 'REAL', 0),
    ('iState', 'INT32', 0), ('iGetUpType', 'INT32', 0),
    ('iCharacterSelector', 'INT32', 0), ('iCombatStance', 'INT32', 0),
    ('IsAttacking', 'BOOL', 0), ('IsAttackReady', 'BOOL', 1),
    ('bEquipOK', 'BOOL', 1),
    ('IsRecoiling', 'BOOL', 0), ('IsStaggering', 'BOOL', 0),
    ('IsBleedingOut', 'BOOL', 0), ('IsBashing', 'BOOL', 0),
    ('bAnimationDriven', 'BOOL', 0), ('bAllowRotation', 'BOOL', 0),
    ('bHeadTracking', 'BOOL', 0), ('bCanHeadTrack', 'BOOL', 0),
    ('bDisableHeadTrack', 'BOOL', 0), ('bForceIdleStop', 'BOOL', 0),
]


def movement_type_names(name: str) -> list:
    """The creature's engine movement-type names — the CONTRACT that makes an
    actor movable at all (2026-07-09, the tc-can't-move root cause).

    The engine registers an actor's movement types by enumerating the ROOT
    behavior graph's variables named `iState_<X>` and looking up the MOVT
    record whose MNAM == <X> (ck-cmd RetargetCreature.cpp does exactly this
    rename+MOVT-clone when retargeting creatures; vanilla dogbehavior
    declares iState_DogDefault/iState_DogRun matching MOVT MNAM DogDefault/
    DogRun). A graph with NO iState_* variables gives the movement
    controller ZERO movement types: the actor cannot move even under
    console `tc` control, no locomotion events are ever sent, and it idles
    forever — records, packages, clips and cache all being correct.

    These names are declared as INT32 graph variables here AND emitted as
    MOVT records by tes5_import/creature_races.py (via the manifest), so
    consistency is by construction, like the ATKE attack events.
    """
    base = f'TES4{name.lower()}'
    return [f'{base}Default', f'{base}Run']


def build_behavior_xml(behavior_name: str, clips: dict,
                       hit_times: dict = None,
                       movement_types: list = None,
                       speeds: dict = None,
                       ragdoll: dict = None) -> str:
    """The generated v1 state machine (see module docstring).

    hit_times: {state_name: [seconds]} — Oblivion 'Hit' text-key times for
    attack clips, emitted as preHitFrame/HitFrame triggers (the engine's
    attack-damage contract; without HitFrame an attack never deals damage).

    movement_types: MOVT MNAM strings (movement_type_names()) declared as
    `iState_<X>` INT32 variables — the engine's movement-type registration
    contract; without them the actor cannot move at all.

    speeds: {'walk': u/s, 'run': u/s, ...} clip root-motion speeds — anchor
    weights for the MoveForward parametric walk/run blend (vanilla
    ForwardWalkBlend: children weighted by natural clip speed, blend
    parameter bound to SpeedSampled, flags=17 SYNC|PARAMETRIC).

    ragdoll: hkx_ragdoll.ragdoll_info() dict — enables the death/ragdoll
    wrapper states (DeathAnimation/Ragdoll/RagdollInstant routing, mirrors
    the vanilla dogbehavior root SM). Oblivion creatures have no death
    animations: death IS the ragdoll.
    """
    hit_times = hit_times or {}
    movement_types = movement_types or []
    speeds = speeds or {}
    # ---- event vocabulary: standard + per-attack ----
    events = ['moveStart', 'moveStop', 'moveForward', 'moveBackward',
              'turnLeft', 'turnRight', 'turnStop', 'swimStart', 'swimStop',
              'recoilStart', 'recoilStop', 'recoilLargeStart',
              'staggerStart', 'staggerStop',
              'combatStanceStart', 'combatStanceStop',
              'weaponDraw', 'weaponSheathe',
              'attackStop', 'returnToDefault', 'deathStart', 'IdleStop',
              'DeathAnimation', 'Ragdoll', 'RagdollInstant',
              'AddRagdollToWorld', 'RemoveCharacterControllerFromWorld',
              'SoundPlay', 'preHitFrame', 'HitFrame', 'FootFront', 'FootBack']
    attack_events = build_attack_events(clips)
    events += attack_events
    eid = {n: i for i, n in enumerate(events)}

    pf = HkxPackfile(first_id=80)

    # blend effects: smooth 0.3s for locomotion, snappier 0.2s reset for hits
    fx_smooth = pf.add('hkbBlendingTransitionEffect')
    for obj, nm, dur, mode in ((fx_smooth, 'BlendSmooth', 0.3,
                                'SELF_TRANSITION_MODE_CONTINUE_IF_CYCLIC'),):
        obj.param('variableBindingSet', 'null')
        obj.param('userData', 0)
        obj.param('name', nm)
        obj.param('selfTransitionMode', mode)
        obj.param('eventMode', 'EVENT_MODE_DEFAULT')
        obj.param('duration', f'{dur:.6f}')
        obj.param('toGeneratorStartTimeFraction', '0.000000')
        obj.param('flags', 'FLAG_IGNORE_FROM_WORLD_FROM_MODEL')
        obj.param('endMode', 'END_MODE_NONE')
        obj.param('blendCurve', 'BLEND_CURVE_SMOOTH')

    # ---- states ----
    defs = state_defs(clips)
    if not defs:
        raise ValueError('creature has no usable clips')

    # variable table is fixed up-front so bindings inside the state loop can
    # reference indices (iState_<MOVT MNAM> registration: see
    # movement_type_names).  Initial values: loco state id for the iState
    # family, declared defaults otherwise (IsAttackReady/bEquipOK = 1).
    loco_id = next((i for i, d in enumerate(defs) if d[0] == 'MoveForward'), 0)
    variables = ([(n, t, iv) for n, t, iv in ENGINE_VARIABLES]
                 + [(f'iState_{mt}', 'INT32', loco_id)
                    for mt in movement_types])
    var_values = [loco_id if n == 'iState' else iv
                  for n, _t, iv in variables]
    vidx = {n: i for i, (n, _t, _iv) in enumerate(variables)}

    def _binding_set(pairs):
        """hkbVariableBindingSet from (memberPath, variable name) pairs."""
        b = pf.add('hkbVariableBindingSet')
        b.param_raw('bindings',
                    '\n'.join(_BINDING_TMPL.format(member=m,
                                                   var_index=vidx[v])
                              for m, v in pairs),
                    numelements=len(pairs))
        b.param('indexOfBindingToEnable', -1)
        return b

    def _clip(name, kf_path, looping, triggers_ref='null'):
        clip = pf.add('hkbClipGenerator')
        clip.param('variableBindingSet', 'null')
        clip.param('userData', 0)
        clip.param('name', name)
        clip.param('animationName',
                   'Animations\\' + _clip_state_name(kf_path) + '.hkx')
        clip.param('triggers', triggers_ref)
        clip.param('cropStartAmountLocalTime', '0.000000')
        clip.param('cropEndAmountLocalTime', '0.000000')
        clip.param('startTime', '0.000000')
        clip.param('playbackSpeed', '1.000000')
        clip.param('enforcedDuration', '0.000000')
        clip.param('userControlledTimeFraction', '0.000000')
        clip.param('animationBindingIndex', -1)
        clip.param('mode', 'MODE_LOOPING' if looping else 'MODE_SINGLE_PLAY')
        clip.param('flags', 0)
        return clip

    state_objs = []
    wildcards = []
    for state_id, (st_name, kf_path, looping, enter_evt, end_evt) in \
            enumerate(defs):
        trigger_items = []
        for t in hit_times.get(st_name, []):
            trigger_items.append(_TRIGGER_TMPL.format(
                time=max(0.0, t - 0.1), event_id=eid['preHitFrame'],
                rel='false'))
            trigger_items.append(_TRIGGER_TMPL.format(
                time=t, event_id=eid['HitFrame'], rel='false'))
        if end_evt:
            trigger_items.append(_TRIGGER_TMPL.format(
                time=0.0, event_id=eid[end_evt], rel='true'))
        triggers_ref = 'null'
        if trigger_items:
            trig = pf.add('hkbClipTriggerArray')
            trig.param_raw('triggers', '\n'.join(trigger_items),
                           numelements=len(trigger_items))
            triggers_ref = trig.ref
        clip = _clip(st_name, kf_path, looping, triggers_ref)

        # MoveForward with a distinct run clip becomes the vanilla parametric
        # speed blend (ForwardWalkBlend_Dog layout): children anchored at
        # each clip's natural root-motion speed, blendParameter driven by
        # SpeedSampled, flags 17 = SYNC|PARAMETRIC — the played animation
        # tracks the actor's actual speed instead of always looking like a
        # walk (2026-07-09 "moves fast but plays walk/idle" fix, with the
        # computed MOVT SPED values in tes5_import/creature_races.py).
        generator = clip
        if st_name == 'MoveForward' and clips.get('run') and speeds.get(
                'walk') and speeds.get('run'):
            run_clip = _clip('MoveForwardRun', clips['run'], True)
            children = []
            for child_gen, w in ((clip, speeds['walk']),
                                 (run_clip, speeds['run'])):
                ch = pf.add('hkbBlenderGeneratorChild')
                ch.param('variableBindingSet', 'null')
                ch.param('generator', child_gen.ref)
                ch.param('boneWeights', 'null')
                ch.param('weight', f'{w:.6f}')
                ch.param('worldFromModelWeight', '1.000000')
                children.append(ch)
            bind = _binding_set([('blendParameter', 'SpeedSampled')])
            blender = pf.add('hkbBlenderGenerator')
            blender.param('variableBindingSet', bind.ref)
            blender.param('userData', 0)
            blender.param('name', 'ForwardSpeedBlend')
            blender.param('referencePoseWeightThreshold', '0.000000')
            blender.param('blendParameter', '1.000000')
            blender.param('minCyclicBlendParameter', '0.000000')
            blender.param('maxCyclicBlendParameter', '1.000000')
            blender.param('indexOfSyncMasterChild', -1)
            blender.param('flags', 17)
            blender.param('subtractLastChild', False)
            blender.param_array('children', [c.ref for c in children])
            generator = blender

        state = pf.add('hkbStateMachineStateInfo')
        state.param('variableBindingSet', 'null')
        state.param_array('listeners', [])
        state.param('enterNotifyEvents', 'null')
        state.param('exitNotifyEvents', 'null')
        state.param('transitions', 'null')
        state.param('generator', generator.ref)
        state.param('name', st_name)
        state.param('stateId', state_id)
        state.param('probability', '1.000000')
        state.param('enable', True)
        state_objs.append(state)

        if enter_evt:
            wildcards.append((eid[enter_evt], state_id))

    # exits back to Idle
    idle_id = 0
    for evt in ('moveStop', 'turnStop', 'swimStop', 'attackStop',
                'recoilStop', 'staggerStop', 'returnToDefault',
                'combatStanceStop', 'IdleStop'):
        wildcards.append((eid[evt], idle_id))

    # extra engine-sent aliases: moveForward re-enters forward locomotion
    # (sent on direction changes while moving), recoilLargeStart shares the
    # single recoil clip
    state_ids = {d[0]: i for i, d in enumerate(defs)}
    if 'MoveForward' in state_ids:
        wildcards.append((eid['moveForward'], state_ids['MoveForward']))
    if 'Recoil' in state_ids:
        wildcards.append((eid['recoilLargeStart'], state_ids['Recoil']))

    wild = pf.add('hkbStateMachineTransitionInfoArray')
    wild.param_raw(
        'transitions',
        '\n'.join(_TRANSITION_TMPL.format(effect=fx_smooth.ref,
                                          event_id=e, to_state=s)
                  for e, s in wildcards),
        numelements=len(wildcards))

    sm = pf.add('hkbStateMachine')
    sm.param('variableBindingSet', 'null')
    sm.param('userData', 0)
    sm.param('name', f'{behavior_name}Root')
    sm.param_raw('eventToSendWhenStateOrTransitionChanges', (
        '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
        '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
    sm.param('startStateChooser', 'null')
    sm.param('startStateId', idle_id)
    sm.param('returnToPreviousStateEventId', -1)
    sm.param('randomTransitionEventId', -1)
    sm.param('transitionToNextHigherStateEventId', -1)
    sm.param('transitionToNextLowerStateEventId', -1)
    sm.param('syncVariableIndex', -1)
    sm.param('wrapAroundStateId', False)
    sm.param('maxSimultaneousTransitions', 32)
    sm.param('startStateMode', 'START_STATE_MODE_DEFAULT')
    sm.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
    sm.param_array('states', [s.ref for s in state_objs])
    sm.param('wildcardTransitions', wild.ref)

    # ---- variables / events tables ----
    strings = pf.add('hkbBehaviorGraphStringData')
    strings.param_strings('eventNames', events)
    strings.param_array('attributeNames', [])
    strings.param_strings('variableNames', [n for n, _t, _iv in variables])
    strings.param_array('characterPropertyNames', [])

    values = pf.add('hkbVariableValueSet')
    values.param_structs('wordVariableValues',
                         [[('value', v)] for v in var_values])
    values.param_array('quadVariableValues', [])
    values.param_array('variantVariableValues', [])

    gdata = pf.add('hkbBehaviorGraphData')
    gdata.param_array('attributeDefaults', [])
    gdata.param_raw('variableInfos',
                    '\n'.join(_VARIABLE_INFO_TMPL.format(vtype=t)
                              for _n, t, _iv in variables),
                    numelements=len(variables))
    gdata.param_structs('characterPropertyInfos', [])
    gdata.param_structs('eventInfos', [[('flags', 0)]] * len(events))
    gdata.param('variableInitialValues', values.ref)
    gdata.param('stringData', strings.ref)

    # ---- engine movement hookup (mirrors the vanilla quadruped root) ----
    # The engine samples the graph's animation-driven movement speed through
    # a BSSpeedSamplerModifier bound to iState/Direction/Speed/SpeedSampled.
    # Without it AI pathing has no speed to drive, the actor never receives
    # movement, and it stands in its idle forever (combat can't approach
    # either).  Vanilla wraps the whole locomotion state machine in a
    # hkbModifierGenerator under a single-state root state machine; copy
    # that layout verbatim (userData values included).
    sampler_binds = _binding_set([('state', 'iState'),
                                  ('direction', 'Direction'),
                                  ('goalSpeed', 'Speed'),
                                  ('speedOut', 'SpeedSampled')])

    sampler = pf.add('BSSpeedSamplerModifier')
    sampler.param('variableBindingSet', sampler_binds.ref)
    sampler.param('userData', 2)
    sampler.param('name', 'BSSpeedSamplerModifier')
    sampler.param('enable', True)
    sampler.param('state', -1)
    sampler.param('direction', '0.000000')
    sampler.param('goalSpeed', '0.000000')
    sampler.param('speedOut', '0.000000')

    # ---- combat stance handshake (verbatim vanilla quadruped layout) ----
    # The engine's ActionDraw routes combatStanceStart (IDLE record); combat
    # then WAITS for the graph to reply with a weaponDraw event before ever
    # sending an attackStart_*.  Vanilla sends that reply from a root-level
    # hkbEventDrivenModifier/hkbEvaluateExpressionModifier pair (StartCombat/
    # StopCombat), NOT from state notify events — an actor without this pair
    # chases its target forever and never attacks.
    def _combat_eem(name, stance_val, reply_evt):
        arr = pf.add('hkbExpressionDataArray')
        arr.param_raw('expressionsData', (
            '<hkobject>\n'
            f'\t<hkparam name="expression">iCombatStance = {stance_val}'
            '</hkparam>\n'
            '\t<hkparam name="assignmentVariableIndex">-1</hkparam>\n'
            '\t<hkparam name="assignmentEventIndex">-1</hkparam>\n'
            '\t<hkparam name="eventMode">EVENT_MODE_SEND_ONCE</hkparam>\n'
            '</hkobject>\n'
            '<hkobject>\n'
            f'\t<hkparam name="expression">{reply_evt} if '
            f'(iCombatStance == {stance_val})</hkparam>\n'
            '\t<hkparam name="assignmentVariableIndex">-1</hkparam>\n'
            '\t<hkparam name="assignmentEventIndex">-1</hkparam>\n'
            '\t<hkparam name="eventMode">EVENT_MODE_SEND_ON_FALSE_TO_TRUE'
            '</hkparam>\n'
            '</hkobject>'), numelements=2)
        eem = pf.add('hkbEvaluateExpressionModifier')
        eem.param('variableBindingSet', 'null')
        eem.param('userData', 2)
        eem.param('name', name)
        eem.param('enable', True)
        eem.param('expressions', arr.ref)
        return eem

    def _edm(name, modifier_ref, activate, deactivate, active_by_default):
        edm = pf.add('hkbEventDrivenModifier')
        edm.param('variableBindingSet', 'null')
        edm.param('userData', 1)
        edm.param('name', name)
        edm.param('enable', True)
        edm.param('modifier', modifier_ref)
        edm.param('activateEventId', activate)
        edm.param('deactivateEventId', deactivate)
        edm.param('activeByDefault', active_by_default)
        return edm

    stop_combat = _edm('StopCombat_EDM',
                       _combat_eem('StopCombat_EEM', 0, 'weaponSheathe').ref,
                       eid['combatStanceStop'], eid['combatStanceStart'],
                       True)
    start_combat = _edm('StartCombat_EDM',
                        _combat_eem('StartCombat_EEM', 1, 'weaponDraw').ref,
                        eid['combatStanceStart'], eid['combatStanceStop'],
                        False)

    mod_list = pf.add('hkbModifierList')
    mod_list.param('variableBindingSet', 'null')
    mod_list.param('userData', 1)
    mod_list.param('name', 'RootModifierList')
    mod_list.param('enable', True)
    mod_list.param_array('modifiers', [stop_combat.ref, start_combat.ref,
                                       sampler.ref])

    mod_gen = pf.add('hkbModifierGenerator')
    mod_gen.param('variableBindingSet', 'null')
    mod_gen.param('userData', 1)
    mod_gen.param('name', 'RootModifierGenerator')
    mod_gen.param('modifier', mod_list.ref)
    mod_gen.param('generator', sm.ref)

    def _root_state(state_id, name, generator_ref, enter_evt_name=None,
                    transitions_ref='null'):
        enter_ref = 'null'
        if enter_evt_name:
            arr = pf.add('hkbStateMachineEventPropertyArray')
            arr.param_raw('events', (
                '<hkobject>\n'
                f'\t<hkparam name="id">{eid[enter_evt_name]}</hkparam>\n'
                '\t<hkparam name="payload">null</hkparam>\n'
                '</hkobject>'), numelements=1)
            enter_ref = arr.ref
        st = pf.add('hkbStateMachineStateInfo')
        st.param('variableBindingSet', 'null')
        st.param_array('listeners', [])
        st.param('enterNotifyEvents', enter_ref)
        st.param('exitNotifyEvents', 'null')
        st.param('transitions', transitions_ref)
        st.param('generator', generator_ref)
        st.param('name', name)
        st.param('stateId', state_id)
        st.param('probability', '1.000000')
        st.param('enable', True)
        return st

    root_states = [_root_state(0, 'Root', mod_gen.ref)]
    root_wild_ref = 'null'

    # ---- death / ragdoll wrapper states (vanilla dogbehavior root SM) ----
    # Oblivion creatures ship no death animations — death IS the ragdoll.
    # The engine's kill flow fires ActionDeathWait, whose IDLE tree
    # (tes5_import/creature_idles.py) sends DeathAnimation or Ragdoll; the
    # wrapper states power the ragdoll (skeleton.hkx hkaRagdollInstance) and
    # notify AddRagdollToWorld / RemoveCharacterControllerFromWorld, which
    # the engine itself consumes.  Without them `kill` leaves the actor
    # standing in its idle forever.
    if ragdoll and clips['idle']:
        pb0, pb1, pb2 = ragdoll['pose_bones']

        def _powered_ragdoll(name, max_force, mode):
            bones_arr = pf.add('hkbBoneIndexArray')
            bones_arr.param('variableBindingSet', 'null')
            bones_arr.param_array('boneIndices', [])
            weights = pf.add('hkbBoneWeightArray')
            weights.param('variableBindingSet', 'null')
            weights.param_array('boneWeights', [])
            m = pf.add('hkbPoweredRagdollControlsModifier')
            m.param('variableBindingSet', 'null')
            m.param('userData', 1)
            m.param('name', name)
            m.param('enable', True)
            m.param_raw('controlData', (
                '<hkobject>\n'
                f'\t<hkparam name="maxForce">{max_force:.6f}</hkparam>\n'
                '\t<hkparam name="tau">0.800000</hkparam>\n'
                '\t<hkparam name="damping">1.000000</hkparam>\n'
                '\t<hkparam name="proportionalRecoveryVelocity">2.000000'
                '</hkparam>\n'
                '\t<hkparam name="constantRecoveryVelocity">1.000000'
                '</hkparam>\n'
                '</hkobject>'))
            m.param('bones', bones_arr.ref)
            m.param_raw('worldFromModelModeData', (
                '<hkobject>\n'
                f'\t<hkparam name="poseMatchingBone0">{pb0}</hkparam>\n'
                f'\t<hkparam name="poseMatchingBone1">{pb1}</hkparam>\n'
                f'\t<hkparam name="poseMatchingBone2">{pb2}</hkparam>\n'
                f'\t<hkparam name="mode">{mode}</hkparam>\n'
                '</hkobject>'))
            m.param('boneWeights', weights.ref)
            return m

        def _mod_state_gen(name, modifiers, clip_name):
            # objects must be defined before their referencers (hkxcmd
            # parser rejects forward references)
            pose_clip = _clip(clip_name, clips['idle'], True)
            lst = pf.add('hkbModifierList')
            lst.param('variableBindingSet', 'null')
            lst.param('userData', 0)
            lst.param('name', f'{name}_ML')
            lst.param('enable', True)
            lst.param_array('modifiers', [m.ref for m in modifiers])
            gen = pf.add('hkbModifierGenerator')
            gen.param('variableBindingSet', 'null')
            gen.param('userData', 1)
            gen.param('name', f'{name}_MG')
            gen.param('modifier', lst.ref)
            gen.param('generator', pose_clip.ref)
            return gen

        # falling-over stage: powered ragdoll drives toward the animated
        # pose; the contact listener converts floor contact into a Ragdoll
        # event (vanilla CollisionListener), completing the collapse
        contact_bones = pf.add('hkbBoneIndexArray')
        contact_bones.param('variableBindingSet', 'null')
        contact_bones.param_array('boneIndices',
                                  list(range(ragdoll['parts'])))
        listener = pf.add('BSRagdollContactListenerModifier')
        listener.param('variableBindingSet', 'null')
        listener.param('userData', 2)
        listener.param('name', 'CollisionListener')
        listener.param('enable', True)
        listener.param_raw('contactEvent', (
            '<hkobject>\n'
            f'\t<hkparam name="id">{eid["Ragdoll"]}</hkparam>\n'
            '\t<hkparam name="payload">null</hkparam>\n'
            '</hkobject>'))
        listener.param('bones', contact_bones.ref)

        anim2rag = _mod_state_gen(
            'AnimateToRagdoll',
            [_powered_ragdoll('PoweredRagdollMatching', 200.0,
                              'WORLD_FROM_MODEL_MODE_COMPUTE'), listener],
            'AnimateToRagdollPose')
        full_rag = _mod_state_gen(
            'FullyRagdoll',
            [_powered_ragdoll('PoweredRagdollNoMatching', 0.0,
                              'WORLD_FROM_MODEL_MODE_RAGDOLL')],
            'FullyRagdollPose')

        rag_fx = pf.add('hkbBlendingTransitionEffect')
        rag_fx.param('variableBindingSet', 'null')
        rag_fx.param('userData', 0)
        rag_fx.param('name', 'RagdollBlend')
        rag_fx.param('selfTransitionMode',
                     'SELF_TRANSITION_MODE_CONTINUE_IF_CYCLIC')
        rag_fx.param('eventMode', 'EVENT_MODE_DEFAULT')
        rag_fx.param('duration', '0.200000')
        rag_fx.param('toGeneratorStartTimeFraction', '0.000000')
        rag_fx.param('flags', 'FLAG_IGNORE_FROM_WORLD_FROM_MODEL')
        rag_fx.param('endMode', 'END_MODE_NONE')
        rag_fx.param('blendCurve', 'BLEND_CURVE_SMOOTH')

        a2r_trans = pf.add('hkbStateMachineTransitionInfoArray')
        a2r_trans.param_raw(
            'transitions',
            _TRANSITION_TMPL.format(effect=rag_fx.ref,
                                    event_id=eid['Ragdoll'], to_state=2),
            numelements=1)

        root_states.append(_root_state(1, 'AnimateToRagdoll', anim2rag.ref,
                                       'AddRagdollToWorld', a2r_trans.ref))
        root_states.append(_root_state(
            2, 'Fully Ragdoll', full_rag.ref,
            'RemoveCharacterControllerFromWorld'))

        root_wild = pf.add('hkbStateMachineTransitionInfoArray')
        root_wild.param_raw(
            'transitions',
            '\n'.join(_TRANSITION_TMPL.format(effect=e, event_id=ev,
                                              to_state=s)
                      for ev, s, e in (
                          (eid['DeathAnimation'], 1, rag_fx.ref),
                          (eid['Ragdoll'], 2, rag_fx.ref),
                          (eid['RagdollInstant'], 2, 'null'))),
            numelements=3)
        root_wild_ref = root_wild.ref

    root_sm = pf.add('hkbStateMachine')
    root_sm.param('variableBindingSet', 'null')
    root_sm.param('userData', 0)
    root_sm.param('name', f'{behavior_name}RootBehavior')
    root_sm.param_raw('eventToSendWhenStateOrTransitionChanges', (
        '<hkobject>\n\t<hkparam name="id">-1</hkparam>\n'
        '\t<hkparam name="payload">null</hkparam>\n</hkobject>'))
    root_sm.param('startStateChooser', 'null')
    root_sm.param('startStateId', 0)
    root_sm.param('returnToPreviousStateEventId', -1)
    root_sm.param('randomTransitionEventId', -1)
    root_sm.param('transitionToNextHigherStateEventId', -1)
    root_sm.param('transitionToNextLowerStateEventId', -1)
    root_sm.param('syncVariableIndex', -1)
    root_sm.param('wrapAroundStateId', False)
    root_sm.param('maxSimultaneousTransitions', 32)
    root_sm.param('startStateMode', 'START_STATE_MODE_DEFAULT')
    root_sm.param('selfTransitionMode', 'SELF_TRANSITION_MODE_NO_TRANSITION')
    root_sm.param_array('states', [s.ref for s in root_states])
    root_sm.param('wildcardTransitions', root_wild_ref)

    graph = pf.add('hkbBehaviorGraph')
    graph.param('variableBindingSet', 'null')
    graph.param('userData', 0)
    graph.param('name', f'{behavior_name}.hkb')
    graph.param('variableMode', 'VARIABLE_MODE_DISCARD_WHEN_INACTIVE')
    graph.param('rootGenerator', root_sm.ref)
    graph.param('data', gdata.ref)

    top = pf.add('hkRootLevelContainer')
    top.param_structs('namedVariants', [
        [('name', 'hkbBehaviorGraph'), ('className', 'hkbBehaviorGraph'),
         ('variant', graph.ref)]])
    return pf.render(top)


# ---------------------------------------------------------------------------
# Orchestrator
# ---------------------------------------------------------------------------

def _write_and_compile(xml: str, out_hkx: str):
    xml_path = out_hkx + '.xml'
    os.makedirs(os.path.dirname(os.path.abspath(out_hkx)), exist_ok=True)
    with open(xml_path, 'w', encoding='ascii', errors='replace',
              newline='\n') as f:
        f.write(xml)
    compile_hkx(xml_path, out_hkx)
    os.remove(xml_path)


def generate_creature_project(creature_dir: str, name: str, out_root: str,
                              fps: float = 30.0) -> dict:
    """Full project generation for one creature.

    Writes the hkx project tree plus `project_manifest.json` — the manifest
    is the contract consumed by asset_convert/animation_data.py (singlefile
    registration) and tes5_import (RACE ATKE/behavior-graph paths).
    """
    from asset_convert.hkx_anim import convert_clip_hkx
    from asset_convert.hkx_ragdoll import ragdoll_info
    from asset_convert.hkx_skeleton import generate_skeleton_hkx

    skeleton_nif = os.path.join(creature_dir, 'skeleton.nif')
    lname = name.lower()
    proj_dir = os.path.join(out_root, 'actors', 'tes4', lname)
    clips = classify_clips(creature_dir)

    bones = generate_skeleton_hkx(
        skeleton_nif, os.path.join(proj_dir, 'character assets',
                                   'skeleton.hkx'))
    ragdoll = ragdoll_info(skeleton_nif, bones)

    # convert every clip the graph uses, collecting per-clip metadata
    # (the run gait clip is not a state — it feeds the MoveForward
    # parametric speed blend — but still needs conversion + registration)
    convert_list = list(state_defs(clips))
    if clips.get('run'):
        convert_list.append(('MoveForwardRun', clips['run'], True, None,
                             None))
    attack_kfs = set(clips['attacks'])
    clip_meta, motions, failures = [], {}, []
    for st_name, kf, looping, _enter, end_evt in convert_list:
        stem = _clip_state_name(kf)
        out_hkx = os.path.join(proj_dir, 'animations', stem + '.hkx')
        try:
            clip, motion = convert_clip_hkx(kf, bones, out_hkx, fps=fps,
                                            is_attack=kf in attack_kfs)
        except Exception as e:  # keep going; report at the end
            failures.append((kf, f'{type(e).__name__}: {e}'))
            if st_name == 'MoveForwardRun':
                clips['run'] = None     # blender must not reference it
            continue
        clip_meta.append({
            'name': st_name,
            'stem': stem,
            'anim': 'Animations\\' + stem + '.hkx',
            'duration': float(clip.duration),
            'looping': looping,
            'end_event': end_evt,
            'sounds': [float(t) for t, s in clip.text_keys
                       if s.strip().lower().startswith('sound')],
            # Oblivion 'Hit' text keys → HitFrame triggers (damage contract)
            'hits': [float(t) for t, s in clip.text_keys
                     if s.strip().lower() == 'hit'],
        })
        if motion:
            motions[stem] = {
                'bone': motion['bone'],
                'duration': float(clip.duration),
                'times': motion['times'].tolist(),
                'translations': (motion['translations'].tolist()
                                 if motion['translations'] is not None
                                 else None),
                'rotations': (motion['rotations'].tolist()
                              if motion['rotations'] is not None else None),
            }

    # natural clip speeds (game units/sec) from root-motion endpoints —
    # ck-cmd calculateMOVTs: forwardWalk = |end translation| / duration.
    # These anchor both the MOVT SPED columns (tes5_import) and the
    # MoveForward parametric blend, so commanded speed == animation speed.
    def _speed_of(kf_path):
        if not kf_path:
            return None
        m = motions.get(_clip_state_name(kf_path))
        if not m or not m['translations'] or not m['duration']:
            return None
        end = m['translations'][-1]
        v = (end[0] ** 2 + end[1] ** 2) ** 0.5 / m['duration']
        return round(v, 3) if v > 1.0 else None

    speeds = {
        'walk': _speed_of(clips['locomotion'].get('MoveForward')),
        'run': _speed_of(clips.get('run')),
        'back': _speed_of(clips['locomotion'].get('MoveBackward')),
        'swim': _speed_of(clips['locomotion'].get('Swim')),
    }

    behavior_name = f'TES4{name.capitalize()}Behavior'
    move_types = movement_type_names(lname)
    _write_and_compile(
        build_behavior_xml(behavior_name, clips,
                           hit_times={c['name']: c['hits']
                                      for c in clip_meta if c['hits']},
                           movement_types=move_types,
                           speeds=speeds, ragdoll=ragdoll),
        os.path.join(proj_dir, 'behaviors', behavior_name.lower() + '.hkx'))
    # dedupe: states can share one animation file (Idle + CombatStance)
    anim_files = list(dict.fromkeys(c['anim'] for c in clip_meta))
    _write_and_compile(
        build_character_xml(
            f'TES4{name.capitalize()}Character', anim_files,
            f'Behaviors\\{behavior_name.lower()}.hkx', n_bones=len(bones)),
        os.path.join(proj_dir, 'characters', f'tes4{lname}character.hkx'))
    _write_and_compile(
        build_project_xml(f'Characters\\tes4{lname}character.hkx'),
        os.path.join(proj_dir, f'tes4{lname}project.hkx'))

    attack_states = [(evt, f'Attack_{_clip_state_name(kf)}')
                     for kf, evt in zip(clips['attacks'],
                                        build_attack_events(clips))]
    converted = {c['name'] for c in clip_meta}
    manifest = {
        'name': lname,
        'project_hkx': f'Actors\\TES4\\{lname}\\tes4{lname}project.hkx',
        'project_txt': f'tes4{lname}project.txt',
        'project_files': [f'Behaviors\\{behavior_name.lower()}.hkx',
                          f'Characters\\tes4{lname}character.hkx',
                          'Character Assets\\skeleton.HKX'],
        'anim_dir': f'meshes\\actors\\tes4\\{lname}\\animations',
        'clips': clip_meta,
        'attacks': [[e, s] for e, s in attack_states if s in converted],
        'movement_types': move_types,
        'speeds': speeds,
        'has_ragdoll': bool(ragdoll),
        'motions': motions,
        'bones': len(bones),
        'failures': failures,
    }
    with open(os.path.join(proj_dir, 'project_manifest.json'), 'w',
              encoding='utf-8') as f:
        json.dump(manifest, f)
    return manifest


if __name__ == '__main__':
    import argparse
    ap = argparse.ArgumentParser(
        description='Generate a full Skyrim LE behavior project from an '
                    'Oblivion creature folder')
    ap.add_argument('creature_dir')
    ap.add_argument('out_root')
    ap.add_argument('--name', help='creature name (default: folder name)')
    ap.add_argument('--fps', type=float, default=30.0)
    args = ap.parse_args()

    name = args.name or os.path.basename(os.path.normpath(args.creature_dir))
    manifest = generate_creature_project(args.creature_dir, name,
                                         args.out_root, fps=args.fps)
    print(f"project: {manifest['project_hkx']}")
    print(f"bones: {manifest['bones']}, "
          f"animations: {len(manifest['clips'])}")
    for evt, state in manifest['attacks']:
        print('  attack event:', evt, '->', state)
    for kf, err in manifest['failures']:
        print('  FAILED:', os.path.basename(kf), err)
