"""Morrowind magic effect index -> canonical name.

GENERATED by tools/generators/gen_morrowind_mgef_table.py -- do not edit.

TES3 addresses magic effects by index into an engine-fixed table, so this
is the vocabulary every converted SPEL, ENCH, ALCH and INGR names.
"""

#: Index -> effect name, in the order TES3 allocates them.
MW_EFFECT_NAMES = (
    'WaterBreathing',               # 0
    'SwiftSwim',                    # 1
    'WaterWalking',                 # 2
    'Shield',                       # 3
    'FireShield',                   # 4
    'LightningShield',              # 5
    'FrostShield',                  # 6
    'Burden',                       # 7
    'Feather',                      # 8
    'Jump',                         # 9
    'Levitate',                     # 10
    'SlowFall',                     # 11
    'Lock',                         # 12
    'Open',                         # 13
    'FireDamage',                   # 14
    'ShockDamage',                  # 15
    'FrostDamage',                  # 16
    'DrainAttribute',               # 17
    'DrainHealth',                  # 18
    'DrainSpellpoints',             # 19
    'DrainFatigue',                 # 20
    'DrainSkill',                   # 21
    'DamageAttribute',              # 22
    'DamageHealth',                 # 23
    'DamageMagicka',                # 24
    'DamageFatigue',                # 25
    'DamageSkill',                  # 26
    'Poison',                       # 27
    'WeaknesstoFire',               # 28
    'WeaknesstoFrost',              # 29
    'WeaknesstoShock',              # 30
    'WeaknesstoMagicka',            # 31
    'WeaknesstoCommonDisease',      # 32
    'WeaknesstoBlightDisease',      # 33
    'WeaknesstoCorprusDisease',     # 34
    'WeaknesstoPoison',             # 35
    'WeaknesstoNormalWeapons',      # 36
    'DisintegrateWeapon',           # 37
    'DisintegrateArmor',            # 38
    'Invisibility',                 # 39
    'Chameleon',                    # 40
    'Light',                        # 41
    'Sanctuary',                    # 42
    'NightEye',                     # 43
    'Charm',                        # 44
    'Paralyze',                     # 45
    'Silence',                      # 46
    'Blind',                        # 47
    'Sound',                        # 48
    'CalmHumanoid',                 # 49
    'CalmCreature',                 # 50
    'FrenzyHumanoid',               # 51
    'FrenzyCreature',               # 52
    'DemoralizeHumanoid',           # 53
    'DemoralizeCreature',           # 54
    'RallyHumanoid',                # 55
    'RallyCreature',                # 56
    'Dispel',                       # 57
    'Soultrap',                     # 58
    'Telekinesis',                  # 59
    'Mark',                         # 60
    'Recall',                       # 61
    'DivineIntervention',           # 62
    'AlmsiviIntervention',          # 63
    'DetectAnimal',                 # 64
    'DetectEnchantment',            # 65
    'DetectKey',                    # 66
    'SpellAbsorption',              # 67
    'Reflect',                      # 68
    'CureCommonDisease',            # 69
    'CureBlightDisease',            # 70
    'CureCorprusDisease',           # 71
    'CurePoison',                   # 72
    'CureParalyzation',             # 73
    'RestoreAttribute',             # 74
    'RestoreHealth',                # 75
    'RestoreSpellPoints',           # 76
    'RestoreFatigue',               # 77
    'RestoreSkill',                 # 78
    'FortifyAttribute',             # 79
    'FortifyHealth',                # 80
    'FortifySpellpoints',           # 81
    'FortifyFatigue',               # 82
    'FortifySkill',                 # 83
    'FortifyMagickaMultiplier',     # 84
    'AbsorbAttribute',              # 85
    'AbsorbHealth',                 # 86
    'AbsorbSpellPoints',            # 87
    'AbsorbFatigue',                # 88
    'AbsorbSkill',                  # 89
    'ResistFire',                   # 90
    'ResistFrost',                  # 91
    'ResistShock',                  # 92
    'ResistMagicka',                # 93
    'ResistCommonDisease',          # 94
    'ResistBlightDisease',          # 95
    'ResistCorprusDisease',         # 96
    'ResistPoison',                 # 97
    'ResistNormalWeapons',          # 98
    'ResistParalysis',              # 99
    'RemoveCurse',                  # 100
    'TurnUndead',                   # 101
    'SummonScamp',                  # 102
    'SummonClannfear',              # 103
    'SummonDaedroth',               # 104
    'SummonDremora',                # 105
    'SummonAncestralGhost',         # 106
    'SummonSkeletalMinion',         # 107
    'SummonLeastBonewalker',        # 108
    'SummonGreaterBonewalker',      # 109
    'SummonBonelord',               # 110
    'SummonWingedTwilight',         # 111
    'SummonHunger',                 # 112
    'SummonGoldenSaint',            # 113
    'SummonFlameAtronach',          # 114
    'SummonFrostAtronach',          # 115
    'SummonStormAtronach',          # 116
    'FortifyAttackBonus',           # 117
    'CommandCreatures',             # 118
    'CommandHumanoids',             # 119
    'BoundDagger',                  # 120
    'BoundLongsword',               # 121
    'BoundMace',                    # 122
    'BoundBattleAxe',               # 123
    'BoundSpear',                   # 124
    'BoundLongbow',                 # 125
    'ExtraSpell',                   # 126
    'BoundCuirass',                 # 127
    'BoundHelm',                    # 128
    'BoundBoots',                   # 129
    'BoundShield',                  # 130
    'BoundGloves',                  # 131
    'Corpus',                       # 132
    'Vampirism',                    # 133
    'SummonCenturionSphere',        # 134
    'SunDamage',                    # 135
    'StuntedMagicka',               # 136
    'SummonFabricant',              # 137
    'SummonCreature01',             # 138
    'SummonCreature02',             # 139
    'SummonCreature03',             # 140
    'SummonCreature04',             # 141
    'SummonCreature05',             # 142
)

#: Index -> the MEDT flags the engine ORs in at load (OpenMW `HardcodedFlags`).
MW_HARDCODED_FLAGS = (
    0x011c8, 0x011c0, 0x011c8, 0x011e0, 0x011e0, 0x011e0, 0x011e0, 0x011d0,
    0x011c0, 0x011c0, 0x011e0, 0x011c0, 0x11184, 0x11184, 0x001f0, 0x001f0,
    0x001f0, 0x011d2, 0x011f0, 0x011d0, 0x011d0, 0x011d1, 0x001d2, 0x001f0,
    0x001d0, 0x001d0, 0x001d1, 0x001f0, 0x011d0, 0x011d0, 0x011d0, 0x011d0,
    0x011d0, 0x011d0, 0x011d0, 0x011d0, 0x011d0, 0x001d0, 0x001d0, 0x011c8,
    0x031c0, 0x011c0, 0x011c0, 0x011c0, 0x01180, 0x011d8, 0x011d8, 0x011d0,
    0x011d0, 0x11180, 0x11180, 0x11180, 0x11180, 0x11180, 0x11180, 0x11180,
    0x11180, 0x011c4, 0x111b8, 0x01040, 0x0104c, 0x0104c, 0x0104c, 0x0104c,
    0x01040, 0x01040, 0x01040, 0x011c0, 0x011c0, 0x001cc, 0x001cc, 0x001cc,
    0x001cc, 0x001cc, 0x001c2, 0x001c0, 0x001c0, 0x001c0, 0x001c1, 0x011c2,
    0x011c0, 0x011c0, 0x011c0, 0x011c1, 0x011c0, 0x21192, 0x20190, 0x20190,
    0x20190, 0x21191, 0x011c0, 0x011c0, 0x011c0, 0x011c0, 0x011c0, 0x011c0,
    0x011c0, 0x011c0, 0x011c0, 0x011c0, 0x001c0, 0x11190, 0x09048, 0x09048,
    0x09048, 0x09048, 0x09048, 0x09048, 0x09048, 0x09048, 0x09048, 0x09048,
    0x09048, 0x09048, 0x09048, 0x09048, 0x09048, 0x011c0, 0x01180, 0x01180,
    0x05048, 0x05048, 0x05048, 0x05048, 0x05048, 0x05048, 0x01188, 0x05048,
    0x05048, 0x05048, 0x05048, 0x05048, 0x01048, 0x0104c, 0x01048, 0x00040,
    0x011c8, 0x01048, 0x01048, 0x01048, 0x01048, 0x01048, 0x01048,
)
