"""CTDA condition translation: TES4 (24-byte) → TES5 (32-byte).

This is a fresh implementation derived directly from the two xEdit function
tables (wbDefinitionsTES4.pas / wbDefinitionsTES5.pas) per the
`oblivion-to-skyrim-dialog` skill (references/conditions.md):

  - Re-pack 24 bytes → 32 bytes (field-compatible; Skyrim adds trailing fields).
  - Reconcile the function index against the two tables:
      * same index, same name  -> passthrough (138 functions)
      * same name, moved index -> remap (4 functions)
      * index reused for a different function, or removed -> drop
  - Remap FormID parameters to the output plugin's load order.

The remap/drop tables below were generated by joining the two function tables
on numeric index and on name; they are NOT hand-curated lore. See the skill's
conditions reference for the methodology.
"""

import struct

from .cell_family import expand_cell_families, or_groups
from .constants import ENGINE_GLOBAL_FORMIDS
from .ctda_bool import bool_outcomes
from .conditions_falloutnv import (FALLOUT_CTDA_SIZE, fallout_function,
                                   fallout_run_on)
from ..generated.ctda_param_types import CTDA_FORMID_PARAMS
from .text_reader import (_ENGINE_FIXED_FORMIDS, get_formid_index_offset,
                          remap_formid)

# --- CTDA type-byte bits (identical in TES4 and TES5) --------------------------
CTDA_OR = 0x01            # OR with the next condition
CTDA_RUN_ON_TARGET = 0x02 # evaluate against target, not subject
CTDA_USE_GLOBAL = 0x04    # comparison value is a GLOB FormID, not a float

# --- Dialogue-critical function indices (identical in both games) --------------
FUNC_GET_IS_ID = 72            # GetIsID(ref)

# DIAL FormIDs (24-bit) whose INFOs are reached ONLY through a TES4
# `Say <topic> <flag> <speak-as NPC> <flag>`.  Filled once per run by
# set_speak_as_topics(); see convert_ctda and talking_activators.py.
_SPEAK_AS_TOPICS: frozenset = frozenset()


# --------------------------------------------------------------------------
# Speak-as topic state
# --------------------------------------------------------------------------


def set_speak_as_topics(fids) -> None:
    """Register the run's speak-as topics (24-bit TES4 DIAL FormIDs)."""
    global _SPEAK_AS_TOPICS
    _SPEAK_AS_TOPICS = frozenset(f & 0x00FFFFFF for f in (fids or ()))


def get_speak_as_topics() -> frozenset:
    return _SPEAK_AS_TOPICS


FUNC_GET_IN_FACTION = 71       # GetInFaction(fact)
#: GetOffersServicesNow(): true only while the actor is actively vending/training.
FUNC_GET_OFFERS_SERVICES_NOW = 255
FUNC_GET_STAGE = 58            # GetStage(quest)
FUNC_GET_STAGE_DONE = 59       # GetStageDone(quest, stage)
FUNC_GET_QUEST_RUNNING = 56    # GetQuestRunning(quest)
FUNC_GET_GLOBAL_VALUE = 74     # GetGlobalValue(glob)
FUNC_GET_IS_VOICE_TYPE = 426   # GetIsVoiceType(vtyp)  — TES5-only, no TES4 source

#: Speaker-as-actor conditions. See: docs/commentary/tes5_import_conditions.md#non-actor-speaker-drop
NON_ACTOR_SPEAKER_DROP = frozenset({
    72,    # GetIsID          -- compares the speaker's base form
    254,   # GetIsPlayableRace-- rides in from the QUST-level condition copy
})

# Run-on-Target conditions that must NOT be retargeted onto a specific
# reference. GetIsID asks "WHICH ACTOR is this?" and answers by comparing the
# runtime actor's BASE form; PlayerRef's base is vanilla Skyrim's 0x00000007,
# never the converted TES4 player NPC_ 0x01000007, so retargeting it onto the
# player yields a condition that can NEVER pass. That mistake silently killed
# 667 GREETING/bark INFOs across 101 topics — every affected NPC lost their
# whole topic list, because the greeting that opens it could not pass (Pinarus
# Inventius kept only quest-less 'rumors'). It falls back to RunOn=Target.
#
# Vanilla Skyrim.esm agrees on exactly this split: GetIsID appears with
# RunOn=Reference ZERO times, while GetIsRace(29), GetIsSex(125),
# GetInFaction(136) and GetFactionRank(22) all use RunOn=Reference->PlayerRef
# routinely.  Those four read live actor STATE rather than a base-form
# identity, so pinning them to the player is both legal and meaning-preserving
# — and it is the ONLY way they can evaluate inside a Say()-driven topic,
# because Skyrim's Say has no target at all (ObjectReference.psc:
# `Say(Topic, Actor akActorToSpeakAs, bool abSpeakInPlayersHead)` — the second
# arg is the SPEAKER, not the addressee; only menu dialogue populates the
# target that Actor.GetDialogueTarget() returns).  Leaving them on
# RunOn=Target inside a Say topic made every per-race/per-sex line evaluate
# against nothing, so the wrong response won: Valen Dreth taunted the player
# with lines written for a different race, and the CharacterGen intro never
# advanced past its first taunt.
_NO_TARGET_RETARGET_FUNCS = frozenset({
    72,    # GetIsID — base-form compare; never valid against PlayerRef
    68,    # GetIsClass — TES4 CLAS identity, same base-form problem
})

# --- Function-index reconciliation (data-derived; see module docstring) --------
# REMAP: TES4 index -> TES5 index for functions that exist in both games under
# the same name but at a DIFFERENT numeric slot. Verified by name-join of the
# two xEdit tables. (Functions renamed but kept at the same index — e.g.
# GetFatiguePercentage->GetStaminaPercentage at 128 — are passthrough and not
# listed here.)
_FUNC_REMAP = {
    101: 263,    # IsWeaponOut
    116: 459,    # GetCrimeGold
    127: 497,    # CanPayCrimeGold
    1122: 264,   # HasSpell (OBSE) -> TES5 HasSpell
}

#: TES5 GetCrimeGold / CanPayCrimeGold read the player's bounty in the SUBJECT's crime faction.
_PLAYER_BOUNTY_FUNCS = frozenset({459, 497})

# DROP: TES4 indices that either (a) have no TES5 entry at all, or (b) have a
# TES5 entry at that index naming a DIFFERENT function (reused slot). Leaving
# these unchanged would silently invoke the wrong TES5 function. Generated by
# index-join; comments record why.
_FUNC_DROP = frozenset({
    40,    # GetVampire — removed
    # Legacy VM variable reads — TES5 lists these indices but the legacy VM is
    # gone, so they never evaluate true.  Callers that can emit a CIS2 string
    # (convert_ctda_list_with_strings) translate them to GetVMScriptVariable/
    # GetVMQuestVariable INSTEAD of calling convert_ctda; every other path must
    # drop them rather than emit a condition that can never pass.
    53,    # GetScriptVariable  -> 630 GetVMScriptVariable (strings path only)
    79,    # GetQuestVariable   -> 629 GetVMQuestVariable  (strings path only)
    # NOTE: GetDisposition (76) is NOT dropped here — see _eval_disposition.
    # Dropping it made the condition vanish and the line unconditional, so all
    # three of Oblivion's disposition tiers fired at once and strangers got
    # intimate-friend greetings. It is now evaluated at a fixed disposition and
    # the whole INFO is dropped when its tier does not match.
    81,    # reused: TES5 IsRotating
    104,   # IsYielding — removed
    109,   # reused: TES5 IsWeaponSkillType (semantics changed)
    160,   # GetFurnitureMarkerID — removed
    171,   # IsPlayerInJail — removed
    180,   # reused: TES5 HasSameEditorLocAsRef
    197,   # reused: TES5 GetPCEnemyofFaction
    201,   # GetPCFactionSubmitAuthority — removed
    224,   # reused: TES5 GetVATSMode  (was GetIsPlayerBirthsign)
    227,   # reused: TES5 GetCannibal
    249,   # reused: TES5 IsInDialogueWithPlayer (was GetPCFame) — critical: see skill
    251,   # GetPCInfamy — removed
    258,   # reused: TES5 HasAssociationType
    259,   # reused: TES5 HasFamilyRelationship
    264,   # reused: TES5 HasSpell (was GetBarterGold)
    274,   # reused: TES5 IsSmallBump
    305,   # reused: TES5 GetPlayerAction
    313,   # reused: TES5 GetPairedAnimation
    323,   # reused: TES5 GetCombatState
    329,   # reused: TES5 IsFleeing
    362,   # reused: TES5 HasLinkedRef
    365,   # reused: TES5 IsChild
    # OBSE supplemental indices with no TES5 equivalent
    1107,  # IsAmmo
    1124,  # IsClassSkill
    1884,  # GetPCTrainingSessionsUsed
    # TES4 package-query funcs (2213-2233) — packages are restructured; drop
    2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224,
    2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233,
    2571,  # GetBaseAV3 — removed
    2573,  # IsNaked — removed
    2578,  # IsDiseased — removed
})


# Functions whose param1 is a RACE FormID in BOTH games (ptRace at the same
# index: 69 GetIsRace, 130 GetPCIsRace). TES4 RACE records are never imported
# (SKIP_TYPES) so the generic load-order remap would leave a dangling FormID —
# the CK's "Unable to find ... TESForm in TESConditionItem Parameter Init"
# warning, and a condition that can never be true in-game (2,650+ dialogue
# lines gated on race). Translate the param to the SAME Skyrim race the NPC
# converter assigns (RACE_MAP), so GetIsRace(speaker) keeps matching the
# converted actors and GetPCIsRace matches the player's Skyrim race.
_RACE_PARAM_FUNCS = frozenset({69, 130})


# --- Actor Value parameters --------------------------------------------------
# ptActorValue params are RAW INDICES into each game's actor-value table, and
# the two tables share not one entry: TES4 index 0 is Strength, TES5 index 0 is
# Aggression; TES4 5 is Endurance, TES5 5 is Assistance. Passing the index
# through unchanged therefore reads a completely unrelated value.
#
# That silently broke every guild in Morroblivion. Joining the Fighters Guild
# is gated on `GetActorValue Strength >= 30 AND GetActorValue Endurance >= 30`;
# converted verbatim it became `Aggression >= 30 AND Assistance >= 30`, and
# those are 0-3 enums that can never reach 30 at any level — so the recruiter
# always fell through to "You don't meet our requirements." The Thieves Guild
# (Agility/Personality -> Morality/One-Handed) failed the same way, as did
# ~600 conditions across the exports.
#
# SKYRIM HAS NO ATTRIBUTES. Strength, Intelligence, Willpower, Agility, Speed,
# Endurance, Personality and Luck simply do not exist as actor values, and no
# TES5 actor value is a faithful stand-in — every candidate (SpeedMult,
# HealRate, UnarmedDamage, ...) is on a different scale, so a 0-100 attribute
# threshold compared against one is arbitrary. An attribute gate is therefore
# DROPPED, which fails OPEN: the check becomes a no-op and the content behind
# it stays reachable. That is the faithful outcome here — Oblivion's attribute
# gates exist to keep an under-developed character out, and a Skyrim character
# has no way to satisfy them, so enforcing them would lock the content away
# permanently rather than merely early.
#
# Skills DO survive, under different names and indices, so a skill gate is
# remapped and keeps its threshold (both games score skills 0-100).
# Derived/status values that exist in both games are remapped too.
_TES4_AV_ATTRIBUTES = frozenset({
    0,   # Strength
    1,   # Intelligence
    2,   # Willpower
    3,   # Agility
    4,   # Speed
    5,   # Endurance
    6,   # Personality
    7,   # Luck
})

#: TES4 actor-value index -> TES5. See: docs/commentary/tes5_import_conditions.md#actor-value-vs-book-skill-table
_TES4_AV_TO_TES5 = {
    # --- derived / status values present in both games ---
    8:  24,   # Health          -> Health
    9:  25,   # Magicka         -> Magicka
    10: 26,   # Fatigue         -> Stamina
    11: 32,   # Encumbrance     -> CarryWeight
    # --- skills ---
    12: 10,   # Armorer         -> Smithing
    13: 26,   # Athletics       -> Stamina        (no Skyrim skill)
    14: 6,    # Blade           -> OneHanded
    15: 9,    # Block           -> Block
    16: 6,    # Blunt           -> OneHanded
    17: 6,    # HandToHand      -> OneHanded
    18: 11,   # HeavyArmor      -> HeavyArmor
    19: 16,   # Alchemy         -> Alchemy
    20: 18,   # Alteration      -> Alteration
    21: 19,   # Conjuration     -> Conjuration
    22: 20,   # Destruction     -> Destruction
    23: 21,   # Illusion        -> Illusion
    24: 21,   # Mysticism       -> Illusion       (Mysticism was folded in)
    25: 22,   # Restoration     -> Restoration
    26: 26,   # Acrobatics      -> Stamina        (no Skyrim skill)
    27: 12,   # LightArmor      -> LightArmor
    28: 8,    # Marksman        -> Archery
    29: 17,   # Mercantile      -> Speech
    30: 14,   # Security        -> Lockpicking
    31: 15,   # Sneak           -> Sneak
    32: 17,   # Speechcraft     -> Speech
    # --- AI / crime values present in both games ---
    33: 0,    # Aggression      -> Aggression
    34: 1,    # Confidence      -> Confidence
    35: 2,    # Energy          -> Energy
    36: 3,    # Responsibility  -> Morality
    38: 60,   # Fame            -> Fame
    39: 61,   # Infamy          -> Infamy
    # --- magic effect values present in both games ---
    41: 55,   # NightEyeBonus   -> NightEye
    45: 84,   # Blindness       -> Blindness
    46: 54,   # Chameleon       -> Invisibility   (nearest: partial concealment)
    47: 54,   # Invisibility    -> Invisibility
    52: 83,   # SpellAbsorbChance -> AbsorbChance
    48: 53,   # Paralysis       -> Paralysis
    55: 57,   # WaterBreathing  -> WaterBreathing
    56: 58,   # WaterWalking    -> WaterWalking
    58: 56,   # DetectLifeRange -> DetectLifeRange
    61: 41,   # ResistFire      -> ResistFire
    62: 43,   # ResistFrost     -> ResistFrost
    63: 45,   # ResistDisease   -> ResistDisease
    64: 44,   # ResistMagic     -> ResistMagic
    65: 39,   # ResistNormalWeapons -> DamageResist
    67: 40,   # ResistPoison    -> PoisonResist
    68: 42,   # ResistShock     -> ResistShock
}

# Condition functions whose param1 is a ptActorValue in BOTH games. Every one
# needs the index translated (or the whole condition dropped when it names an
# attribute). Sourced from xEdit's wbConditionFunctions tables; TES4-only
# entries (2571 GetBaseAV3, 2577 IsMajorRef, 1124 IsClassSkill) are already in
# _FUNC_DROP or have no TES5 counterpart, so they never reach here.
_AV_PARAM_FUNCS = frozenset({
    14,    # GetActorValue
    277,   # GetBaseActorValue
})


def _map_race_param(fid: int) -> 'int | None':
    """The Skyrim race a `GetIsRace` param must name to keep matching.

    This MUST resolve exactly as `_resolve_npc_race` does, including its
    fallback: an actor whose RACE is plugin-authored (Morroblivion adds
    mwBMRieklingRace, and TES4_RACE_FID_TO_EDID holds only the 15 vanilla
    Oblivion races) is converted with DEFAULT_RACE, so a condition naming that
    race must name DEFAULT_RACE too or it can never match the actors it was
    written for.

    Returning None here instead DROPPED the condition, and a dropped condition
    does not fail closed -- it fails OPEN.  mwGenericRieklingGreeting's three
    greetings ("What is it, human?", "What?", "Speak!") carry no INFO
    conditions of their own; the quest-level `GetIsRace(mwBMRieklingRace)` was
    the only thing keeping them on Rieklings.  With it deleted they became
    unconditioned greetings in a priority-47 quest, which outranks
    fbmwMSGreetings (44) -- so they won the greeting for EVERY actor in the
    plugin, including Fargoth, a Wood Elf.  That also cost him his "ring"
    topic: the topic is unlocked only by his own greeting's fragment, which
    never got to play.
    """
    from .constants import DEFAULT_RACE
    from .equivalents import RACE_MAP, TES4_RACE_FID_TO_EDID
    edid = TES4_RACE_FID_TO_EDID.get(fid & 0x00FFFFFF)
    if edid is None:
        return DEFAULT_RACE
    return RACE_MAP.get(edid, DEFAULT_RACE)


# FormIDs a CONDITION PARAMETER may keep at index 0. Both games define these
# at the same ids and the ENGINE owns the live copy, so a condition must read
# Skyrim's form rather than our converted duplicate:
#   0x07/0x14  the player base and PlayerRef
#   0x35-0x3A  GameYear, GameMonth, GameDay, GameHour, GameDaysPassed, TimeScale
# Everything else below 0x100 is a real Oblivion record and MUST remap.
_CONDITION_PASSTHROUGH_FIDS = frozenset(_ENGINE_FIXED_FORMIDS) | frozenset(
    ENGINE_GLOBAL_FORMIDS.values())


def _remap_formid(fid: int, offset: int) -> int:
    """Remap a TES4 FormID to the output plugin's load order.

    Engine-fixed forms (index 0, object id < 0x100) pass through UNCHANGED:
    Bethesda hardcodes the same ids in every game (Player NPC_ 0x7, PlayerRef
    0x14, DoorMarker 0x1, ...), and a condition evaluates against the RUNTIME
    form — the in-game player's base is vanilla Skyrim's 0x00000007, never our
    converted copy of the TES4 Player record. Shifting them rewrote
    `GetIsID(Player) [Target]` ("am I addressing the player?") on 3,761 INFOs
    to GetIsID(0x01000007), which can never pass; every stage-gated reveal
    greeting died, their unlock fragments never ran, and NPCs lost whole topic
    lists (Pinarus Inventius kept only 'Rumors'). This passthrough existed
    here before the override work unified condition remapping with
    text_reader.remap_formid (whose record-field contract is the opposite:
    references to the CONVERTED player copy 0x0100xxxx must keep shifting).

    Everything else delegates to text_reader.remap_formid so conditions shift
    identically to record fields — including overrides, which keep their
    master's index.
    The pass-through set is ENUMERATED, not "everything below 0x100":
    Oblivion.esm defines 127 records of its own down there — Tamriel WRLD 0x3C,
    gold 0xF, DASkeletonKey 0xB, 57 DIALs from 0xAA, 21 SKILs, 27 marker STATs
    — and passing those through hands the condition a vanilla Skyrim form of an
    unrelated type, or nothing at all. Measured: the two MQ08 Skeleton Key
    INFOs asked GetItemCount(0x0000000B) instead of 0x0100000B and the CK
    reported "Unable to find Function Info TESForm".

    The set is the player forms PLUS the six engine GLOBALS (GameYear 0x35 ..
    TimeScale 0x3A). Those six exist at IDENTICAL ids in both games —
    Skyrim.esm carries GameHour at 0x38 exactly as Oblivion.esm does — and the
    engine updates its own copies, so a condition must read Skyrim's clock and
    not our inert converted duplicate. Narrowing the set to the player forms
    alone and letting these remap cost 119 warnings on GetGlobalValue against
    0x01000038/0x01000037, worse than the 2 it fixed.
    """
    if (fid >> 24) == 0 and (fid & 0x00FFFFFF) in _CONDITION_PASSTHROUGH_FIDS:
        return fid
    return remap_formid(fid, offset)


# TES4 GetScriptVariable(53) reads a variable on the legacy (pre-Papyrus) script
# system.  Skyrim still LISTS function 53, but the legacy VM is gone and vanilla
# Skyrim.esm uses it exactly ZERO times; the live equivalent is
# GetVMScriptVariable(630), which reads a Papyrus property off a reference
# (4,290 vanilla uses between it and GetVMQuestVariable).  Param2 is a runtime
# string pointer, so the property NAME travels in a companion CIS2 subrecord as
# the mangled `::<name>_var` form (verified: `CIS2=::RadiantAelaBlock_var`).
#
# This is the gate a huge number of Oblivion quest packages actually use — e.g.
# FGC01Rats' escort package is `GetScriptVariable(PinarusREF, packageVAR) == 1`,
# set by the dialogue INFO that agrees to help.  Without this translation the
# condition silently invokes a dead function and the package never fires.
#
# GetQuestVariable(79) is the quest-script twin (`GetQuestVariable Arena,
# ReadyMatch` gates most of the Arena blademaster dialogue) and is equally dead
# in Skyrim; its live equivalent is GetVMQuestVariable(629).  Both use the same
# script_vars table — build_script_var_map indexes QUST FormIDs alongside refs.
GET_SCRIPT_VARIABLE = 53
GET_QUEST_VARIABLE = 79
GET_VM_SCRIPT_VARIABLE = 630
GET_VM_QUEST_VARIABLE = 629

# Legacy variable-read function -> live Papyrus-VM equivalent.
_VM_VAR_FUNCS = {
    GET_SCRIPT_VARIABLE: GET_VM_SCRIPT_VARIABLE,
    GET_QUEST_VARIABLE: GET_VM_QUEST_VARIABLE,
}
# CIS2 name for a script variable that does not exist: no converted script
# ever declares it, so the read yields 0 — the value TES4's GetScriptVariable
# returns for a scriptless ref or a missing variable.  See
# convert_script_var_ctda.
_UNRESOLVED_VAR_SENTINEL = '::TES4NoSuchVariable_var'


def papyrus_var_name(var: str) -> str:
    """Papyrus property name as a CIS2 script-variable reference.

    Must mirror the converter's property renaming (safe_property_name): the
    ::<name>_var lookup is against the COMPILED property, so a TES4 variable
    the converter had to rename (reserved word, ::temp collision) must be
    referenced by its renamed form.
    """
    from script_convert.constants import safe_property_name
    return f'::{safe_property_name(var)}_var'


# --- Disposition -> Relationship Rank ---------------------------------------
# Skyrim DOES have a disposition system; it is just not called that and is not
# a 0-100 scale. An NPC's friendliness is a RELATIONSHIP RANK from -4 to +4
# (Archnemesis, Enemy, Foe, Rival, Acquaintance, Friend, Confidant, Ally,
# Lover), default 0, read by condition function 419 GetRelationshipRank and
# settable from Papyrus via Actor.SetRelationshipRank. Oblivion's
# GetDisposition (76) therefore maps onto it rather than being dropped -- and it
# must be mapped, because CTDA index 76 is `FastTravel` in Skyrim, so passing
# the condition through unchanged would invoke an unrelated function.
#
# Oblivion uses GetDisposition on 1,751 conditions across 1,451 INFOs, tiering
# dialogue overwhelmingly at 30 and 70. The two scales line up like this, with
# Oblivion's neutral 40-60 band mapping to Acquaintance (0), the rank a Skyrim
# NPC starts at:
#
#     Oblivion disposition   Skyrim rank
#     0-19                   -2  Foe
#     20-39                  -1  Rival
#     40-60                   0  Acquaintance   <- both games' default
#     61-79                   1  Friend
#     80-100                  2  Confidant
#
# Ally (3) and Lover (4) are deliberately unused: Oblivion has no equivalent
# relationship, and reserving them keeps quest-granted ranks meaningful.
GET_DISPOSITION = 76
# CTDA index 403, NOT the engine function table's row number (419). A CTDA
# names its function by `opcode - 0x1000`, and GetRelationshipRank sits at
# opcode 0x1193 = 403 while occupying row 419 of the table. Confirmed three
# ways: the engine table's own opcode field, xEdit's wbConditionFunctions, and
# vanilla Skyrim.esm, which uses 403 in 298 INFO conditions and 419 in none.
# 419 is GetObjectiveCompleted(Quest, Integer) -- emitting that instead turns
# every converted disposition gate into an unrelated quest check.
GET_RELATIONSHIP_RANK = 403
#: PlayerRef, the ACTOR-typed parameter; never the player base NPC 0x07.
_PLAYER_REF_FORMID = 0x00000014

# Oblivion's default starting disposition, used when a comparison has to be
# resolved rather than translated.
DEFAULT_DISPOSITION = 50.0


def disposition_to_rank(disposition: float) -> int:
    """Oblivion's 0-100 disposition as a Skyrim relationship rank (-4..4)."""
    if disposition < 20:
        return -2
    if disposition < 40:
        return -1
    if disposition <= 60:
        return 0
    if disposition < 80:
        return 1
    return 2


# --------------------------------------------------------------------------
# Chargen-identity conditions -> menu-choice globals
# --------------------------------------------------------------------------
#: See: docs/commentary/tes5_import_conditions.md#chargen-identity-to-menu-globals
CHARGEN_CHOICE: dict = {}


def set_chargen_choice(mapping: dict, merge: bool = False):
    if not merge:
        CHARGEN_CHOICE.clear()
    CHARGEN_CHOICE.update(mapping)


def _chargen_choice_ctda(type_byte: int, data: bytes, func_idx: int,
                         param1: int) -> 'bytes | None':
    """The GetGlobalValue translation described at _CHARGEN_CHOICE."""
    glob_fid, index_map = CHARGEN_CHOICE[func_idx]
    idx = index_map.get(param1 & 0xFFFFFF)
    if idx is None:
        return None
    outcomes = bool_outcomes(type_byte, struct.unpack_from('<I', data, 4)[0])
    if outcomes is None:
        return None
    truth_passes, false_passes = outcomes
    choice = float(idx + 1)
    if truth_passes and false_passes:
        new_op, comp_val = 3, 0.0          # >= 0: always true, keeps OR groups
    elif truth_passes:
        new_op, comp_val = 0, choice       # == index+1
    elif false_passes:
        new_op, comp_val = 1, choice       # != index+1
    else:
        new_op, comp_val = 0, -1.0         # never true, faithfully
    new_type = (new_op << 5) | (type_byte & CTDA_OR)
    comp_raw = struct.unpack('<I', struct.pack('<f', comp_val))[0]
    return struct.pack('<B3xIHHIIII I',
                       new_type, comp_raw,
                       74, 0,              # GetGlobalValue
                       glob_fid, 0,
                       0, 0, 0xFFFFFFFF)


def is_speak_as_record(rec: dict) -> bool:
    """True when this INFO belongs to a speak-as topic (see the module note).

    Reads the INFO's own ParentDIAL, so the answer is a property of the record
    rather than of any NPC it happens to name.
    """
    if not _SPEAK_AS_TOPICS:
        return False
    raw = rec.get('ParentDIAL') or rec.get('DIAL') or ''
    try:
        return (int(raw, 16) & 0x00FFFFFF) in _SPEAK_AS_TOPICS
    except (TypeError, ValueError):
        return False


def _disposition_fields(type_byte: int, data: bytes) -> 'tuple | None':
    """(comp_raw, func_idx, param1, param2) for a GetDisposition condition.

    None drops a Use Global comparison, whose GLOB cannot be rescaled.
    See: docs/commentary/tes5_import_conditions.md#disposition-param
    """
    if type_byte & CTDA_USE_GLOBAL:
        return None
    rank = float(disposition_to_rank(struct.unpack_from('<f', data, 4)[0]))
    comp_raw = struct.unpack('<I', struct.pack('<f', rank))[0]
    return comp_raw, GET_RELATIONSHIP_RANK, _PLAYER_REF_FORMID, 0


def _convert_params(func_idx: int, param1: int, param2: int,
                    offset: int) -> 'tuple | None':
    """(param1, param2) with only FormID slots remapped, or None to drop.

    `func_idx` is the TES5 index.  Actor-value and race parameters are
    translated between the games' tables rather than remapped.
    See: docs/commentary/tes5_import_conditions.md#formid-params
    """
    fid_slots = CTDA_FORMID_PARAMS.get(func_idx, frozenset())
    if func_idx in _AV_PARAM_FUNCS:
        av = param1 if param1 < 0x80000000 else param1 - 0x100000000
        if av in _TES4_AV_ATTRIBUTES or av not in _TES4_AV_TO_TES5:
            return None
        return _TES4_AV_TO_TES5[av], 0
    if func_idx in _RACE_PARAM_FUNCS:
        param1 = _map_race_param(param1)
        if param1 is None:
            return None
    elif 1 in fid_slots:
        param1 = _remap_formid(param1, offset)
    if 2 in fid_slots:
        param2 = _remap_formid(param2, offset)
    return param1, param2


def _target_run_on(func_idx: int, run_on_target_ref: 'int | None',
                   drop_run_on_target: bool) -> 'tuple | None':
    """(run_on, reference) for a run-on-target condition, or None to drop it.

    A resolved listener retargets to Run On = Reference, except for identity
    functions; a script-driven topic with no resolvable listener drops.
    See: docs/commentary/tes5_import_conditions.md#run-on-target
    """
    identity = func_idx in _NO_TARGET_RETARGET_FUNCS
    if run_on_target_ref is not None and not identity:
        return 2, run_on_target_ref
    if drop_run_on_target or run_on_target_ref is not None:
        return None
    return 1, 0


def _ctda_head(raw: bytes, offset: int, in_speak_as_topic: bool):
    """The decoded fields of one source CTDA, a finished CTDA, or None to drop.

    Returns (type, comparison, TES5 function, param1, param2, run_on,
    reference) once the FO3/FNV, disposition, chargen-choice, speak-as and
    dropped-function cases are settled.
    """
    data = raw + b'\x00' * max(0, 24 - len(raw))
    type_byte = data[0]
    comp_raw, func_idx = struct.unpack_from('<IH', data, 4)
    param1, param2 = struct.unpack_from('<II', data, 12)
    run_on, reference, fallout = 0, 0, len(raw) >= FALLOUT_CTDA_SIZE
    if fallout:
        is_target, run_on, reference = fallout_run_on(
            raw, lambda fid: _remap_formid(fid, offset))
        type_byte |= CTDA_RUN_ON_TARGET if is_target else 0
        func_idx = fallout_function(func_idx)
        if func_idx is None:
            return None
    if func_idx == GET_DISPOSITION:
        fields = _disposition_fields(type_byte, data)
        if fields is None:
            return None
        comp_raw, func_idx, param1, param2 = fields
    if func_idx in CHARGEN_CHOICE:
        return _chargen_choice_ctda(type_byte, data, func_idx, param1)
    if in_speak_as_topic and not (type_byte & CTDA_RUN_ON_TARGET) and (
            func_idx in NON_ACTOR_SPEAKER_DROP):
        return None
    if func_idx in (_VM_VAR_FUNCS if fallout else _FUNC_DROP):
        return None
    if not fallout:
        func_idx = _FUNC_REMAP.get(func_idx, func_idx)
    return type_byte, comp_raw, func_idx, param1, param2, run_on, reference


def _run_on_fields(type_byte: int, func_idx: int, run_on: int, reference: int,
                   run_on_target_ref, drop_run_on_target: bool):
    """(type, run_on, reference) with RunOnTarget resolved, or None to drop.

    A bounty test the source ran on the player (its target) runs on the
    subject: Skyrim reads the player's bounty in the subject's crime faction.
    See: docs/commentary/tes5_import_conditions.md#run-on-target
    """
    if not type_byte & CTDA_RUN_ON_TARGET:
        return type_byte, run_on, reference
    type_byte &= ~CTDA_RUN_ON_TARGET
    if func_idx in _PLAYER_BOUNTY_FUNCS:
        return type_byte, 0, 0
    target = _target_run_on(func_idx, run_on_target_ref, drop_run_on_target)
    return None if target is None else (type_byte,) + target


def convert_ctda(raw: bytes, offset: 'int | None' = None,
                 run_on_target_ref: 'int | None' = None,
                 drop_run_on_target: bool = False,
                 in_speak_as_topic: bool = False) -> 'bytes | None':
    """Convert one TES4 (24-byte) or FO3/FNV (28-byte) CTDA to a 32-byte TES5 CTDA.

    Returns None if the function must be dropped (no faithful TES5 equivalent),
    so the caller can repair the OR chain.  `run_on_target_ref` retargets a
    run-on-target condition of a script-driven topic onto that listener;
    `drop_run_on_target` drops it instead; `in_speak_as_topic` drops
    subject-run actor-identity gates.
    See: docs/commentary/tes5_import_conditions.md#say-driven-topics
    """
    if offset is None:
        offset = get_formid_index_offset()
    head = _ctda_head(raw, offset, in_speak_as_topic)
    if not isinstance(head, tuple):
        return head
    type_byte, comp_raw, func_idx, param1, param2, run_on, reference = head
    if type_byte & CTDA_USE_GLOBAL:
        comp_raw = _remap_formid(comp_raw, offset)
    params = _convert_params(func_idx, param1, param2, offset)
    fields = _run_on_fields(type_byte, func_idx, run_on, reference,
                            run_on_target_ref, drop_run_on_target)
    if params is None or fields is None:
        return None
    param1, param2 = params
    type_byte, run_on, reference = fields

    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       run_on, reference, 0xFFFFFFFF)


def convert_ctda_list(rec: dict, offset: 'int | None' = None,
                      prefix: str = '') -> list:
    """Convert all of a record's TES4 conditions, repairing the OR chain.

    Reads [prefix]Condition[i].Raw (24-byte hex blobs) and returns a list of
    32-byte TES5 CTDAs. prefix selects nested condition lists (e.g.
    'Target[2].' for quest target conditions). Dropping a condition that
    participated in an OR group is safe — it's simply removed from the group —
    but the LAST surviving condition must not retain a dangling OR flag, so we
    clear it.
    """
    if offset is None:
        offset = get_formid_index_offset()
    out = []
    i = 0
    while True:
        raw_hex = rec.get(f'{prefix}Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex:
            continue
        try:
            ctda = convert_ctda(bytes.fromhex(raw_hex), offset)
        except (ValueError, struct.error):
            continue
        if ctda is not None:
            out.append(ctda)
    # Repair: a trailing OR flag with nothing after it is invalid.
    if out and (out[-1][0] & CTDA_OR):
        out[-1] = bytes([out[-1][0] & ~CTDA_OR]) + out[-1][1:]
    return out


def convert_ctda_list_with_strings(rec: dict, script_vars: dict = None,
                                   offset: 'int | None' = None,
                                   prefix: str = '',
                                   run_on_target_ref: 'int | None' = None,
                                   drop_run_on_target: bool = False) -> list:
    """Like convert_ctda_list, but returns [(ctda_bytes, cis2_or_None)].

    GetScriptVariable becomes GetVMScriptVariable + a CIS2 naming the Papyrus
    property; `script_vars` maps ref_fid -> {var_index: var_name}, and an
    unresolved variable reads a sentinel no script declares, so 0.
    `[prefix]Condition[i].RunOn=Player` retargets that one run-on-target
    condition onto PlayerRef, overriding `run_on_target_ref`.
    See: docs/commentary/tes4_export_morrowind.md#bark-conditions
    """
    if offset is None:
        offset = get_formid_index_offset()
    script_vars = script_vars or {}
    speak_as = is_speak_as_record(rec)
    out = []
    i = 0
    while True:
        raw_hex = rec.get(f'{prefix}Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
        except ValueError:
            continue

        func = struct.unpack_from('<H', raw + b'\0' * 24, 8)[0]
        ref = (_PLAYER_REF_FORMID if rec.get(f'{prefix}Condition[{i - 1}].RunOn')
               == 'Player' else run_on_target_ref)
        if func in _VM_VAR_FUNCS:
            pair = convert_script_var_ctda(
                raw, script_vars, offset, ref, drop_run_on_target,
                rec.get(f'{prefix}Condition[{i - 1}].Variable', ''))
            if pair is not None:
                out.append(pair)
            continue

        try:
            ctda = convert_ctda(raw, offset, run_on_target_ref=ref,
                                drop_run_on_target=drop_run_on_target,
                                in_speak_as_topic=speak_as)
        except (ValueError, struct.error):
            continue
        if ctda is not None:
            out.append((ctda, None))

    if out and (out[-1][0][0] & CTDA_OR):
        fixed = bytes([out[-1][0][0] & ~CTDA_OR]) + out[-1][0][1:]
        out[-1] = (fixed, out[-1][1])
    return sort_vm_conditions_last(expand_cell_families(out))


def sort_vm_conditions_last(pairs: list) -> list:
    """Stable-partition (CTDA, CIS2) pairs so VM-variable reads evaluate LAST.

    GetVMQuestVariable(629)/GetVMScriptVariable(630) are not ordinary
    conditions: each evaluation crosses from the main thread into the Papyrus
    VM (lock + script-object variable lookup by mangled name), where every
    engine-native condition is a plain field read.  The engine walks a
    topic's INFOs evaluating each one's conditions IN ORDER until the first
    failure, so a VM read placed before the cheap identity gates runs for
    every candidate INFO on every Say — CharGenMain carries 59 INFOs whose
    convCount VM read preceded its GetIsID, and all four escort speakers
    share one voice type, so nothing upstream filtered: every Say paid ~59
    VM round-trips on the main thread.  That is the visible hitch each time
    a converted NPC speaks.

    AND-joined conditions are order-independent (all must pass), so moving
    whole condition units is semantics-preserving.  The unit is the OR-GROUP:
    a run of conditions chained by the Or flag (bit 0) forms one boolean
    unit and must never be split or interleaved.  Groups keep their relative
    order within each class (stable), cheap classes first.
    """
    if len(pairs) < 2:
        return pairs
    groups = or_groups(pairs)

    def _has_vm_read(group):
        for ctda, _cis2 in group:
            if struct.unpack_from('<H', ctda, 8)[0] in (
                    GET_VM_SCRIPT_VARIABLE, GET_VM_QUEST_VARIABLE):
                return True
        return False

    cheap = [g for g in groups if not _has_vm_read(g)]
    vm = [g for g in groups if _has_vm_read(g)]
    if not cheap or not vm:
        return pairs
    return [p for g in cheap + vm for p in g]


def convert_script_var_ctda(raw: bytes, script_vars: dict, offset: int,
                             run_on_target_ref: 'int | None' = None,
                             drop_run_on_target: bool = False,
                             authored_name: str = ''):
    """GetScriptVariable(ref, varIdx) -> GetVMScriptVariable(ref, '::var_var');
    GetQuestVariable(quest, varIdx) -> GetVMQuestVariable(quest, '::var_var').

    `authored_name` is the variable name an export states outright, for a
    condition that names no reference to resolve an index against.
    """
    data = raw + b'\x00' * max(0, 24 - len(raw))
    type_byte = data[0]
    comp_raw = struct.unpack_from('<I', data, 4)[0]
    func = struct.unpack_from('<H', data, 8)[0]
    param1 = struct.unpack_from('<I', data, 12)[0]   # the ref / the quest
    param2 = struct.unpack_from('<I', data, 16)[0]   # script-local var index

    ref = _remap_formid(param1, offset)
    name = (authored_name
            or script_vars.get(param1 & 0x00FFFFFF, {}).get(param2))
    if name:
        cis2 = papyrus_var_name(name)
    else:
        # No such script variable on that ref/quest — the base has no script,
        # the script has no variable at that index, or the ref was deleted
        # (param1 = 0).  Oblivion's GetScriptVariable returns 0 in every one
        # of those cases, and Skyrim's GetVMScriptVariable returns 0 for a
        # name no attached script declares — so a NEVER-declared name
        # reproduces the TES4 value exactly, and the authored comparison and
        # Or-flag keep doing their job.  Dropping the condition instead
        # failed OPEN: SE08's five Xedilian victims force-greeted and fled
        # unconditionally, and 14 jailor packages ran with the player free.
        cis2 = _UNRESOLVED_VAR_SENTINEL

    if type_byte & CTDA_USE_GLOBAL:
        comp_raw = _remap_formid(comp_raw, offset)
    run_on = 0
    reference = 0
    if type_byte & CTDA_RUN_ON_TARGET:
        type_byte &= ~CTDA_RUN_ON_TARGET
        if run_on_target_ref is not None:
            run_on = 2
            reference = run_on_target_ref
        elif drop_run_on_target:
            return None
        else:
            run_on = 1

    ctda = struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       _VM_VAR_FUNCS[func], 0,
                       ref, 0,
                       run_on, reference, 0xFFFFFFFF)
    return ctda, cis2


# --- Builders for the Skyrim-required injected conditions ----------------------

def build_ctda(func_idx: int, param1: int = 0, param2: int = 0,
               comp_value: float = 1.0, operator: int = 0x00,
               is_or: bool = False) -> bytes:
    """Build a 32-byte TES5 CTDA. operator is the high-nibble comparison
    (0x00 ==, 0x60 >=, etc.); is_or sets the OR flag for chaining."""
    type_byte = operator | (CTDA_OR if is_or else 0)
    comp_raw = struct.unpack('<I', struct.pack('<f', comp_value))[0]
    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       0, 0, 0xFFFFFFFF)


def build_or_chain(func_idx: int, param1_fids: list, comp_value: float = 1.0,
                   operator: int = 0x00) -> bytes:
    """Build an OR-chain of func(param)==value CTDAs (OR on all but the last).

    Returns packed CTDA subrecords ready to concatenate. Empty list -> b''.
    """
    from ..record_types.common import pack_subrecord
    fids = sorted(set(param1_fids))
    out = b''
    for idx, fid in enumerate(fids):
        is_last = (idx == len(fids) - 1)
        out += pack_subrecord(
            'CTDA', build_ctda(func_idx, param1=fid, comp_value=comp_value,
                               operator=operator, is_or=not is_last))
    return out


def read_getisid_fids(rec: dict, offset: 'int | None' = None,
                      positive_only: bool = True) -> set:
    """Collect remapped NPC FormIDs from GetIsID conditions on a record.

    positive_only restricts to GetIsID(X) == 1.0 (the "is this NPC" form),
    ignoring negated/comparison forms.
    """
    if offset is None:
        offset = get_formid_index_offset()
    fids = set()
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] != FUNC_GET_IS_ID:
                continue
            if positive_only:
                operator = raw[0] & 0xF0
                comp = struct.unpack_from('<f', raw, 4)[0]
                if operator != 0x00 or comp != 1.0:
                    continue
            fids.add(_remap_formid(struct.unpack_from('<I', raw, 12)[0], offset))
        except (ValueError, struct.error):
            continue
    return fids


def has_positive_getisid(rec: dict) -> bool:
    """True if the record has at least one GetIsID(X) == 1.0 condition."""
    return bool(read_getisid_fids(rec, positive_only=True))


def read_func_param_fids(rec: dict, func_idx: int,
                         offset: 'int | None' = None) -> set:
    """Remapped param1 FormIDs of every `func(X) == 1.0` condition on a record.

    Used to harvest the "who is this line for" gates a sibling INFO carries
    (e.g. GetInFaction(Beggars)) so a conditionless sibling can inherit them.
    """
    if offset is None:
        offset = get_formid_index_offset()
    fids = set()
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] != func_idx:
                continue
            if (raw[0] & 0xF0) != 0x00 or struct.unpack_from('<f', raw, 4)[0] != 1.0:
                continue
            fid = struct.unpack_from('<I', raw, 12)[0]
            if fid:
                fids.add(_remap_formid(fid, offset))
        except (ValueError, struct.error):
            continue
    return fids


def has_any_conditions(rec: dict) -> bool:
    """True if the record carries at least one TES4 condition."""
    return bool(rec.get('Condition[0].Raw'))


# TES4 condition functions that already answer "WHO is this line for":
# GetInCell(67), GetIsClass(68), GetIsRace(69), GetInFaction(71), GetIsID(72),
# GetFactionRank(73). GetIsSex(70) is deliberately excluded — male/female alone
# is not an audience restriction.
_AUDIENCE_FUNCS = frozenset({67, 68, 69, 71, 72, 73})

# The subset of _AUDIENCE_FUNCS whose parameter is a form THIS PLUGIN owns, so
# the condition cannot pass for an actor belonging to a different converted
# plugin: GetInFaction(71), GetIsID(72), GetFactionRank(73), GetIsClass(68).
#
# CLAS records ARE converted into the output plugin (192 in Oblivion, 30 in
# Nehrim, every one at the plugin's own load-order index), and func 68 takes
# the ordinary load-order remap, so its param stays plugin-owned and a foreign
# actor can never match it.
#
# The other two do NOT scope across plugins, even though they scope perfectly
# well inside one:
#   * GetIsRace(69)  — _map_race_param rewrites the param to a VANILLA SKYRIM
#     race (0x000131F0 Imperial, ...), which every converted plugin's NPCs
#     share.  In Oblivion race WAS the plugin boundary because only Oblivion
#     existed; after conversion "GenericImperial" means every Imperial in the
#     whole load order, Nehrim's included.  RACE is the one audience function
#     with a vanilla-remap step, which is exactly why it stops scoping.
#   * GetInCell(67)  — a cell name, not an owned form reference.
_PLUGIN_SCOPED_AUDIENCE_FUNCS = frozenset({68, 71, 72, 73})


def _condition_tests(rec: dict):
    """Yield (func_idx, operator, comp_value, run_on_target) per TES4 condition."""
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            yield (struct.unpack_from('<H', raw, 8)[0],   # function
                   raw[0] & 0xF0,                        # comparison operator
                   struct.unpack_from('<f', raw, 4)[0],  # compare value
                   bool(raw[0] & CTDA_RUN_ON_TARGET))
        except (ValueError, struct.error):
            continue


def _asserts_membership(operator: int, comp_value: float) -> bool:
    """True if this comparison ASSERTS membership rather than denying it.

    Same rule as read_getisid_fids(positive_only=True): the "is this NPC"
    form is exactly `== 1.0`. Everything else — `== 0` / `!= 1` ("anyone
    EXCEPT this one") and the ordering comparisons — leaves the audience open
    and cannot scope a line to this plugin's actors.
    """
    return operator == 0x00 and comp_value == 1.0


def needs_origin_gate(rec: dict) -> bool:
    """True if this INFO can be reached by an actor from a DIFFERENT plugin.

    A line is safely scoped only by a condition that POSITIVELY names a form
    this plugin owns AND evaluates against the SPEAKER. Three traps, each
    measured against the real Oblivion/Nehrim exports:

      * Race/cell gates look like an audience but don't resolve to a form this
        plugin uniquely owns — GetIsRace's param is rewritten to a vanilla
        Skyrim race every converted plugin shares. This is the measured cause
        of Oblivion guard/crime/directions lines playing on Nehrim NPCs.
      * A NEGATIVE membership test is an exclusion, not an audience. Oblivion's
        Rumors channel (INFOGENERAL, 1854 lines) is built almost entirely from
        `GetIsID(SomeNPC) == 0` — "any speaker other than X". Counting that as
        pinned left 395 rumour lines (plus 77 with no conditions at all)
        reaching Nehrim NPCs — the Oblivion Rumors topic seen in-game on a
        Nehrim NPC.
      * A RunOn=Target test is about the LISTENER, not the speaker.
        `GetIsID(PlayerRef)[Target] == 1` means "the addressee is the player",
        which every conversation satisfies and which says nothing about who is
        talking. Counting it as a pin left 55 greeting/rumour/guard lines open
        to any actor in the load order.
    """
    return not any(f in _PLUGIN_SCOPED_AUDIENCE_FUNCS
                   and _asserts_membership(op, cv)
                   and not run_on_target
                   for f, op, cv, run_on_target in _condition_tests(rec))


# Condition functions that express a WORLD-STATE precondition for a topic
# rather than an audience: quest stage/running/completed and the player's
# standing. A conditionless INFO whose every conditioned sibling shares one of
# these is not "always valid" — the shared gate IS the topic's precondition.
_STATE_FUNCS = frozenset({
    56,   # GetQuestRunning
    58,   # GetStage
    59,   # GetStageDone
    71,   # GetInFaction      (only when RunOn=Target, i.e. about the PLAYER)
    73,   # GetFactionRank    (ditto)
    99,   # GetQuestCompleted
})


def shared_state_conditions(recs: list) -> list:
    """Raw CTDA blobs that EVERY conditioned record in `recs` carries.

    Oblivion frequently leaves one INFO of a topic conditionless and lets its
    siblings' conditions scope the whole topic — the topic itself being
    AddTopic-gated meant the loose line could never show early. Skyrim has no
    such implicit scoping, so a conditionless line becomes permanently valid.

    The Fighters Guild join topic is the case that proves it: three of its four
    lines carry `GetInFaction(FightersGuild)[Target] == 0` ("player is not a
    member") and the fourth carries nothing, so after joining, that fourth line
    kept the topic alive and Azzan went on offering "Join the Fighters Guild"
    to a member forever.

    Returns the intersection of the conditioned records' state conditions, as
    raw hex blobs, preserving the order of the first record that has them.
    """
    per_rec = []
    for rec in recs:
        if not has_any_conditions(rec):
            continue
        blobs = []
        i = 0
        while True:
            raw_hex = rec.get(f'Condition[{i}].Raw')
            if raw_hex is None:
                break
            i += 1
            if not raw_hex or len(raw_hex) < 24:
                continue
            try:
                raw = bytes.fromhex(raw_hex)
                func = struct.unpack_from('<H', raw, 8)[0]
            except (ValueError, struct.error):
                continue
            if func not in _STATE_FUNCS:
                continue
            # A faction check only describes world state when it runs on the
            # TARGET (the player). On the subject it is an audience test.
            if func in (71, 73) and not (raw[0] & 0x02):
                continue
            # An OR-flagged condition belongs to a group; lifting one member
            # out of its chain would change the meaning, so skip the whole run.
            if raw[0] & 0x01:
                continue
            blobs.append(raw_hex)
        if not blobs:
            return []          # a sibling with no state gate ⇒ no unanimity
        per_rec.append(blobs)
    if len(per_rec) < 2:
        return []
    common = set(per_rec[0])
    for blobs in per_rec[1:]:
        common &= set(blobs)
    if not common:
        return []
    return [b for b in per_rec[0] if b in common]


def has_audience_condition(rec: dict) -> bool:
    """True if the record already restricts WHICH actors the line reaches.

    An INFO gated on a cell, class, race, faction or actor has stated its own
    audience — injecting a GetIsID OR-chain harvested from its siblings on top
    would narrow it to a handful of NPCs (e.g. AnvilTopic, gated GetInCell
    (Anvil), would stop reaching most Anvil NPCs).
    """
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] in _AUDIENCE_FUNCS:
                return True
        except (ValueError, struct.error):
            continue
    return False
