// GENERATED by tools/generators/gen_morrowind_menu_swf.py.
// Edit the generator, not this file.

#pragma once

namespace mwruntime::layout {

constexpr int kCaptionX = 350;
constexpr int kCaptionY = 207;
constexpr int kCaptionW = 580;
constexpr int kCaptionH = 20;
constexpr int kHistoryX = 369;
constexpr int kHistoryY = 246;
constexpr int kHistoryW = 350;
constexpr int kHistoryH = 370;
constexpr int kHistoryScrollX = 724;
constexpr int kHistoryScrollY = 244;
constexpr int kHistoryScrollW = 14;
constexpr int kHistoryScrollH = 371;
constexpr int kTopicsX = 755;
constexpr int kTopicsY = 265;
constexpr int kTopicsW = 160;
constexpr int kTopicsH = 322;
constexpr int kTopicRowX = 757;
constexpr int kTopicRowY = 267;
constexpr int kTopicRowW = 138;
constexpr int kTopicRowH = 18;
constexpr int kTopicScrollX = 901;
constexpr int kTopicScrollY = 265;
constexpr int kTopicScrollW = 14;
constexpr int kTopicScrollH = 322;
constexpr int kByeX = 752;
constexpr int kByeY = 597;
constexpr int kByeW = 166;
constexpr int kByeH = 23;

constexpr int kCaptionPad = 8;
constexpr int kScrollEnd = 15;
constexpr int kScrollTrackTop = 18;
constexpr int kScrollTrackBottom = 17;
constexpr int kThumbH = 30;
constexpr int kTopicFields = 14;
constexpr int kRowHeight = 18;
constexpr int kRowPad = 3;
constexpr int kRowTextShift = -1;
constexpr int kSeparatorHeight = 18;
constexpr int kFontPx = 16;
constexpr int kTextGutter = 2;

constexpr unsigned kColorNormal = 0xCAA560;
constexpr unsigned kColorNormalOver = 0xDFC99F;
constexpr unsigned kColorNormalPressed = 0xF3EDDD;
constexpr unsigned kColorLink = 0x707ECF;
constexpr unsigned kColorLinkOver = 0x8F9BDA;
constexpr unsigned kColorLinkPressed = 0xAFB8E4;
constexpr unsigned kColorAnswer = 0x96321E;
constexpr unsigned kColorAnswerOver = 0xDFC99F;
constexpr unsigned kColorAnswerPressed = 0xF3EDDD;
constexpr unsigned kColorHeader = 0xDFC99F;
constexpr unsigned kColorNotify = 0xDFC99F;
constexpr unsigned kColorDisabled = 0xB3A887;

constexpr const char* kFieldName = "_root.Name";
constexpr const char* kFieldHistory = "_root.History";
constexpr const char* kFieldDisposition = "_root.Disposition";
constexpr const char* kFieldBye = "_root.Bye";
constexpr const char* kFieldTopic = "_root.Topic";
constexpr const char* kSpriteCover = "_root.Cover";
constexpr const char* kSpriteCapLeft = "_root.CapLeft";
constexpr const char* kSpriteCapRight = "_root.CapRight";
constexpr const char* kSpriteHistoryScroll = "_root.HistoryScroll";
constexpr const char* kSpriteHistoryThumb = "_root.HistoryThumb";
constexpr const char* kSpriteTopicScroll = "_root.TopicScroll";
constexpr const char* kSpriteTopicThumb = "_root.TopicThumb";
constexpr const char* kSpriteTopicLine = "_root.TopicLine";
constexpr const char* kGoodbye = "Goodbye";
constexpr const char* kPersuasion = "Persuasion";

constexpr int kFontEm = 20480;
constexpr int kFontAscent = 16980;
constexpr int kFontDescent = 3500;
constexpr int kFontLeading = 1840;
constexpr int kFirstCode = 32;
constexpr int kAdvance[] = {8700, 4560, 7580, 11640, 11180, 15780, 15060, 3680, 8040, 8040, 10040, 11680, 5440, 7200, 4880, 6980, 10200, 10200, 10200, 10200, 10200, 10200, 10200, 10200, 10200, 10200, 5080, 5640, 12480, 12220, 12480, 8120, 17200, 14920, 14740, 13940, 14720, 14360, 11100, 15880, 15700, 10300, 9220, 14280, 14660, 18080, 19200, 17380, 15660, 17380, 17340, 13720, 14560, 15740, 14380, 23620, 13520, 12920, 13520, 6820, 7560, 6820, 9600, 10980, 4160, 9860, 10660, 8680, 11180, 8740, 6860, 10940, 11800, 6800, 6640, 10940, 5580, 16540, 11420, 10340, 10680, 12020, 9400, 8420, 8800, 10300, 10520, 17300, 11220, 10580, 10600, 7540, 5960, 8140, 11000};

}  // namespace mwruntime::layout
