"""Generate tes5_import/generated/morrowind_quest_names.json from the UESP dump.

A TES3 journal's display name is an INFO flagged QSTN, which Tribunal
introduced: Morrowind.esm carries none, and some later quests none either, so
their QUST would otherwise show the raw journal id. Every UESP quest page
names its journal ids in the `{{Quest Header}}` infobox's `|ID=` field and
titles itself with the quest's player-facing name; this pairs the two.

    python tools/generators/gen_morrowind_quest_names.py [--dump F] [--out F]

See: docs/commentary/morrowind_runtime.md#quest-names
"""
import argparse
import json
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.path.insert(0, ROOT)
from tools.misc.uesp_lookup import DUMP, pages

OUT = os.path.join(ROOT, 'tes5_import', 'generated', 'morrowind_quest_names.json')

#: UESP namespaces whose quests are TES3 journals: the game, its expansions, TES3 mods.
NAMESPACES = ('Morrowind', 'Tribunal', 'Bloodmoon', 'Morrowind Mod',
              'Tamriel Rebuilt', 'Project Tamriel')

_QUEST_BOX = re.compile(r'\{\{\s*Quest Header', re.I)
_ID_FIELD = re.compile(r'^\s*\|\s*ID\s*=(.*)$', re.I | re.M)
_MARKUP = re.compile(r"''+|\[\[|\]\]|<[^>]*>")
_SEPARATOR = re.compile(r'[,();]|\s+(?:and|or|-)\s+', re.I)
_LEAD_WORD = re.compile(r'^(also|see)\b\s*:?\s*', re.I)
_JOURNAL_ID = re.compile(r'[A-Za-z0-9_][A-Za-z0-9_\- ]*')
_DISAMBIGUATOR = re.compile(r'\s*\([^)]*\)$')

#: Placeholder words an `|ID=` field uses to say the quest has no journal.
_NO_ID = frozenset(('none', 'n/a', 'na', 'unknown'))


def journal_ids(field: str) -> list:
    """The journal ids an `|ID=` value lists, primary first.

    Handles the dump's free-form spellings: `A, B`, `A (also: B, C)`,
    `A ''(B)''`, `A, B, and C`, `A or B`, `A - note`. A wildcard or
    punctuated chunk is skipped.
    """
    ids = []
    for chunk in _SEPARATOR.split(_MARKUP.sub('', field)):
        chunk = _LEAD_WORD.sub('', chunk.strip()).strip()
        if (chunk and chunk.lower() not in _NO_ID
                and _JOURNAL_ID.fullmatch(chunk)):
            ids.append(chunk)
    return ids


def display_name(title: str) -> str:
    """A page title minus its namespace and trailing disambiguator."""
    return _DISAMBIGUATOR.sub('', title.split(':', 1)[1]).strip()


def collect(page_iter) -> tuple:
    """`({lower id: name}, conflicts)` over `(title, text)` pages.

    An id a page lists FIRST beats the same id listed later on another page,
    so a quest's own page wins over one that mentions it in an `also`.
    Ties keep the first page in dump order.
    """
    best = {}
    conflicts = 0
    for title, text in page_iter:
        namespace = title.split(':', 1)[0]
        if namespace not in NAMESPACES or not _QUEST_BOX.search(text or ''):
            continue
        name = display_name(title)
        listed = [i for field in _ID_FIELD.findall(text)
                  for i in journal_ids(field)]
        for rank, journal in enumerate(listed):
            key = journal.lower()
            held = best.get(key)
            if held is None or rank < held[0]:
                conflicts += held is not None and held[1] != name
                best[key] = (rank, name)
    return {key: name for key, (_rank, name) in sorted(best.items())}, conflicts


def main():
    """Write the table and print its size."""
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--dump', default=DUMP)
    ap.add_argument('--out', default=OUT)
    args = ap.parse_args()
    names, conflicts = collect(pages(args.dump))
    table = {
        '__doc__': ('TES3 journal id (lowercase) -> the quest name UESP titles '
                    'its page with. The fallback FULL for a journal that '
                    'authors no QSTN name. Generated by tools/generators/'
                    'gen_morrowind_quest_names.py from '
                    f'{os.path.basename(args.dump)}; UESP text is CC BY-SA 2.5.'),
        '__count__': len(names),
        'entries': names,
    }
    with open(args.out, 'w', encoding='utf-8', newline='\n') as handle:
        json.dump(table, handle, ensure_ascii=False, indent=1)
        handle.write('\n')
    print(f'{len(names)} journal ids named ({conflicts} re-assigned by rank) '
          f'-> {args.out}')


if __name__ == '__main__':
    main()
