"""Generate tes4_export/morrowind_mgef_names.py from OpenMW's effect tables.

Morrowind's magic effects are an engine-fixed set addressed by an integer
index, not per-effect records with their own IDs: a plugin may override an
effect's cost or art, but never invent one.  The canonical index -> name table
therefore lives in the engine, and OpenMW carries it twice -- once as the GMST
name array and once as the index -> RefId array.  Both are read here and
required to agree, because a table that silently disagreed with itself would
mis-key every converted spell.

Names only.  Which Skyrim archetype an effect becomes is judgement and lives in
tes4_export/record_types/morrowind_magic.py.

    python tools/generators/gen_morrowind_mgef_table.py

See: docs/commentary/tes4_export_morrowind.md#tes4-vocabulary
"""
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
SRC = os.path.join(ROOT, 'external', 'openmw', 'components', 'esm3', 'loadmgef.cpp')
HDR = os.path.join(ROOT, 'external', 'openmw', 'components', 'esm3', 'loadmgef.hpp')
OUT = os.path.join(ROOT, 'tes4_export', 'morrowind_mgef_names.py')

#: TES3 allocates this many effect indices; OpenMW's `MagicEffect::Length`.
EFFECT_COUNT = 143


def _array_block(text: str, marker: str) -> str:
    """The text of the array literal introduced by `marker`."""
    start = text.find(marker)
    if start < 0:
        raise SystemExit(f'{marker} not found in {SRC}')
    end = text.find('};', start)
    if end < 0:
        raise SystemExit(f'{marker} array is unterminated in {SRC}')
    return text[start:end]


def gmst_names(text: str) -> list:
    """The index-ordered effect names, from the `sEffect*` GMST id array."""
    return re.findall(r'"sEffect(\w+)"', _array_block(text, 'sGmstEffectIds'))


def refid_names(text: str) -> list:
    """The index-ordered effect names, from the index -> RefId array."""
    block = _array_block(text, 'sMagicEffectIds')
    return re.findall(r'MagicEffect::(\w+)', block)


def declared_length() -> int:
    """`MagicEffect::Length` as the header declares it."""
    with open(HDR, encoding='utf-8', errors='replace') as handle:
        found = re.search(r'Length\s*=\s*(\d+)', handle.read())
    if not found:
        raise SystemExit(f'MagicEffect::Length not found in {HDR}')
    return int(found.group(1))


def check(gmst: list, refids: list) -> None:
    """Fail unless both arrays span the whole index range the header declares.

    LENGTH is the invariant, not spelling: the two arrays name 13 of the same
    effects differently (index 19 `DrainSpellpoints` vs `DrainMagicka`, 132
    `Corpus` vs `Corprus`, 138-140 the Bloodmoon summons under generic vs real
    names), which is upstream style, not disagreement about what lives where.
    A LENGTH change is the thing that would renumber every converted spell.
    """
    length = declared_length()
    for name, table in (('sGmstEffectIds', gmst), ('sMagicEffectIds', refids)):
        if len(table) != length:
            raise SystemExit(
                f'{name} has {len(table)} entries, MagicEffect::Length is {length}')
    if length != EFFECT_COUNT:
        raise SystemExit(
            f'MagicEffect::Length is {length}, this generator expects {EFFECT_COUNT}')


def render(names: list) -> str:
    """The committed module's text."""
    lines = [
        '"""Morrowind magic effect index -> canonical name.',
        '',
        'GENERATED by tools/generators/gen_morrowind_mgef_table.py -- do not edit.',
        '',
        'TES3 addresses magic effects by index into an engine-fixed table, so this',
        'is the vocabulary every converted SPEL, ENCH, ALCH and INGR names.',
        '"""',
        '',
        '#: Index -> effect name, in the order TES3 allocates them.',
        'MW_EFFECT_NAMES = (',
    ]
    for index, name in enumerate(names):
        lines.append(f"    '{name}',".ljust(36) + f'# {index}')
    lines.append(')')
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    """Write the committed name table; the process exit status."""
    with open(SRC, encoding='utf-8', errors='replace') as handle:
        text = handle.read()
    gmst = gmst_names(text)
    refids = refid_names(text)
    check(gmst, refids)
    with open(OUT, 'w', encoding='utf-8') as handle:
        handle.write(render(gmst))
    print(f'wrote {len(gmst)} effect names to {OUT}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
