"""CTDA condition-function parameter types (GENERATED — do not edit).

Generated by tools/gen_ctda_param_types.py from C:/Users/Bryant/Documents/Code/TESConversion/references/xEdit/Core/wbDefinitionsTES5.pas.

Maps a condition function index to the set of parameter slots (1, 2)
that hold a FormID. A slot NOT listed here is a plain integer, enum, or
float and must never be load-order remapped — the engine uses several of
them as raw array indices (ptActorValue, ptAxis, ptQuestStage, ...), so a
remapped value is an out-of-bounds read, not merely a dangling reference.
"""

# {function index: frozenset of 1-based param slots holding a FormID}
CTDA_FORMID_PARAMS = {
    1: frozenset({1}),  # GetDistance(ptReference)
    27: frozenset({1}),  # GetLineOfSight(ptReference)
    32: frozenset({1}),  # GetInSameCell(ptReference)
    42: frozenset({1}),  # SameFaction(ptActor)
    43: frozenset({1}),  # SameRace(ptActor)
    44: frozenset({1}),  # SameSex(ptActor)
    45: frozenset({1}),  # GetDetected(ptActor)
    47: frozenset({1}),  # GetItemCount(ptInventoryObject)
    53: frozenset({1}),  # GetScriptVariable(ptReference)
    56: frozenset({1}),  # GetQuestRunning(ptQuest)
    58: frozenset({1}),  # GetStage(ptQuest)
    59: frozenset({1}),  # GetStageDone(ptQuest)
    60: frozenset({1, 2}),  # GetFactionRankDifference(ptFaction, ptActor)
    66: frozenset({1}),  # GetShouldAttack(ptActor)
    67: frozenset({1}),  # GetInCell(ptCell)
    68: frozenset({1}),  # GetIsClass(ptClass)
    69: frozenset({1}),  # GetIsRace(ptRace)
    71: frozenset({1}),  # GetInFaction(ptFaction)
    72: frozenset({1}),  # GetIsID(ptBaseObject)
    73: frozenset({1}),  # GetFactionRank(ptFaction)
    74: frozenset({1}),  # GetGlobalValue(ptGlobal)
    79: frozenset({1}),  # GetQuestVariable(ptQuest)
    84: frozenset({1}),  # GetDeadCount(ptActorBase)
    99: frozenset({1}),  # GetHeadingAngle(ptReference)
    117: frozenset({1}),  # IsPlayerInRegion(ptRegion)
    122: frozenset({1}),  # GetCrime(ptActor)
    129: frozenset({1}),  # GetPCIsClass(ptClass)
    130: frozenset({1}),  # GetPCIsRace(ptRace)
    132: frozenset({1}),  # GetPCInFaction(ptFaction)
    136: frozenset({1}),  # GetIsReference(ptReference)
    149: frozenset({1}),  # GetIsCurrentWeather(ptWeather)
    152: frozenset({1}),  # GetIsCrimeFaction(ptFaction)
    161: frozenset({1}),  # GetIsCurrentPackage(ptPackage)
    162: frozenset({1}),  # IsCurrentFurnitureRef(ptReference)
    163: frozenset({1}),  # IsCurrentFurnitureObj(ptFurniture)
    172: frozenset({1}),  # GetTalkedToPCParam(ptActor)
    180: frozenset({1, 2}),  # HasSameEditorLocAsRef(ptReference, ptKeyword)
    181: frozenset({2}),  # HasSameEditorLocAsRefAlias(ptKeyword)
    182: frozenset({1}),  # GetEquipped(ptInventoryObject)
    193: frozenset({1}),  # GetPCExpelled(ptFaction)
    195: frozenset({1}),  # GetPCFactionMurder(ptFaction)
    197: frozenset({1}),  # GetPCEnemyofFaction(ptFaction)
    199: frozenset({1}),  # GetPCFactionAttack(ptFaction)
    214: frozenset({1}),  # HasMagicEffect(ptMagicEffect)
    223: frozenset({1}),  # IsSpellTarget(ptEffectItem)
    228: frozenset({1}),  # GetIsClassDefault(ptClass)
    230: frozenset({1, 2}),  # GetInCellParam(ptCell, ptReference)
    246: frozenset({1}),  # GetIsUsedItem(ptBaseObject)
    248: frozenset({1}),  # IsScenePlaying(ptScene)
    250: frozenset({1}),  # GetLocationCleared(ptLocation)
    258: frozenset({1, 2}),  # HasAssociationType(ptActor, ptAssociationType)
    259: frozenset({1}),  # HasFamilyRelationship(ptActor)
    261: frozenset({1}),  # HasParentRelationship(ptActor)
    262: frozenset({1}),  # IsWarningAbout(ptFormList)
    264: frozenset({1}),  # HasSpell(ptEffectItem)
    278: frozenset({1}),  # IsOwner(ptOwner)
    280: frozenset({1, 2}),  # IsCellOwner(ptCell, ptOwner)
    359: frozenset({1}),  # GetInCurrentLoc(ptLocation)
    362: frozenset({1}),  # HasLinkedRef(ptKeyword)
    366: frozenset({1}),  # GetStolenItemValueNoCrime(ptFaction)
    370: frozenset({1}),  # IsTalkingActivatorActor(ptActor)
    372: frozenset({1}),  # IsInList(ptFormList)
    373: frozenset({1}),  # GetStolenItemValue(ptFaction)
    375: frozenset({1}),  # GetCrimeGoldViolent(ptFactionNull)
    376: frozenset({1}),  # GetCrimeGoldNonviolent(ptFactionNull)
    378: frozenset({1}),  # HasShout(ptShout)
    398: frozenset({1}),  # IsWeaponInList(ptFormList)
    403: frozenset({1}),  # GetRelationshipRank(ptReference)
    408: frozenset({1}),  # IsKiller(ptActor)
    409: frozenset({1}),  # IsKillerObject(ptFormList)
    410: frozenset({1, 2}),  # GetFactionCombatReaction(ptFaction, ptFaction)
    414: frozenset({1}),  # Exists(ptReference)
    426: frozenset({1}),  # GetIsVoiceType(ptVoiceType)
    444: frozenset({1}),  # GetInCurrentLocFormList(ptFormList)
    445: frozenset({1}),  # GetInZone(ptEncounterZone)
    448: frozenset({1}),  # HasPerk(ptPerk)
    449: frozenset({1}),  # GetFactionRelation(ptActor)
    450: frozenset({1}),  # IsLastIdlePlayed(ptIdleForm)
    459: frozenset({1}),  # GetCrimeGold(ptFactionNull)
    463: frozenset({1}),  # IsPlayerGrabbedRef(ptReference)
    465: frozenset({1}),  # GetKeywordItemCount(ptKeyword)
    477: frozenset({1}),  # GetThreatRatio(ptActor)
    493: frozenset({1}),  # PlayerKnows(ptKnowable)
    501: frozenset({1}),  # EPAlchemyEffectHasKeyword(ptKeyword)
    513: frozenset({1}),  # IsCombatTarget(ptActor)
    515: frozenset({1}),  # GetVATSRightAreaFree(ptReference)
    516: frozenset({1}),  # GetVATSLeftAreaFree(ptReference)
    517: frozenset({1}),  # GetVATSBackAreaFree(ptReference)
    518: frozenset({1}),  # GetVATSFrontAreaFree(ptReference)
    522: frozenset({1}),  # GetVATSRightTargetVisible(ptReference)
    523: frozenset({1}),  # GetVATSLeftTargetVisible(ptReference)
    524: frozenset({1}),  # GetVATSBackTargetVisible(ptReference)
    525: frozenset({1}),  # GetVATSFrontTargetVisible(ptReference)
    533: frozenset({1}),  # GetInfamy(ptFactionNull)
    534: frozenset({1}),  # GetInfamyViolent(ptFactionNull)
    535: frozenset({1}),  # GetInfamyNonViolent(ptFactionNull)
    543: frozenset({1}),  # GetQuestCompleted(ptQuest)
    550: frozenset({1}),  # IsSceneActionComplete(ptScene)
    552: frozenset({1}),  # GetSpellUsageNum(ptEffectItem)
    560: frozenset({1}),  # HasKeyword(ptKeyword)
    561: frozenset({1}),  # HasRefType(ptLocationRefType)
    562: frozenset({1}),  # LocationHasKeyword(ptKeyword)
    563: frozenset({1}),  # LocationHasRefType(ptLocationRefType)
    565: frozenset({1}),  # GetIsEditorLocation(ptLocation)
    576: frozenset({2}),  # GetEventData(ptEventData)
    577: frozenset({1, 2}),  # IsCloserToAThanB(ptReference, ptReference)
    579: frozenset({1}),  # GetEquippedShout(ptShout)
    584: frozenset({1}),  # GetRelativeAngle(ptReference)
    591: frozenset({1, 2}),  # GetRefTypeDeadCount(ptLocation, ptLocationRefType)
    592: frozenset({1, 2}),  # GetRefTypeAliveCount(ptLocation, ptLocationRefType)
    595: frozenset({1}),  # IsCurrentSpell(ptEffectItem)
    596: frozenset({2}),  # SpellHasKeyword(ptKeyword)
    600: frozenset({2}),  # GetLocAliasRefTypeDeadCount(ptLocationRefType)
    601: frozenset({2}),  # GetLocAliasRefTypeAliveCount(ptLocationRefType)
    603: frozenset({1, 2}),  # IsInSameCurrentLocAsRef(ptReference, ptKeyword)
    604: frozenset({2}),  # IsInSameCurrentLocAsRefAlias(ptKeyword)
    605: frozenset({2}),  # LocAliasIsLocation(ptLocation)
    606: frozenset({1, 2}),  # GetKeywordDataForLocation(ptLocation, ptKeyword)
    608: frozenset({2}),  # GetKeywordDataForAlias(ptKeyword)
    610: frozenset({2}),  # LocAliasHasKeyword(ptKeyword)
    617: frozenset({1}),  # HasAssociationTypeAny(ptAssociationType)
    624: frozenset({1}),  # GetInContainer(ptReference)
    625: frozenset({1}),  # IsLocationLoaded(ptLocation)
    629: frozenset({1}),  # GetVMQuestVariable(ptQuest)
    630: frozenset({1}),  # GetVMScriptVariable(ptReference)
    639: frozenset({1}),  # GetWithinDistance(ptReference)
    650: frozenset({1, 2}),  # IsLinkedTo(ptReference, ptKeyword)
    651: frozenset({1}),  # GetKeywordDataForCurrentLocation(ptKeyword)
    652: frozenset({1}),  # GetInSharedCrimeFaction(ptReference)
    660: frozenset({1}),  # EPTemperingItemHasKeyword(ptKeyword)
    678: frozenset({1}),  # ShouldAttackKill(ptActor)
    682: frozenset({1}),  # WornHasKeyword(ptKeyword)
    691: frozenset({1}),  # EPModSkillUsage_AdvanceObjectHasKeyword(ptKeyword)
    693: frozenset({1}),  # EPMagic_SpellHasKeyword(ptKeyword)
    697: frozenset({1}),  # IsAttackType(ptKeyword)
    699: frozenset({1}),  # HasMagicEffectKeyword(ptKeyword)
    705: frozenset({1}),  # GetShouldHelp(ptActor)
    707: frozenset({1}),  # GetCombatTargetHasKeyword(ptKeyword)
    713: frozenset({1}),  # SpellHasCastingPerk(ptPerk)
    719: frozenset({1}),  # IsHostileToActor(ptActor)
    720: frozenset({1}),  # GetTargetHeight(ptReference)
    722: frozenset({1}),  # WornApparelHasKeywordCount(ptKeyword)
}

# Every function index xEdit defines, for "is this real" checks.
CTDA_KNOWN_FUNCTIONS = frozenset({
    0, 1, 5, 6, 8, 10, 11, 12, 14, 18, 24, 25,
    26, 27, 32, 35, 36, 39, 41, 42, 43, 44, 45, 46,
    47, 48, 49, 50, 53, 56, 58, 59, 60, 61, 62, 63,
    64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75,
    77, 79, 80, 81, 84, 91, 98, 99, 101, 102, 103, 106,
    107, 108, 109, 110, 111, 112, 116, 117, 118, 122, 123, 125,
    127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 141, 142,
    143, 144, 145, 146, 147, 148, 149, 150, 152, 153, 154, 157,
    159, 161, 162, 163, 170, 172, 175, 176, 180, 181, 182, 185,
    190, 192, 193, 195, 197, 199, 203, 214, 215, 219, 223, 224,
    225, 226, 227, 228, 229, 230, 235, 237, 242, 244, 246, 247,
    248, 249, 250, 254, 255, 258, 259, 261, 262, 263, 264, 265,
    266, 267, 274, 277, 278, 280, 282, 285, 286, 287, 288, 289,
    300, 304, 305, 306, 309, 310, 312, 313, 314, 315, 318, 320,
    323, 325, 327, 329, 332, 338, 339, 353, 354, 358, 359, 360,
    361, 362, 365, 366, 367, 368, 370, 372, 373, 375, 376, 378,
    381, 390, 391, 396, 397, 398, 402, 403, 407, 408, 409, 410,
    414, 415, 416, 426, 427, 429, 430, 432, 434, 435, 437, 444,
    445, 446, 447, 448, 449, 450, 453, 454, 458, 459, 463, 465,
    470, 473, 476, 477, 479, 487, 488, 491, 493, 494, 495, 497,
    499, 500, 501, 503, 508, 513, 515, 516, 517, 518, 519, 520,
    521, 522, 523, 524, 525, 528, 530, 533, 534, 535, 543, 547,
    550, 552, 554, 555, 560, 561, 562, 563, 565, 566, 567, 568,
    569, 570, 571, 572, 574, 576, 577, 579, 580, 584, 589, 590,
    591, 592, 594, 595, 596, 597, 598, 600, 601, 602, 603, 604,
    605, 606, 608, 610, 611, 612, 613, 614, 615, 616, 617, 618,
    619, 620, 621, 622, 623, 624, 625, 626, 627, 629, 630, 631,
    632, 633, 635, 636, 637, 638, 639, 640, 641, 642, 644, 645,
    646, 647, 650, 651, 652, 654, 655, 656, 657, 659, 660, 664,
    672, 673, 674, 675, 676, 678, 680, 681, 682, 683, 684, 691,
    692, 693, 694, 696, 697, 698, 699, 700, 701, 702, 703, 704,
    705, 706, 707, 709, 710, 711, 713, 714, 715, 716, 718, 719,
    720, 721, 722, 723, 724, 725, 726, 730, 731, 732, 733, 734,
    735, 1024, 1025, 1026, 1027, 1028,
})
