"""CTDA condition translation: TES4 (24-byte) → TES5 (32-byte).

This is a fresh implementation derived directly from the two xEdit function
tables (wbDefinitionsTES4.pas / wbDefinitionsTES5.pas) per the
`oblivion-to-skyrim-dialog` skill (references/conditions.md):

  - Re-pack 24 bytes → 32 bytes (field-compatible; Skyrim adds trailing fields).
  - Reconcile the function index against the two tables:
      * same index, same name  -> passthrough (138 functions)
      * same name, moved index -> remap (4 functions)
      * index reused for a different function, or removed -> drop
  - Remap FormID parameters to the output plugin's load order.

The remap/drop tables below were generated by joining the two function tables
on numeric index and on name; they are NOT hand-curated lore. See the skill's
conditions reference for the methodology.
"""

import struct

from .text_reader import get_formid_index_offset

# --- CTDA type-byte bits (identical in TES4 and TES5) --------------------------
CTDA_OR = 0x01            # OR with the next condition
CTDA_RUN_ON_TARGET = 0x02 # evaluate against target, not subject
CTDA_USE_GLOBAL = 0x04    # comparison value is a GLOB FormID, not a float

# --- Dialogue-critical function indices (identical in both games) --------------
FUNC_GET_IS_ID = 72            # GetIsID(ref)
FUNC_GET_IN_FACTION = 71       # GetInFaction(fact)
FUNC_GET_STAGE = 58            # GetStage(quest)
FUNC_GET_STAGE_DONE = 59       # GetStageDone(quest, stage)
FUNC_GET_QUEST_RUNNING = 56    # GetQuestRunning(quest)
FUNC_GET_GLOBAL_VALUE = 74     # GetGlobalValue(glob)
FUNC_GET_IS_VOICE_TYPE = 426   # GetIsVoiceType(vtyp)  — TES5-only, no TES4 source

# --- Function-index reconciliation (data-derived; see module docstring) --------
# REMAP: TES4 index -> TES5 index for functions that exist in both games under
# the same name but at a DIFFERENT numeric slot. Verified by name-join of the
# two xEdit tables. (Functions renamed but kept at the same index — e.g.
# GetFatiguePercentage->GetStaminaPercentage at 128 — are passthrough and not
# listed here.)
_FUNC_REMAP = {
    101: 263,    # IsWeaponOut
    116: 459,    # GetCrimeGold
    127: 497,    # CanPayCrimeGold
    1122: 264,   # HasSpell (OBSE) -> TES5 HasSpell
}

# DROP: TES4 indices that either (a) have no TES5 entry at all, or (b) have a
# TES5 entry at that index naming a DIFFERENT function (reused slot). Leaving
# these unchanged would silently invoke the wrong TES5 function. Generated by
# index-join; comments record why.
_FUNC_DROP = frozenset({
    40,    # GetVampire — removed
    # Legacy VM variable reads — TES5 lists these indices but the legacy VM is
    # gone, so they never evaluate true.  Callers that can emit a CIS2 string
    # (convert_ctda_list_with_strings) translate them to GetVMScriptVariable/
    # GetVMQuestVariable INSTEAD of calling convert_ctda; every other path must
    # drop them rather than emit a condition that can never pass.
    53,    # GetScriptVariable  -> 630 GetVMScriptVariable (strings path only)
    79,    # GetQuestVariable   -> 629 GetVMQuestVariable  (strings path only)
    76,    # GetDisposition — removed (disposition system gone)
    81,    # reused: TES5 IsRotating
    104,   # IsYielding — removed
    109,   # reused: TES5 IsWeaponSkillType (semantics changed)
    160,   # GetFurnitureMarkerID — removed
    171,   # IsPlayerInJail — removed
    180,   # reused: TES5 HasSameEditorLocAsRef
    197,   # reused: TES5 GetPCEnemyofFaction
    201,   # GetPCFactionSubmitAuthority — removed
    224,   # reused: TES5 GetVATSMode  (was GetIsPlayerBirthsign)
    227,   # reused: TES5 GetCannibal
    249,   # reused: TES5 IsInDialogueWithPlayer (was GetPCFame) — critical: see skill
    251,   # GetPCInfamy — removed
    258,   # reused: TES5 HasAssociationType
    259,   # reused: TES5 HasFamilyRelationship
    264,   # reused: TES5 HasSpell (was GetBarterGold)
    274,   # reused: TES5 IsSmallBump
    305,   # reused: TES5 GetPlayerAction
    313,   # reused: TES5 GetPairedAnimation
    323,   # reused: TES5 GetCombatState
    329,   # reused: TES5 IsFleeing
    362,   # reused: TES5 HasLinkedRef
    365,   # reused: TES5 IsChild
    # OBSE supplemental indices with no TES5 equivalent
    1107,  # IsAmmo
    1124,  # IsClassSkill
    1884,  # GetPCTrainingSessionsUsed
    # TES4 package-query funcs (2213-2233) — packages are restructured; drop
    2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224,
    2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233,
    2571,  # GetBaseAV3 — removed
    2573,  # IsNaked — removed
    2578,  # IsDiseased — removed
})


# Functions whose param1 is a RACE FormID in BOTH games (ptRace at the same
# index: 69 GetIsRace, 130 GetPCIsRace). TES4 RACE records are never imported
# (SKIP_TYPES) so the generic load-order remap would leave a dangling FormID —
# the CK's "Unable to find ... TESForm in TESConditionItem Parameter Init"
# warning, and a condition that can never be true in-game (2,650+ dialogue
# lines gated on race). Translate the param to the SAME Skyrim race the NPC
# converter assigns (RACE_MAP), so GetIsRace(speaker) keeps matching the
# converted actors and GetPCIsRace matches the player's Skyrim race.
_RACE_PARAM_FUNCS = frozenset({69, 130})


def _map_race_param(fid: int) -> 'int | None':
    from .skyrim_overrides import RACE_MAP, TES4_RACE_FID_TO_EDID
    edid = TES4_RACE_FID_TO_EDID.get(fid & 0x00FFFFFF)
    if edid is None:
        return None
    return RACE_MAP.get(edid)


def _remap_formid(fid: int, offset: int) -> int:
    """Remap a source-file-local FormID to the output plugin's load order.

    Only rewrites the high byte when the FormID is local to the source file
    (high byte 0x00) and is a real record (low 24 bits >= 0x100); engine-fixed
    FormIDs (Player 0x14, etc.) and master-file refs pass through unchanged.
    """
    if offset and (fid >> 24) == 0x00 and (fid & 0x00FFFFFF) >= 0x100:
        return (fid & 0x00FFFFFF) | (offset << 24)
    return fid


# TES4 GetScriptVariable(53) reads a variable on the legacy (pre-Papyrus) script
# system.  Skyrim still LISTS function 53, but the legacy VM is gone and vanilla
# Skyrim.esm uses it exactly ZERO times; the live equivalent is
# GetVMScriptVariable(630), which reads a Papyrus property off a reference
# (4,290 vanilla uses between it and GetVMQuestVariable).  Param2 is a runtime
# string pointer, so the property NAME travels in a companion CIS2 subrecord as
# the mangled `::<name>_var` form (verified: `CIS2=::RadiantAelaBlock_var`).
#
# This is the gate a huge number of Oblivion quest packages actually use — e.g.
# FGC01Rats' escort package is `GetScriptVariable(PinarusREF, packageVAR) == 1`,
# set by the dialogue INFO that agrees to help.  Without this translation the
# condition silently invokes a dead function and the package never fires.
#
# GetQuestVariable(79) is the quest-script twin (`GetQuestVariable Arena,
# ReadyMatch` gates most of the Arena blademaster dialogue) and is equally dead
# in Skyrim; its live equivalent is GetVMQuestVariable(629).  Both use the same
# script_vars table — build_script_var_map indexes QUST FormIDs alongside refs.
GET_SCRIPT_VARIABLE = 53
GET_QUEST_VARIABLE = 79
GET_VM_SCRIPT_VARIABLE = 630
GET_VM_QUEST_VARIABLE = 629

# Legacy variable-read function -> live Papyrus-VM equivalent.
_VM_VAR_FUNCS = {
    GET_SCRIPT_VARIABLE: GET_VM_SCRIPT_VARIABLE,
    GET_QUEST_VARIABLE: GET_VM_QUEST_VARIABLE,
}


def papyrus_var_name(var: str) -> str:
    """Papyrus property name as a CIS2 script-variable reference.

    Must mirror the converter's property renaming (_safe_property_name): the
    ::<name>_var lookup is against the COMPILED property, so a TES4 variable
    the converter had to rename (reserved word, ::temp collision) must be
    referenced by its renamed form.
    """
    from script_convert.constants import _safe_property_name
    return f'::{_safe_property_name(var)}_var'


def convert_ctda(raw: bytes, offset: 'int | None' = None,
                 run_on_target_ref: 'int | None' = None,
                 drop_run_on_target: bool = False) -> 'bytes | None':
    """Convert one 24-byte TES4 CTDA to a 32-byte TES5 CTDA.

    Returns None if the function must be dropped (no faithful TES5 equivalent),
    so the caller can repair the OR chain. The byte layout is field-compatible;
    Skyrim only appends Run On / Reference / trailing fields.

    run_on_target_ref / drop_run_on_target handle conditions in SCRIPT-DRIVEN
    (Say/SayTo) topics: Skyrim's Actor.Say() has no dialogue target, so a
    RunOn=Target condition evaluates against nothing and can never pass
    (CharacterGen: every Valen Dreth taunt is race-of-target gated — the whole
    intro froze). When the script's SayTo target is known and unique, the
    condition is retargeted to RunOn=Reference on that ref (equivalent — for
    menu dialogue too, where the target IS the player); when the topic's
    targets are mixed/unknown, drop_run_on_target discards the condition
    (Oblivion's call sites already pick speaker+topic, so auto-pass is closer
    to intent than never-pass).
    """
    if offset is None:
        offset = get_formid_index_offset()
    data = raw + b'\x00' * max(0, 24 - len(raw))

    type_byte = data[0]
    comp_raw = struct.unpack_from('<I', data, 4)[0]
    func_idx = struct.unpack_from('<H', data, 8)[0]
    param1 = struct.unpack_from('<I', data, 12)[0]
    param2 = struct.unpack_from('<I', data, 16)[0]

    if func_idx in _FUNC_DROP:
        return None
    func_idx = _FUNC_REMAP.get(func_idx, func_idx)

    # Comparison value is a GLOB FormID only when the Use Global flag is set.
    if type_byte & CTDA_USE_GLOBAL:
        comp_raw = _remap_formid(comp_raw, offset)
    if func_idx in _RACE_PARAM_FUNCS:
        # RACE records aren't imported: translate the param to the Skyrim
        # race the converted NPCs actually use, or drop the condition.
        param1 = _map_race_param(param1)
        if param1 is None:
            return None
    else:
        param1 = _remap_formid(param1, offset)
    param2 = _remap_formid(param2, offset)

    # TES4 "Run on target" flag -> TES5 Run On = 1 (Target). Clear the flag bit
    # so it isn't double-counted; everything else stays Subject (0).
    run_on = 0
    reference = 0
    if type_byte & CTDA_RUN_ON_TARGET:
        type_byte &= ~CTDA_RUN_ON_TARGET
        if run_on_target_ref is not None:
            run_on = 2                    # Reference
            reference = run_on_target_ref
        elif drop_run_on_target:
            return None
        else:
            run_on = 1                    # Target

    # 32-byte TES5 CTDA: type(1)+pad(3) comp(4) func(2)+pad(2) p1(4) p2(4)
    #                    runOn(4) reference(4) unknown(4)
    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       run_on, reference, 0xFFFFFFFF)


def convert_ctda_list(rec: dict, offset: 'int | None' = None,
                      prefix: str = '') -> list:
    """Convert all of a record's TES4 conditions, repairing the OR chain.

    Reads [prefix]Condition[i].Raw (24-byte hex blobs) and returns a list of
    32-byte TES5 CTDAs. prefix selects nested condition lists (e.g.
    'Target[2].' for quest target conditions). Dropping a condition that
    participated in an OR group is safe — it's simply removed from the group —
    but the LAST surviving condition must not retain a dangling OR flag, so we
    clear it.
    """
    if offset is None:
        offset = get_formid_index_offset()
    out = []
    i = 0
    while True:
        raw_hex = rec.get(f'{prefix}Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex:
            continue
        try:
            ctda = convert_ctda(bytes.fromhex(raw_hex), offset)
        except (ValueError, struct.error):
            continue
        if ctda is not None:
            out.append(ctda)
    # Repair: a trailing OR flag with nothing after it is invalid.
    if out and (out[-1][0] & CTDA_OR):
        out[-1] = bytes([out[-1][0] & ~CTDA_OR]) + out[-1][1:]
    return out


def convert_ctda_list_with_strings(rec: dict, script_vars: dict = None,
                                   offset: 'int | None' = None,
                                   prefix: str = '',
                                   run_on_target_ref: 'int | None' = None,
                                   drop_run_on_target: bool = False) -> list:
    """Like convert_ctda_list, but returns [(ctda_bytes, cis2_or_None)].

    A TES4 GetScriptVariable condition carries its variable NAME as a script-
    local index we cannot see in the CTDA itself — the name lives in the target
    ref's script.  `script_vars` maps ref_fid -> {var_index: var_name} (built by
    the caller from the SCPT records), letting us re-emit the condition as
    GetVMScriptVariable + a CIS2 naming the Papyrus property.

    Conditions whose variable we cannot resolve are DROPPED rather than emitted
    against the dead legacy function — a condition that can never be true would
    silently disable the package it gates.
    """
    if offset is None:
        offset = get_formid_index_offset()
    script_vars = script_vars or {}
    out = []
    i = 0
    while True:
        raw_hex = rec.get(f'{prefix}Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
        except ValueError:
            continue

        func = struct.unpack_from('<H', raw + b'\0' * 24, 8)[0]
        if func in _VM_VAR_FUNCS:
            pair = _convert_script_var_ctda(raw, script_vars, offset,
                                            run_on_target_ref,
                                            drop_run_on_target)
            if pair is not None:
                out.append(pair)
            continue

        try:
            ctda = convert_ctda(raw, offset,
                                run_on_target_ref=run_on_target_ref,
                                drop_run_on_target=drop_run_on_target)
        except (ValueError, struct.error):
            continue
        if ctda is not None:
            out.append((ctda, None))

    if out and (out[-1][0][0] & CTDA_OR):
        fixed = bytes([out[-1][0][0] & ~CTDA_OR]) + out[-1][0][1:]
        out[-1] = (fixed, out[-1][1])
    return out


def _convert_script_var_ctda(raw: bytes, script_vars: dict, offset: int,
                             run_on_target_ref: 'int | None' = None,
                             drop_run_on_target: bool = False):
    """GetScriptVariable(ref, varIdx) -> GetVMScriptVariable(ref, '::var_var');
    GetQuestVariable(quest, varIdx) -> GetVMQuestVariable(quest, '::var_var')."""
    data = raw + b'\x00' * max(0, 24 - len(raw))
    type_byte = data[0]
    comp_raw = struct.unpack_from('<I', data, 4)[0]
    func = struct.unpack_from('<H', data, 8)[0]
    param1 = struct.unpack_from('<I', data, 12)[0]   # the ref / the quest
    param2 = struct.unpack_from('<I', data, 16)[0]   # script-local var index

    ref = _remap_formid(param1, offset)
    name = script_vars.get(param1 & 0x00FFFFFF, {}).get(param2)
    if not name:
        return None

    if type_byte & CTDA_USE_GLOBAL:
        comp_raw = _remap_formid(comp_raw, offset)
    run_on = 0
    reference = 0
    if type_byte & CTDA_RUN_ON_TARGET:
        type_byte &= ~CTDA_RUN_ON_TARGET
        if run_on_target_ref is not None:
            run_on = 2
            reference = run_on_target_ref
        elif drop_run_on_target:
            return None
        else:
            run_on = 1

    ctda = struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       _VM_VAR_FUNCS[func], 0,
                       ref, 0,
                       run_on, reference, 0xFFFFFFFF)
    return ctda, papyrus_var_name(name)


# --- Builders for the Skyrim-required injected conditions ----------------------

def build_ctda(func_idx: int, param1: int = 0, param2: int = 0,
               comp_value: float = 1.0, operator: int = 0x00,
               is_or: bool = False) -> bytes:
    """Build a 32-byte TES5 CTDA. operator is the high-nibble comparison
    (0x00 ==, 0x60 >=, etc.); is_or sets the OR flag for chaining."""
    type_byte = operator | (CTDA_OR if is_or else 0)
    comp_raw = struct.unpack('<I', struct.pack('<f', comp_value))[0]
    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       0, 0, 0xFFFFFFFF)


def build_or_chain(func_idx: int, param1_fids: list, comp_value: float = 1.0,
                   operator: int = 0x00) -> bytes:
    """Build an OR-chain of func(param)==value CTDAs (OR on all but the last).

    Returns packed CTDA subrecords ready to concatenate. Empty list -> b''.
    """
    from .record_types.common import pack_subrecord
    fids = sorted(set(param1_fids))
    out = b''
    for idx, fid in enumerate(fids):
        is_last = (idx == len(fids) - 1)
        out += pack_subrecord(
            'CTDA', build_ctda(func_idx, param1=fid, comp_value=comp_value,
                               operator=operator, is_or=not is_last))
    return out


def read_getisid_fids(rec: dict, offset: 'int | None' = None,
                      positive_only: bool = True) -> set:
    """Collect remapped NPC FormIDs from GetIsID conditions on a record.

    positive_only restricts to GetIsID(X) == 1.0 (the "is this NPC" form),
    ignoring negated/comparison forms.
    """
    if offset is None:
        offset = get_formid_index_offset()
    fids = set()
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] != FUNC_GET_IS_ID:
                continue
            if positive_only:
                operator = raw[0] & 0xF0
                comp = struct.unpack_from('<f', raw, 4)[0]
                if operator != 0x00 or comp != 1.0:
                    continue
            fids.add(_remap_formid(struct.unpack_from('<I', raw, 12)[0], offset))
        except (ValueError, struct.error):
            continue
    return fids


def has_positive_getisid(rec: dict) -> bool:
    """True if the record has at least one GetIsID(X) == 1.0 condition."""
    return bool(read_getisid_fids(rec, positive_only=True))


def read_func_param_fids(rec: dict, func_idx: int,
                         offset: 'int | None' = None) -> set:
    """Remapped param1 FormIDs of every `func(X) == 1.0` condition on a record.

    Used to harvest the "who is this line for" gates a sibling INFO carries
    (e.g. GetInFaction(Beggars)) so a conditionless sibling can inherit them.
    """
    if offset is None:
        offset = get_formid_index_offset()
    fids = set()
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] != func_idx:
                continue
            if (raw[0] & 0xF0) != 0x00 or struct.unpack_from('<f', raw, 4)[0] != 1.0:
                continue
            fid = struct.unpack_from('<I', raw, 12)[0]
            if fid:
                fids.add(_remap_formid(fid, offset))
        except (ValueError, struct.error):
            continue
    return fids


def has_any_conditions(rec: dict) -> bool:
    """True if the record carries at least one TES4 condition."""
    return bool(rec.get('Condition[0].Raw'))


# TES4 condition functions that already answer "WHO is this line for":
# GetInCell(67), GetIsClass(68), GetIsRace(69), GetInFaction(71), GetIsID(72),
# GetFactionRank(73). GetIsSex(70) is deliberately excluded — male/female alone
# is not an audience restriction.
_AUDIENCE_FUNCS = frozenset({67, 68, 69, 71, 72, 73})


def has_audience_condition(rec: dict) -> bool:
    """True if the record already restricts WHICH actors the line reaches.

    An INFO gated on a cell, class, race, faction or actor has stated its own
    audience — injecting a GetIsID OR-chain harvested from its siblings on top
    would narrow it to a handful of NPCs (e.g. AnvilTopic, gated GetInCell
    (Anvil), would stop reaching most Anvil NPCs).
    """
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] in _AUDIENCE_FUNCS:
                return True
        except (ValueError, struct.error):
            continue
    return False
