"""CTDA condition translation: TES4 (24-byte) → TES5 (32-byte).

This is a fresh implementation derived directly from the two xEdit function
tables (wbDefinitionsTES4.pas / wbDefinitionsTES5.pas) per the
`oblivion-to-skyrim-dialog` skill (references/conditions.md):

  - Re-pack 24 bytes → 32 bytes (field-compatible; Skyrim adds trailing fields).
  - Reconcile the function index against the two tables:
      * same index, same name  -> passthrough (138 functions)
      * same name, moved index -> remap (4 functions)
      * index reused for a different function, or removed -> drop
  - Remap FormID parameters to the output plugin's load order.

The remap/drop tables below were generated by joining the two function tables
on numeric index and on name; they are NOT hand-curated lore. See the skill's
conditions reference for the methodology.
"""

import struct

from .text_reader import get_formid_index_offset

# --- CTDA type-byte bits (identical in TES4 and TES5) --------------------------
CTDA_OR = 0x01            # OR with the next condition
CTDA_RUN_ON_TARGET = 0x02 # evaluate against target, not subject
CTDA_USE_GLOBAL = 0x04    # comparison value is a GLOB FormID, not a float

# --- Dialogue-critical function indices (identical in both games) --------------
FUNC_GET_IS_ID = 72            # GetIsID(ref)
FUNC_GET_STAGE = 58            # GetStage(quest)
FUNC_GET_STAGE_DONE = 59       # GetStageDone(quest, stage)
FUNC_GET_QUEST_RUNNING = 56    # GetQuestRunning(quest)
FUNC_GET_IS_VOICE_TYPE = 426   # GetIsVoiceType(vtyp)  — TES5-only, no TES4 source

# --- Function-index reconciliation (data-derived; see module docstring) --------
# REMAP: TES4 index -> TES5 index for functions that exist in both games under
# the same name but at a DIFFERENT numeric slot. Verified by name-join of the
# two xEdit tables. (Functions renamed but kept at the same index — e.g.
# GetFatiguePercentage->GetStaminaPercentage at 128 — are passthrough and not
# listed here.)
_FUNC_REMAP = {
    101: 263,    # IsWeaponOut
    116: 459,    # GetCrimeGold
    127: 497,    # CanPayCrimeGold
    1122: 264,   # HasSpell (OBSE) -> TES5 HasSpell
}

# DROP: TES4 indices that either (a) have no TES5 entry at all, or (b) have a
# TES5 entry at that index naming a DIFFERENT function (reused slot). Leaving
# these unchanged would silently invoke the wrong TES5 function. Generated by
# index-join; comments record why.
_FUNC_DROP = frozenset({
    40,    # GetVampire — removed
    76,    # GetDisposition — removed (disposition system gone)
    81,    # reused: TES5 IsRotating
    104,   # IsYielding — removed
    109,   # reused: TES5 IsWeaponSkillType (semantics changed)
    160,   # GetFurnitureMarkerID — removed
    171,   # IsPlayerInJail — removed
    180,   # reused: TES5 HasSameEditorLocAsRef
    197,   # reused: TES5 GetPCEnemyofFaction
    201,   # GetPCFactionSubmitAuthority — removed
    224,   # reused: TES5 GetVATSMode  (was GetIsPlayerBirthsign)
    227,   # reused: TES5 GetCannibal
    249,   # reused: TES5 IsInDialogueWithPlayer (was GetPCFame) — critical: see skill
    251,   # GetPCInfamy — removed
    258,   # reused: TES5 HasAssociationType
    259,   # reused: TES5 HasFamilyRelationship
    264,   # reused: TES5 HasSpell (was GetBarterGold)
    274,   # reused: TES5 IsSmallBump
    305,   # reused: TES5 GetPlayerAction
    313,   # reused: TES5 GetPairedAnimation
    323,   # reused: TES5 GetCombatState
    329,   # reused: TES5 IsFleeing
    362,   # reused: TES5 HasLinkedRef
    365,   # reused: TES5 IsChild
    # OBSE supplemental indices with no TES5 equivalent
    1107,  # IsAmmo
    1124,  # IsClassSkill
    1884,  # GetPCTrainingSessionsUsed
    # TES4 package-query funcs (2213-2233) — packages are restructured; drop
    2213, 2214, 2215, 2216, 2217, 2218, 2219, 2220, 2221, 2222, 2223, 2224,
    2225, 2226, 2227, 2228, 2229, 2230, 2231, 2232, 2233,
    2571,  # GetBaseAV3 — removed
    2573,  # IsNaked — removed
    2578,  # IsDiseased — removed
})


def _remap_formid(fid: int, offset: int) -> int:
    """Remap a source-file-local FormID to the output plugin's load order.

    Only rewrites the high byte when the FormID is local to the source file
    (high byte 0x00) and is a real record (low 24 bits >= 0x100); engine-fixed
    FormIDs (Player 0x14, etc.) and master-file refs pass through unchanged.
    """
    if offset and (fid >> 24) == 0x00 and (fid & 0x00FFFFFF) >= 0x100:
        return (fid & 0x00FFFFFF) | (offset << 24)
    return fid


def convert_ctda(raw: bytes, offset: 'int | None' = None) -> 'bytes | None':
    """Convert one 24-byte TES4 CTDA to a 32-byte TES5 CTDA.

    Returns None if the function must be dropped (no faithful TES5 equivalent),
    so the caller can repair the OR chain. The byte layout is field-compatible;
    Skyrim only appends Run On / Reference / trailing fields.
    """
    if offset is None:
        offset = get_formid_index_offset()
    data = raw + b'\x00' * max(0, 24 - len(raw))

    type_byte = data[0]
    comp_raw = struct.unpack_from('<I', data, 4)[0]
    func_idx = struct.unpack_from('<H', data, 8)[0]
    param1 = struct.unpack_from('<I', data, 12)[0]
    param2 = struct.unpack_from('<I', data, 16)[0]

    if func_idx in _FUNC_DROP:
        return None
    func_idx = _FUNC_REMAP.get(func_idx, func_idx)

    # Comparison value is a GLOB FormID only when the Use Global flag is set.
    if type_byte & CTDA_USE_GLOBAL:
        comp_raw = _remap_formid(comp_raw, offset)
    param1 = _remap_formid(param1, offset)
    param2 = _remap_formid(param2, offset)

    # TES4 "Run on target" flag -> TES5 Run On = 1 (Target). Clear the flag bit
    # so it isn't double-counted; everything else stays Subject (0).
    run_on = 0
    if type_byte & CTDA_RUN_ON_TARGET:
        run_on = 1
        type_byte &= ~CTDA_RUN_ON_TARGET

    # 32-byte TES5 CTDA: type(1)+pad(3) comp(4) func(2)+pad(2) p1(4) p2(4)
    #                    runOn(4) reference(4) unknown(4)
    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       run_on, 0, 0xFFFFFFFF)


def convert_ctda_list(rec: dict, offset: 'int | None' = None,
                      prefix: str = '') -> list:
    """Convert all of a record's TES4 conditions, repairing the OR chain.

    Reads [prefix]Condition[i].Raw (24-byte hex blobs) and returns a list of
    32-byte TES5 CTDAs. prefix selects nested condition lists (e.g.
    'Target[2].' for quest target conditions). Dropping a condition that
    participated in an OR group is safe — it's simply removed from the group —
    but the LAST surviving condition must not retain a dangling OR flag, so we
    clear it.
    """
    if offset is None:
        offset = get_formid_index_offset()
    out = []
    i = 0
    while True:
        raw_hex = rec.get(f'{prefix}Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex:
            continue
        try:
            ctda = convert_ctda(bytes.fromhex(raw_hex), offset)
        except (ValueError, struct.error):
            continue
        if ctda is not None:
            out.append(ctda)
    # Repair: a trailing OR flag with nothing after it is invalid.
    if out and (out[-1][0] & CTDA_OR):
        out[-1] = bytes([out[-1][0] & ~CTDA_OR]) + out[-1][1:]
    return out


# --- Builders for the Skyrim-required injected conditions ----------------------

def build_ctda(func_idx: int, param1: int = 0, param2: int = 0,
               comp_value: float = 1.0, operator: int = 0x00,
               is_or: bool = False) -> bytes:
    """Build a 32-byte TES5 CTDA. operator is the high-nibble comparison
    (0x00 ==, 0x60 >=, etc.); is_or sets the OR flag for chaining."""
    type_byte = operator | (CTDA_OR if is_or else 0)
    comp_raw = struct.unpack('<I', struct.pack('<f', comp_value))[0]
    return struct.pack('<B3xIHHIIII I',
                       type_byte, comp_raw,
                       func_idx, 0,
                       param1, param2,
                       0, 0, 0xFFFFFFFF)


def build_or_chain(func_idx: int, param1_fids: list, comp_value: float = 1.0,
                   operator: int = 0x00) -> bytes:
    """Build an OR-chain of func(param)==value CTDAs (OR on all but the last).

    Returns packed CTDA subrecords ready to concatenate. Empty list -> b''.
    """
    from .record_types.common import pack_subrecord
    fids = sorted(set(param1_fids))
    out = b''
    for idx, fid in enumerate(fids):
        is_last = (idx == len(fids) - 1)
        out += pack_subrecord(
            'CTDA', build_ctda(func_idx, param1=fid, comp_value=comp_value,
                               operator=operator, is_or=not is_last))
    return out


def read_getisid_fids(rec: dict, offset: 'int | None' = None,
                      positive_only: bool = True) -> set:
    """Collect remapped NPC FormIDs from GetIsID conditions on a record.

    positive_only restricts to GetIsID(X) == 1.0 (the "is this NPC" form),
    ignoring negated/comparison forms.
    """
    if offset is None:
        offset = get_formid_index_offset()
    fids = set()
    i = 0
    while True:
        raw_hex = rec.get(f'Condition[{i}].Raw')
        if raw_hex is None:
            break
        i += 1
        if not raw_hex or len(raw_hex) < 24:
            continue
        try:
            raw = bytes.fromhex(raw_hex)
            if struct.unpack_from('<H', raw, 8)[0] != FUNC_GET_IS_ID:
                continue
            if positive_only:
                operator = raw[0] & 0xF0
                comp = struct.unpack_from('<f', raw, 4)[0]
                if operator != 0x00 or comp != 1.0:
                    continue
            fids.add(_remap_formid(struct.unpack_from('<I', raw, 12)[0], offset))
        except (ValueError, struct.error):
            continue
    return fids


def has_positive_getisid(rec: dict) -> bool:
    """True if the record has at least one GetIsID(X) == 1.0 condition."""
    return bool(read_getisid_fids(rec, positive_only=True))
