"""
TES5 Import Orchestrator — Reads TES4 exports and writes TES5 ESM/ESP files.

Handles:
- Reading per-type export files from a directory
- Converting each record using tes5_import converters
- Building proper group hierarchies (CELL/WRLD/DIAL)
- FormID remapping (load order adjustment)
- Writing the final binary file

Usage:
    python -m tes5_import export/Oblivion.esm -o output/Oblivion.esm
"""

import argparse
import os
import struct
import sys
import time
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor

from .constants import IMPORT_DISPATCH, SKIP_TYPES, TYPE_MAP
from .master_manifest import write_manifest
from .overrides import (OverrideContext, build_nested_overrides,
                        detect_injected_records)
from .magic_effects import set_tes4_effect_names
from .dialog_converter import (
    build_dialog_groups,
    build_npc_to_vtyp_map,
    compute_quest_priorities,
    convert_QUST,
)
from .record_types.dialog_misc import convert_SOUN
from .skyrim_overrides import (
    CUSTOM_VTYP_EDIDS,
    TES4_RACE_FID_TO_EDID,
    VOICE_TYPE_MAP,
    set_voice_type,
)
from .navi_builder import NAVI_SINGLETON_FID, build_navi_record
from .locations import build_marker_locations
from .record_types.world import (
    convert_ACHR,
    convert_CELL,
    convert_LAND,
    convert_LTEX,
    convert_REFR,
    convert_WRLD,
    set_cell_locations,
)
from .text_reader import (
    get_float,
    get_formid,
    get_formid_index_offset,
    get_int,
    get_str,
    group_records_by_type,
    parse_export_directory,
    get_injected_formids,
    set_formid_index_offset,
    set_injected_formids,
)
from .writer import (
    PluginWriter,
    pack_group,
    pack_record,
    pack_string_subrecord,
    pack_subrecord,
    pack_uint32_subrecord,
)

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from worker_budget import worker_count  # noqa: E402

# Well-known property names that are generated by the script converter for
# TES4-specific systems with no Skyrim equivalent. These records must be
# created in the output ESM so VMAD properties can reference them.
_WELL_KNOWN_PROPERTIES: dict[str, int] = {}   # populated by _create_tes4_special_records


def _create_tes4_special_records(writer: PluginWriter):
    """Create globals and factions needed by converted Papyrus scripts.

    TES4Fame / TES4Infamy: Replace Oblivion's GetPCFame/GetPCInfamy system.
    TES4CyrodiilCrimeFaction: Replace Oblivion's single crime faction system.

    FormIDs are stored in _WELL_KNOWN_PROPERTIES so VMAD builders can inject
    them as property values, eliminating the "fill in CK" step.
    """
    # TES4Fame — GlobalVariable (Float, initial 0.0)
    fame_fid = writer.alloc_formid()
    fame_subs = pack_string_subrecord('EDID', 'TES4Fame')
    fame_subs += pack_subrecord('FNAM', struct.pack('<B', ord('f')))
    fame_subs += pack_subrecord('FLTV', struct.pack('<f', 0.0))
    writer.add_record('GLOB', pack_record('GLOB', fame_fid, 0, fame_subs))
    _WELL_KNOWN_PROPERTIES['TES4Fame'] = fame_fid

    # TES4Infamy — GlobalVariable (Float, initial 0.0)
    infamy_fid = writer.alloc_formid()
    infamy_subs = pack_string_subrecord('EDID', 'TES4Infamy')
    infamy_subs += pack_subrecord('FNAM', struct.pack('<B', ord('f')))
    infamy_subs += pack_subrecord('FLTV', struct.pack('<f', 0.0))
    writer.add_record('GLOB', pack_record('GLOB', infamy_fid, 0, infamy_subs))
    _WELL_KNOWN_PROPERTIES['TES4Infamy'] = infamy_fid

    # TES4CyrodiilCrimeFaction — Faction with crime flags
    crime_fid = writer.alloc_formid()
    crime_subs = pack_string_subrecord('EDID', 'TES4CyrodiilCrimeFaction')
    crime_subs += pack_string_subrecord('FULL', 'Cyrodiil Crime Faction')
    # DATA: CanBeOwner(0x8000) + all crime flags
    crime_flags = 0x8000 | 0x0080 | 0x0100 | 0x0200 | 0x0400 | 0x0800 | 0x2000 | 0x10000
    crime_subs += pack_subrecord('DATA', struct.pack('<I', crime_flags))
    # CRVA — Crime Values (defaults)
    crime_subs += pack_subrecord('CRVA', struct.pack('<HHHHIfI', 0, 0, 0, 0, 0, 1.0, 0))
    writer.add_record('FACT', pack_record('FACT', crime_fid, 0, crime_subs))
    _WELL_KNOWN_PROPERTIES['TES4CyrodiilCrimeFaction'] = crime_fid

    print(f"  Created TES4 special records: "
          f"TES4Fame={fame_fid:08X}, TES4Infamy={infamy_fid:08X}, "
          f"TES4CyrodiilCrimeFaction={crime_fid:08X}")


def _create_vtyp_records(writer: PluginWriter):
    """Create custom VTYP records for all Oblivion races in the output plugin.

    All voice types are created from scratch — we never reference Skyrim.esm
    VTYPs.  Voice files go in Sound/Voice/<plugin>/<EditorID>/ and must match
    the EditorIDs created here (TES4Male*, TES4Female*).

    Updates VOICE_TYPE_MAP at runtime so NPC_ converters pick the right FormID.

    DNAM flags: bit 0 = AllowDefaultDialogue, bit 1 = Female
      Male   voices: DNAM = 1
      Female voices: DNAM = 3
    """
    for vtyp_edid, (race_edid, gender) in CUSTOM_VTYP_EDIDS.items():
        fid = writer.alloc_formid()
        dnam = 3 if gender == 'Female' else 1
        subs = pack_string_subrecord('EDID', vtyp_edid)
        subs += pack_subrecord('DNAM', struct.pack('<B', dnam))
        writer.add_record('VTYP', pack_record('VTYP', fid, 0, subs))
        set_voice_type(race_edid, gender, fid)


def _read_tes4_master_count(export_dir: str) -> int:
    """Count Master[N]= lines in the export's _HEADER.txt (0 if absent)."""
    path = os.path.join(export_dir, '_HEADER.txt')
    if not os.path.isfile(path):
        return 0
    count = 0
    with open(path, 'r', encoding='utf-8') as f:
        for line in f:
            if line.startswith('Master['):
                count += 1
    return count


def import_plugin(export_dir: str, output_path: str, masters: list = None,
                  is_esm: bool = True, skip_types: set = None,
                  output_root: str = None):
    """
    Main import entry point. Reads exports and writes a TES5 plugin.

    Args:
        export_dir: Directory containing per-type .txt export files
        output_path: Path for the output .esm/.esp file
        masters: List of master file names (e.g., ['Skyrim.esm'])
        is_esm: Whether to create an ESM (True) or ESP (False)
        skip_types: Additional types to skip
        output_root: Root output dir holding the converted masters at
                     <root>/<Master>/<Master>. Required when the plugin has
                     TES4 masters — its overrides are merged against them.
                     Defaults to the parent of this plugin's output folder.
    """
    if masters is None:
        masters = ['Skyrim.esm']
    if skip_types is None:
        skip_types = set()
    all_skip = SKIP_TYPES | skip_types

    # Per-plugin output dirs are named after the plugin (output/Oblivion.esm/ is
    # a FOLDER); given the folder, write <folder>/<folder-name> inside it rather
    # than failing to overwrite a directory with a file at the end of the run.
    # convert.py always creates that folder up front and passes the inner path,
    # so this only fires for a direct CLI run against an existing plugin dir.
    if os.path.isdir(output_path):
        output_path = os.path.join(
            output_path, os.path.basename(os.path.normpath(output_path)))
    plugin_out_dir = os.path.dirname(output_path)

    # Per-phase wall-clock reporting so slow phases are visible in the log.
    _phase_t = time.time()

    def _phase_done(label: str):
        nonlocal _phase_t
        now = time.time()
        print(f"  [phase] {label}: {now - _phase_t:.1f}s")
        _phase_t = now

    # Finer-grained timer for the phase-0 pre-scans (prints only slow steps).
    _step_t = time.time()

    def _step_done(label: str):
        nonlocal _step_t
        now = time.time()
        if now - _step_t >= 1.0:
            print(f"    [phase0] {label}: {now - _step_t:.1f}s")
        _step_t = now

    # How many masters the file had in TES4. Everything at a load-order index
    # below this is an override of one of those masters; the plugin's own
    # records sit at exactly this index.
    num_tes4_masters = _read_tes4_master_count(export_dir)
    ctx = None
    if num_tes4_masters:
        print(f"  TES4 masters: {num_tes4_masters} "
              f"(records below index {num_tes4_masters:02X} are overrides)")
        # An override is emitted as the MASTER's converted record with only the
        # author's changes applied, so we need three things from the master:
        # its converted bytes, the companion pairings its run recorded, and its
        # raw export (to tell what the author actually changed). OverrideContext
        # bundles all three (see tes5_import/overrides.py).
        if output_root is None:
            output_root = os.path.dirname(plugin_out_dir) or '.'
        _t = time.time()
        ctx = OverrideContext(export_dir, masters, num_tes4_masters,
                              output_root)
        print(f"  Master: {len(ctx.master_index)} converted records, "
              f"{len(ctx.master_manifest)} manifest entries, "
              f"{len(ctx)} exported records ({time.time() - _t:.1f}s)")
        if not len(ctx):
            # No master export to diff against: every record would be treated
            # as new, silently duplicating the master. The warning has already
            # printed; run without an override context.
            ctx = None

    print(f"Reading exports from: {export_dir}")
    t0 = time.time()

    # Parse all records
    all_records = parse_export_directory(export_dir)
    by_type = group_records_by_type(all_records)

    t1 = time.time()
    print(f"  Parsed {len(all_records)} records in {len(by_type)} types ({t1-t0:.2f}s)")
    _phase_done('parse export text')

    for sig in sorted(by_type.keys()):
        special_types = {'LTEX', 'SOUN', 'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE', 'LAND', 'DIAL', 'INFO'}
        status = "SKIP" if sig in all_skip else ("CONVERT" if sig in IMPORT_DISPATCH or sig in special_types else "UNKNOWN")
        print(f"  {sig}: {len(by_type[sig])} records [{status}]")

    # Create writer
    writer = PluginWriter(masters=masters, is_esm=is_esm,
                          description="Converted from TES4 by tes4_export")

    # Set FormID remapping. The TES5 master list is the TES4 one with N new
    # masters (Skyrim.esm) PREPENDED, so every TES4 load-order index — the
    # plugin's own and its masters' alike — shifts up by exactly N.
    #   Oblivion.esm, masters=['Skyrim.esm'], tes4 masters=0 → offset 1:
    #     own 0x00XXXXXX → 0x01XXXXXX
    #   Translation.esp, masters=['Skyrim.esm','Nehrim.esm'],
    #   tes4 masters=['Nehrim.esm'] → offset 1:
    #     Nehrim override 0x00XXXXXX → 0x01XXXXXX  (overrides Nehrim.esm)
    #     own new record  0x01XXXXXX → 0x02XXXXXX
    # Using len(masters) here instead would shift overrides to the plugin's own
    # index, turning every override into a duplicate new record.
    num_new_masters = len(masters) - num_tes4_masters
    set_formid_index_offset(num_new_masters)

    # Determine next FormID from the maximum in the export (before remapping applies)
    # Must scan ALL FormIDs including those in cross-references to avoid collisions
    # Only the plugin's OWN records can constrain its next object id — an
    # override's low bytes belong to the master's id space, not ours.
    max_formid = 0
    for rec in all_records:
        fid_raw = int(rec.get('FormID', '0'), 16)
        if (fid_raw >> 24) & 0xFF != num_tes4_masters:
            continue
        low = fid_raw & 0x00FFFFFF
        if low > max_formid:
            max_formid = low
    file_index = len(masters)  # Our file's index in the TES5 master list
    # Start well above the highest FormID to avoid collision with companion records
    writer.next_object_id = (file_index << 24) | (max_formid + 0x1000)

    # INJECTED records: Oblivion let a plugin ADD a record carrying a MASTER's
    # load-order index (see overrides.detect_injected_records). They are new
    # records — redirect them into our own space before anything converts.
    if num_tes4_masters:
        injected = detect_injected_records(
            all_records, ctx.master_export if ctx else {},
            num_tes4_masters, writer)
        set_injected_formids(injected)
        if injected:
            print(f"  Injected records: {len(injected)} moved out of the "
                  f"master's FormID space into ours")

    # Register TES4 effect display names so synthesized aimed MGEF clones can
    # be named what Oblivion called them (see tes5_import/magic_effects.py).
    set_tes4_effect_names(by_type.get('MGEF', []))

    # --- Phase 0: Create custom VTYP records for voice types not in Skyrim.esm ---
    # Skipped entirely for a plugin with masters: these are SUPPORT records the
    # master's conversion already created (voice types, TES4 globals/factions,
    # vendor/trainer factions, locations). Re-creating them in a dependent
    # plugin duplicates master content — 27 spurious VTYP, 35 GLOB, 27 FACT —
    # and the duplicates then compete with the originals the overrides use.
    _step_t = time.time()
    if not ctx:
        _create_vtyp_records(writer)

        # --- Phase 0a: TES4-specific globals/factions for converted scripts ---
        _create_tes4_special_records(writer)
    _step_done('vtyp/special records')

    # --- Phase 0b: Pre-scan for dialogue conversion ---
    # Build NPC FormID → VTYP FormID mapping for voice type injection, and
    # register it so convert_NPC_/convert_CREA stamp the SAME VNAM-resolved
    # voice on VTCK (an actor whose VTCK disagrees with the dialogue pass's
    # GetIsVoiceType gates never plays its lines).
    npc_to_vtyp = build_npc_to_vtyp_map(by_type, num_new_masters)
    from .record_types.actors import set_npc_voice_map
    set_npc_voice_map(npc_to_vtyp)
    _step_done('npc voice map')

    # AddTopic unlock plan: gated topics get GetGlobalValue conditions and one
    # GLOB each; revealer INFO/stage fragments set the globals (must exist
    # before the QUST pass so quest VMADs can bind them as properties).
    from .dialog_unlocks import build_unlock_plan, create_unlock_globals
    unlock_plan = build_unlock_plan(by_type)
    unlock_globals = create_unlock_globals(writer, unlock_plan)
    print(f"  AddTopic unlocks: {len(unlock_globals)} gated topics, "
          f"{len(unlock_plan['info_reveals'])} revealer INFOs, "
          f"{len(unlock_plan['stage_reveals'])} revealer quest stages")
    _step_done('addtopic unlock plan')

    # --- Phase 0b2: Build FormID → EditorID map for VMAD property resolution ---
    # Scripts reference external records via SCRO FormIDs. To populate VMAD
    # property values (so CK isn't needed), we need EditorIDs to generate
    # property names that match the compiled .psc files.
    fid_to_edid = {}
    for rec in all_records:
        fid_str = rec.get('FormID', '')
        edid_str = rec.get('EditorID', '')
        if fid_str and edid_str:
            try:
                fid_to_edid[int(fid_str, 16)] = edid_str
            except ValueError:
                pass
    print(f"  Built FormID->EditorID map: {len(fid_to_edid)} entries")
    _step_done('fid->edid map')

    # Build CrossRefGraph for INFO script property type detection.
    # INFO result scripts reference factions/quests/etc. as bare EditorID tokens.
    # ScriptConverter needs xref.edid_to_formid + xref.record_type to classify
    # these tokens (Quest/Faction/Actor/etc.) and register them as property refs.
    # Without this, properties like FightersGuild stay unbound (None at runtime).
    from script_convert.cross_ref import CrossRefGraph
    xref = CrossRefGraph()
    for rec in all_records:
        fid_str = rec.get('FormID', '')
        edid_str = rec.get('EditorID', '')
        sig = rec.get('Signature', '')
        if not fid_str:
            continue
        if edid_str:
            edid_low = edid_str.lower()
            xref.edid_to_formid[edid_low] = fid_str
            xref.formid_to_edid[fid_str] = edid_str
            if sig == 'QUST':
                xref.quest_edids.add(edid_low)
        xref.record_type[fid_str] = sig
        # SCPT type/EditorID (needed for get_extends_class + object-script binding)
        if sig == 'SCPT':
            if edid_str:
                xref.script_formid_to_edid[fid_str] = edid_str
            schr_type = rec.get('SCHR.Type')
            if schr_type is not None:
                try:
                    xref.script_formid_to_type[fid_str] = int(schr_type)
                except ValueError:
                    pass
        # Attached-script + placed-ref base chains (get_extends_class, ref typing)
        scri = rec.get('SCRI', '')
        if scri:
            xref.record_scri[fid_str] = scri
        if sig in ('NPC_', 'CREA'):
            xref.npc_formids.add(fid_str)
        if sig in ('ACHR', 'ACRE', 'REFR'):
            name_fid = rec.get('NAME', '')
            if name_fid:
                xref.record_base[fid_str] = name_fid
    # Populate per-script variable tables + ref-as-int analysis so the object
    # script converter can type its properties (same pass the CLI runs).
    scpt_path = os.path.join(export_dir, 'SCPT.txt')
    if os.path.exists(scpt_path):
        xref.build_ref_as_int_map(scpt_path)
    print(f"  Built CrossRefGraph: {len(xref.edid_to_formid)} entries, "
          f"{len(xref.quest_edids)} quests, {len(xref.script_formid_to_edid)} scripts")
    _step_done('cross-ref graph')

    # --- Phase 0b3: Bind converted object scripts (SCPT via SCRI) to records ---
    # Each scriptable object record gets a VMAD naming its compiled TES4_<script>
    # Papyrus script + FormID bindings for the script's external references.
    # Without this the OnActivate/OnLoad/GameMode handlers never run in-game
    # (altars showed no message/effect, nirnroots never stopped their sound).
    from .object_scripts import build_object_script_plan, build_quest_script_plan
    n_obj_scripts = build_object_script_plan(by_type, xref, fid_to_edid)
    print(f"  Object scripts: attached {n_obj_scripts} SCPT scripts to records via VMAD")
    n_qust_scripts = build_quest_script_plan(by_type, xref, fid_to_edid)
    print(f"  Quest scripts: planned {n_qust_scripts} SCRI attachments for QUST VMADs")
    _step_done('object/quest script plans')

    # --- Phase 0c: Create vendor factions for merchant NPCs, plus the
    # trainer faction + per-trainer CLAS clones for the training service ---
    if not ctx:
        from .record_types.actors import (create_trainer_records,
                                          create_vendor_factions)
        create_vendor_factions(by_type, writer)
        create_trainer_records(by_type, writer)
    _step_done('vendor/trainer records')

    # --- Phase 0d: Load mesh bounds for accurate OBND computation ---
    # Bounds cache normally comes from convert.py's mesh-bounds phase (after
    # mesh+speedtree conversion, so it includes speedtree NIFs too). If it's
    # missing — e.g. running the import step standalone — scan it here from
    # the already-converted output meshes so callers never have to run a
    # separate step for this.
    # Cache lives in the export directory: export/<plugin>/mesh_bounds_cache.json
    from .mesh_bounds import load_mesh_bounds, scan_mesh_bounds
    cache_path = os.path.join(export_dir, 'mesh_bounds_cache.json')
    mesh_dir = os.path.join(plugin_out_dir, 'meshes')
    if not os.path.exists(cache_path) and os.path.isdir(mesh_dir):
        print(f"  Mesh bounds cache not found, scanning {mesh_dir}...")
        scan_mesh_bounds(mesh_dir, cache_path)
    load_mesh_bounds(cache_path)
    # Havok collision soups (walkable/blocking triangles) the navmesh is built
    # from, extracted from the CONVERTED meshes. Same fallback as above.
    from asset_convert.collision_extract import load_collision, scan_collision
    col_path = os.path.join(export_dir, 'collision_cache.bin')
    if not os.path.exists(col_path) and os.path.isdir(mesh_dir):
        print(f"  Collision cache not found, scanning {mesh_dir}...")
        scan_collision(mesh_dir, col_path)
    load_collision(col_path)
    _step_done('mesh bounds + collision caches')

    # --- Phase 0e: Compute furniture seat lists from source NIF markers ---
    # FURN MNAM/FNPR must index the converted NIF's clustered seat positions,
    # and REFRs of re-origined furniture models need z compensation
    # (shared algorithm in asset_convert/furniture_markers.py).
    from .record_types.items import load_furniture_models
    load_furniture_models(os.path.join(export_dir, 'meshes'), by_type)
    _step_done('furniture seats')

    # --- Phase 0f: Generated creature RACE/ARMA/ARMO chains ---
    # One race per unique (creature folder, body-part set) among CREA records
    # whose folder was converted by the creature pipeline (creatures step).
    # convert_CREA then points RNAM at the generated race; NPC_ humanoids
    # keep the Skyrim playable-race override system.
    from .creature_races import build_creature_races
    build_creature_races(by_type, writer, export_dir)
    _step_done('creature races')

    # --- Phase 0g: plan AI packages -------------------------------------
    # TES4 PACK records convert to TES5 template instances (pack_converter).
    # Quest-owned packages must hang off a QUST reference alias (ALPC) to
    # outrank the actor's standing schedule, so the alias indices have to be
    # decided BEFORE either QUST or PACK is written — both read this one plan.
    from .pack_aliases import (PackagePlan, build_script_var_map,
                               build_scriptvar_owner_map)
    from .packages import load_package_types
    load_package_types(by_type)

    _script_vars = build_script_var_map(by_type)
    _sv_owner = build_scriptvar_owner_map(by_type, fid_to_edid)
    pack_plan = PackagePlan()
    pack_plan.build(by_type,
                    {get_formid(r, 'FormID') for r in by_type.get('QUST', [])},
                    _sv_owner)
    print(f"  Package plan: {pack_plan.summary()}")

    # Quest packages live on a QUST alias (ALPC), not in the actor's PKID list.
    from .packages import set_quest_packages
    set_quest_packages(pack_plan.owner_quest.keys())

    from .pack_converter import PackContext
    pack_ctx = PackContext(plan=pack_plan, script_vars=_script_vars)
    _step_done('package plan')

    # --- Phase 0h: placed leveled creatures (REFR→LVLC) ---
    # Skyrim only spawns actors from ACHR→NPC_, so each placed LVLC becomes an
    # ACHR aimed at a generated shell NPC_ whose TPLT points at the LVLN.
    # Must run after 0f (needs the generated creature races) and before the
    # CELL/WRLD builders, which read by_type['REFR'] / by_type['ACHR'].
    from .leveled_actors import build_leveled_actor_shells
    n_lvl_achr = build_leveled_actor_shells(by_type, writer)
    print(f"  Leveled creature placements: {n_lvl_achr} REFR -> ACHR "
          f"via generated shell NPCs")
    _step_done('leveled actor shells')

    # --- Phase 0i: index inventory item types for the outfit split ---
    # A TES4 actor equips out of one mixed CNTO inventory; TES5 needs the
    # wearables moved to a DOFT outfit and everything else left in CNTO
    # (see outfits.py). Classifying an item needs its record type and biped
    # slot, so index them before the actor converters run in Phase 1.
    from .outfits import load_item_index
    load_item_index(by_type)
    _phase_done('phase 0 pre-scans')

    # --- Phase 1: Simple record types (flat top-level groups) ---
    print("\nConverting records...")
    t2 = time.time()

    simple_types = set()
    for sig in sorted(by_type.keys()):
        if sig in all_skip:
            continue
        if sig in ('CELL', 'WRLD', 'DIAL', 'INFO', 'REFR', 'ACHR', 'ACRE', 'LAND',
                    'LTEX', 'SOUN', 'PGRD', 'QUST'):
            continue  # Handled separately
        if sig not in IMPORT_DISPATCH:
            continue
        simple_types.add(sig)

    # Types that need the writer passed in (for companion record generation)
    _WRITER_TYPES = {'ARMO', 'CLOT', 'WEAP', 'AMMO', 'NPC_', 'CREA', 'BOOK',
                     'ENCH', 'SPEL', 'SGST'}

    converted = 0
    errors = 0

    # Build work items: list of (sig, target_sig, rec) tuples
    work_items = []
    for sig in sorted(simple_types):
        target_sig = TYPE_MAP.get(sig, sig)
        for rec in by_type[sig]:
            work_items.append((sig, target_sig, rec))

    # Serial on purpose: this whole phase is ~1.5s of GIL-bound Python, so a
    # thread pool adds no speed — but it DID make the output nondeterministic:
    # converters that allocate companion records (ARMA, aimed-MGEF clones, …)
    # called writer.alloc_formid() in thread-completion order, so companion
    # FormIDs and record order shuffled between runs. A plain loop keeps the
    # ESM byte-reproducible. (The genuinely heavy conversion work — text parse,
    # LAND, navmeshes — runs in process pools elsewhere.)
    for sig, target_sig, rec in work_items:
        converter = IMPORT_DISPATCH[sig]
        try:
            src_fid = (rec.get('FormID') or '').upper()

            # OVERRIDE: the master's converted record with only the author's
            # changes substituted (see overrides.py). Nothing is re-derived, so
            # nothing can drift: this is what stops 1821 NPC_ races being
            # rewritten to vanilla Skyrim ones when the author changed none.
            # A 'reconvert' result (authored effect-list change) falls through
            # to the normal path — its FormID still lands on the master's.
            ov = ctx.build(rec, sig) if ctx else None
            if ov is not None and ov.status != 'reconvert':
                if ov.record_bytes:
                    writer.add_record(target_sig, ov.record_bytes)
                    converted += 1
                continue

            # NEW record: the normal conversion path, unchanged.
            with writer.converting(src_fid, get_formid(rec, 'FormID')):
                if sig in _WRITER_TYPES:
                    record_bytes = converter(rec, writer=writer)
                else:
                    record_bytes = converter(rec)
            writer.add_record(target_sig, record_bytes)
            converted += 1
        except Exception as e:
            edid = get_str(rec, 'EditorID', '?')
            print(f"  ERROR converting {sig} '{edid}': {e}")
            errors += 1
    _phase_done(f'phase 1 simple records ({len(work_items)})')

    # --- Phase 2: LTEX (creates TXST companion records) ---
    ltex_records = by_type.get('LTEX', [])
    if ltex_records:
        print(f"  Converting {len(ltex_records)} LTEX records (with TXST creation)...")
        for rec in ltex_records:
            try:
                ov = ctx.build(rec, 'LTEX') if ctx else None
                if ov is not None:
                    # An LTEX override reuses the master's record (and thereby
                    # its TXST companion); converting fresh would mint a
                    # duplicate TXST the master already defines.
                    if ov.record_bytes:
                        writer.add_record('LTEX', ov.record_bytes)
                        converted += 1
                    continue
                ltex_bytes, txst_bytes, txst_fid = convert_LTEX(rec, writer)
                writer.add_record('LTEX', ltex_bytes)
                if txst_bytes:
                    writer.add_record('TXST', txst_bytes)
                converted += 1
            except Exception as e:
                print(f"  ERROR converting LTEX '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3: SOUN (creates SNDR companion records) ---
    soun_records = by_type.get('SOUN', [])
    if soun_records:
        print(f"  Converting {len(soun_records)} SOUN records (with SNDR creation)...")
        for rec in soun_records:
            try:
                ov = ctx.build(rec, 'SOUN') if ctx else None
                if ov is not None:
                    # A SOUN override reuses the master's record (and thereby
                    # its SNDR companion); converting fresh would mint a
                    # duplicate SNDR the master already defines.
                    if ov.record_bytes:
                        writer.add_record('SOUN', ov.record_bytes)
                        converted += 1
                    continue
                soun_bytes, sndr_bytes, sndr_fid = convert_SOUN(rec, writer)
                writer.add_record('SOUN', soun_bytes)
                if sndr_bytes:
                    writer.add_record('SNDR', sndr_bytes)
                converted += 1
            except Exception as e:
                print(f"  ERROR converting SOUN '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3b: QUST ---
    # Zero-stage "conversation container" quests must never outrank a staged
    # quest's dialogue arbitration (see compute_quest_priorities) — this has
    # to run before QUST conversion so convert_QUST writes the EFFECTIVE
    # DNAM.Priority, not the raw TES4 value.
    compute_quest_priorities(by_type)
    # Track all StartGameEnabled quest FormIDs for .seq file generation
    sge_quest_fids = set()
    qust_records = by_type.get('QUST', [])
    if qust_records and 'QUST' not in all_skip:
        print(f"  Converting {len(qust_records)} QUST records...")
        for rec in qust_records:
            try:
                # OVERRIDE: the master's quest, with only the author's changes.
                # Re-converting would rebuild the VMAD script bindings and
                # re-allocate alias indices against state this run doesn't have.
                ov = ctx.build(rec, 'QUST') if ctx else None
                if ov is not None:
                    if ov.record_bytes:
                        writer.add_record('QUST', ov.record_bytes)
                        converted += 1
                    continue

                qust_bytes = convert_QUST(rec, fid_to_edid=fid_to_edid,
                                          well_known_props=_WELL_KNOWN_PROPERTIES,
                                          unlock_plan=unlock_plan,
                                          unlock_globals=unlock_globals,
                                          pack_plan=pack_plan)
                writer.add_record('QUST', qust_bytes)
                converted += 1
                # Track SGE quests for .seq generation
                fid = get_formid(rec, 'FormID')
                flags = get_int(rec, 'DATA.Flags')
                # Quest has SGE if TES4 flag bit 0 set (no longer force all dialogue quests)
                if flags & 0x01:
                    sge_quest_fids.add(fid)
            except Exception as e:
                print(f"  ERROR converting QUST '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3b2: PACK AI packages ---
    # Must run AFTER QUST: convert_QUST allocates the reference-alias indices
    # that a quest package's PTDA/PLDT point at (PackagePlan holds them), so the
    # aliases have to exist before the packages that reference them are written.
    pack_records = by_type.get('PACK', [])
    if pack_records and 'PACK' not in all_skip:
        from .pack_converter import convert_PACK
        print(f"  Converting {len(pack_records)} PACK records...")
        for rec in pack_records:
            try:
                # A PACK override reuses the master's converted package rather
                # than re-deriving it against this run's (empty) alias state.
                ov = ctx.build(rec, 'PACK') if ctx else None
                if ov is not None:
                    if ov.record_bytes:
                        writer.add_record('PACK', ov.record_bytes)
                        converted += 1
                    continue
                writer.add_record('PACK', convert_PACK(rec, pack_ctx))
                converted += 1
            except Exception as e:
                print(f"  ERROR converting PACK "
                      f"'{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    _phase_done('phases 2-3 LTEX/SOUN/QUST/PACK')

    # --- Phase 3c: LCTN Locations ---
    # Skyrim only reveals a map marker when the player discovers the Location it
    # belongs to, and it reads an exterior cell's displayed name off that same
    # Location — Oblivion has neither, so build them here, before the cells are
    # written, since every cell needs an XLCN pointing at one.
    # For a plugin with masters this is skipped: the master already built a
    # LCTN for every marker and cell, and its CELL records already point at
    # them. Building our own would duplicate all 265 and leave the overrides'
    # inherited XLCN pointing at the master's anyway.
    if not ctx:
        set_cell_locations(*build_marker_locations(by_type, writer))

    # --- Phase 4: CELL/WRLD hierarchy (+ PGRD→NAVM navmeshes) ---
    # Base-object model index for navmesh static-footprint carving. Only
    # blocking base types contribute; keyed by raw low-24 FormID so lookups
    # work regardless of load-order remapping.
    base_model_by_fid = _build_base_model_index(by_type)
    # Raw low-24 DOOR base FormIDs, so the navmesh can choke + link at doorways.
    door_fids = _build_door_fid_set(by_type)
    # NAVM metadata accumulated across interior + exterior cells, used to build
    # the single top-level NAVI (Navmesh Info Map) the engine needs.
    navm_metas: list = []

    # Navmesh generation (scipy Delaunay + footprint carving) is the heaviest
    # CPU work in the import and is independent per cell, so run it up front
    # across a thread pool.  FormIDs are pre-allocated in deterministic cell
    # order first, so the output stays byte-identical to the single-threaded
    # path regardless of completion order.  The group builders below then just
    # look up the precomputed (navm_bytes, meta) instead of calling convert_PGRD.
    navm_cache = _precompute_navmeshes(
        by_type, writer, base_model_by_fid, door_fids,
        collision_cache=os.path.join(export_dir, 'collision_cache.bin'))

    # Stitch adjacent exterior cell navmeshes together with Edge Links. Without
    # them every cell mesh is an island and NO actor can path across a cell
    # boundary, so any AI package with an out-of-cell destination starts (the
    # actor stands up) and never moves. Must run after every mesh exists (it
    # needs neighbour NAVM FormIDs + final triangle indices) and before the group
    # builders serialise them. See docs/world_land_navmesh_notes.md.
    from .navm_edge_links import build_edge_links
    build_edge_links(navm_cache)
    _phase_done('phase 4a navmesh generation')

    # LAND is the heaviest per-record converter; convert all of them up front
    # across a process pool (must run after Phase 3c set_cell_locations so the
    # worker state snapshot is complete).
    land_cache = _precompute_land(by_type, export_dir)
    _phase_done('phase 4b LAND conversion')

    if ctx:
        # A CELL's child GRUP REPLACES the master's — it is not merged (see
        # overrides.build_nested_overrides). LAND and PGRD ride along: LAND
        # overrides substitute into the master's converted LAND; PGRD has no
        # output record to patch (it becomes a generated NAVM) and is counted
        # as inexpressible rather than silently dropped.
        build_nested_overrides(
            by_type, ('CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE', 'LAND', 'PGRD'),
            ctx, writer, 'CELL/WRLD/REFR')
        _phase_done('phase 4c/4d CELL+WRLD overrides')
    else:
        _build_cell_groups(by_type, writer, navm_metas, base_model_by_fid,
                           door_fids, navm_cache, land_cache)
        _phase_done('phase 4c CELL groups')
        _build_world_groups(by_type, writer, navm_metas, base_model_by_fid,
                            door_fids, navm_cache, land_cache)
        _phase_done('phase 4d WRLD groups')

    # Build the NAVI record indexing every generated navmesh.  It MUST be an
    # override of Skyrim.esm's singleton 0x00012FB4 — the engine resolves the
    # Navmesh Info Map by that fixed FormID and merges every file's override
    # (all four DLC ESMs ship theirs as 0x00012FB4).  Our old freshly-allocated
    # FormID produced a NAVI the engine never consulted: no navmesh was
    # registered, so no converted NPC could pathfind ANYWHERE (quest travel/
    # escort packages started and the actor just stood; the only movement left
    # was the off-screen teleport failsafe).  See navi_builder.py.
    if navm_metas:
        # Burn one FormID where the old freshly-allocated NAVI id used to be:
        # thousands of records (all generated DIAL/INFO/DLBR/DLVW/LCTN/SNDR)
        # are allocated after this point, and dropping the alloc shifted every
        # one of them relative to previously shipped builds — which scrambles
        # any existing save's Papyrus/dialogue state bound to those FormIDs.
        writer.alloc_formid()
        n_edge = sum(len(m.get('edge_link_fids') or ()) for m in navm_metas)
        n_door = sum(len(m.get('door_refs') or ()) for m in navm_metas)
        from .navi_builder import read_master_nvpp
        from asset_convert.skyrim_assets import find_skyrim_data
        master_nvpp = read_master_nvpp(find_skyrim_data())
        navi_bytes = build_navi_record(NAVI_SINGLETON_FID, navm_metas,
                                       master_nvpp=master_nvpp)
        if navi_bytes:
            writer.add_raw_group('NAVI', navi_bytes)
        print(f"  Built NAVI: {len(navm_metas)} navmeshes registered "
              f"({n_edge} edge links, {n_door} door links, "
              f"NVPP {'vanilla' if master_nvpp else 'EMPTY - no SSE install'})")

    # --- Phase 5: DIAL/INFO hierarchy ---
    voice_map = {}
    if ctx:
        # Same reasoning as CELL: a DIAL's child GRUP of INFOs replaces the
        # master's. Re-running the dialogue pipeline would also re-key topics,
        # regenerate DLBR/DLVW branches the master already has, and re-decide
        # which of the 71 skipped topics to drop. A translation only rewrites
        # response text, so emit flat overrides carrying exactly that.
        build_nested_overrides(by_type, ('DIAL', 'INFO'), ctx, writer,
                               'DIAL/INFO')
        dialog_sge_fids = set()
    else:
        dialog_sge_fids = build_dialog_groups(by_type, writer, npc_to_vtyp, fid_to_edid=fid_to_edid, xref=xref, well_known_props=_WELL_KNOWN_PROPERTIES, voice_map=voice_map, unlock_plan=unlock_plan, unlock_globals=unlock_globals, script_vars=_script_vars)
    sge_quest_fids |= dialog_sge_fids
    _write_voice_map(output_path, voice_map)
    from .dialog_converter import get_lip_texts
    _write_lip_text(output_path, get_lip_texts())
    _phase_done('phase 5 DIAL/INFO groups')

    if ctx:
        ctx.report()

    t3 = time.time()
    print(f"\nConverted {converted} records ({errors} errors) in {t3-t2:.2f}s")

    # Write output
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    writer.write(output_path)
    _phase_done('write output file')

    # Companion manifest: records which generated records belong to which
    # source record, so a plugin that overrides them can reuse ours instead of
    # minting duplicates. Written for every conversion — any file can be a
    # master to something.
    mpath = write_manifest(output_path, os.path.basename(export_dir),
                           writer.manifest())
    print(f"  Wrote {mpath} ({len(writer.manifest())} source records)")

    file_size = os.path.getsize(output_path)
    print(f"Wrote {output_path} ({file_size:,} bytes)")

    # Generate .seq file for StartGameEnabled quests
    _write_seq_file(output_path, sge_quest_fids)

    # Reset FormID remapping
    set_formid_index_offset(0)

    return converted, errors


def _write_voice_map(output_path: str, voice_map: dict):
    """Write the INFO FormID -> voice filename prefix map next to the ESM.

    The audio pipeline (organize_voice_files) uses it to name extracted voice
    files the way the Skyrim engine resolves them at runtime: the prefix is
    built from the CONVERTED records' owning-quest + topic EditorIDs, so the
    Oblivion filename prefix cannot be trusted.
    """
    if not voice_map:
        return
    map_path = output_path + '.voicemap.txt'
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write('# InfoFormID(low24,hex)=prefix[\\tVTYP1,VTYP2] '
                '(questEDID_topicEDID; optional tab-separated target voice-type '
                'folders for NPC-specific lines whose speaker VTYP differs from '
                'the Oblivion source race folder)\n')
        for fid in sorted(voice_map):
            f.write(f'{fid:06X}={voice_map[fid]}\n')
    print(f"  Wrote {map_path} ({len(voice_map)} voice filename prefixes)")


def _write_lip_text(output_path: str, lip_texts: dict):
    """Write the {(info_fid24, resp_num): spoken text} map next to the ESM.

    The audio pipeline pairs each voice WAV with its transcript and runs the
    Creation Kit's LipGenerator to produce the .lip sync track, packing both
    into a .fuz (SSE only reads lip data from .fuz containers).

    Format: one line per response — `<fid24 hex6>_<resp_num>=<text>` with
    backslash escapes for \\ \n \r \t (same scheme as the text export).
    """
    if not lip_texts:
        return
    map_path = output_path + '.liptext.txt'
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write('# InfoFormID(low24,hex)_ResponseNumber=spoken text '
                '(for .lip generation; escapes: \\\\ \\n \\r \\t)\n')
        for (fid, num) in sorted(lip_texts):
            text = (lip_texts[(fid, num)]
                    .replace('\\', '\\\\').replace('\n', '\\n')
                    .replace('\r', '\\r').replace('\t', '\\t'))
            f.write(f'{fid:06X}_{num}={text}\n')
    print(f"  Wrote {map_path} ({len(lip_texts)} response transcripts)")


def _write_seq_file(output_path: str, sge_quest_fids: set):
    """Write a .seq file listing all StartGameEnabled quest FormIDs.

    The Skyrim engine reads this file on game start to initialize SGE quests.
    Without it, quests with the StartGameEnabled flag don't actually start,
    which means dialogue quests never run and no dialog appears.

    Format: raw binary array of uint32 FormIDs (little-endian), no header.
    Path:   <Data>/seq/<PluginName>.seq  (next to the ESM in Data folder)
    """
    if not sge_quest_fids:
        print("  No StartGameEnabled quests — skipping .seq generation")
        return

    output_dir = os.path.dirname(output_path)
    plugin_name = os.path.basename(output_path)
    seq_dir = os.path.join(output_dir, 'seq')
    os.makedirs(seq_dir, exist_ok=True)

    seq_path = os.path.join(seq_dir, os.path.splitext(plugin_name)[0] + '.seq')
    sorted_fids = sorted(sge_quest_fids)
    with open(seq_path, 'wb') as f:
        for fid in sorted_fids:
            f.write(struct.pack('<I', fid))

    print(f"  Wrote {seq_path} ({len(sorted_fids)} SGE quests, "
          f"{len(sorted_fids) * 4} bytes)")


# Base record types whose placed footprint should carve holes in a navmesh.
# Doors/lights/markers/actors are intentionally excluded.
_NAVM_BLOCKING_BASE_TYPES = frozenset({'STAT', 'CONT', 'FURN', 'ACTI', 'TREE'})


def _navm_model_key(model: str) -> str:
    """Normalise a TES4 model path to the mesh_bounds cache key.

    Mirrors mesh_bounds' key format: lowercase, forward slashes, 'tes4/' prefix,
    '.nif' suffix.  e.g. 'Furniture\\ChairNoble01.NIF' -> 'tes4/furniture/chairnoble01.nif'.
    """
    p = model.lower().replace('\\', '/').lstrip('/')
    if p.startswith('textures/'):
        p = p[len('textures/'):]
    if not p.startswith('tes4/'):
        p = 'tes4/' + p
    if not p.endswith('.nif'):
        p += '.nif'
    return p


def _build_base_model_index(by_type: dict) -> dict:
    """Map raw low-24 base-object FormID -> normalised model key.

    Only blocking base types are indexed, so navmesh carving never removes
    triangles under doors, lights, or markers.
    """
    index = {}
    for sig in _NAVM_BLOCKING_BASE_TYPES:
        for rec in by_type.get(sig, []):
            model = get_str(rec, 'Model.MODL') or get_str(rec, 'MODL')
            if not model:
                continue
            fid_str = rec.get('FormID')
            if not fid_str:
                continue
            try:
                low = int(fid_str, 16) & 0x00FFFFFF
            except ValueError:
                continue
            index[low] = _navm_model_key(model)
    return index


def _build_door_fid_set(by_type: dict) -> set:
    """Raw low-24 FormIDs of all DOOR base records (for navmesh door handling)."""
    out = set()
    for rec in by_type.get('DOOR', []):
        fid_str = rec.get('FormID')
        if not fid_str:
            continue
        try:
            out.add(int(fid_str, 16) & 0x00FFFFFF)
        except ValueError:
            continue
    return out


def _gather_navm_jobs(by_type: dict, door_fids: set = None):
    """Enumerate PGRD→NAVM jobs in the exact order the group builders visit them.

    Order is: interior cells (block/sub-block, same key order as
    _build_cell_groups) first, then exterior cells per worldspace (persistent
    cells have no PGRDs, then block/sub-block exterior cells, same key order as
    _build_world_groups).  Keeping this identical to the builders means the
    FormIDs handed out below match the single-threaded allocation exactly.

    Yields job dicts with everything convert_PGRD needs plus a cache key
    (cell_fid, pgrd_fid) the builders use to look the result back up.
    """
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])
    door_fids = door_fids or set()

    refr_by_cell = defaultdict(list)
    for rec in refrs:
        refr_by_cell[get_formid(rec, 'ParentCELL')].append(rec)
    land_by_cell = defaultdict(list)
    for rec in lands:
        land_by_cell[get_formid(rec, 'ParentCELL')].append(rec)
    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        pgrd_by_cell[get_formid(rec, 'ParentCELL')].append(rec)

    # Exterior teleport doors are PERSISTENT refs parented to the worldspace's
    # persistent (dummy) cell — the grid cell they physically stand in never
    # lists them, so exterior navmeshes got no door triangles (89/6,516 vs
    # 1,612/1,640 interiors) and cross-door pathing broke at every house door
    # and city gate.  Bucket each worldspace's persistent door refs by the grid
    # square their POSITION falls in; the matching cell's job stamps + links
    # them like its own doors.
    def _is_door_ref(rec):
        if rec.get('XTEL.Door'):
            return True
        name = rec.get('NAME')
        if not name:
            return False
        try:
            return (int(name, 16) & 0xFFFFFF) in door_fids
        except ValueError:
            return False

    pers_doors_by_grid = defaultdict(list)
    for cell in cells:
        wrld = get_formid(cell, 'ParentWRLD')
        if not wrld or not (get_int(cell, 'RecordFlags') & 0x400):
            continue
        for rec in refr_by_cell.get(get_formid(cell, 'FormID'), []):
            if not _is_door_ref(rec):
                continue
            try:
                x = float(rec.get('PosX', ''))
                y = float(rec.get('PosY', ''))
            except (TypeError, ValueError):
                continue
            pers_doors_by_grid[(wrld, int(x // 4096.0),
                                int(y // 4096.0))].append(rec)

    jobs = []

    def _emit(cell_rec, land_rec, extra_door_refrs=None):
        cell_fid = get_formid(cell_rec, 'FormID')
        cell_refrs = refr_by_cell.get(cell_fid, [])
        for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
            jobs.append({
                'key': (cell_fid, get_formid(pgrd_rec, 'FormID')),
                'pgrd_rec': pgrd_rec,
                'land_rec': land_rec,
                'cell_rec': cell_rec,
                'refr_recs': cell_refrs,
                'extra_door_refrs': extra_door_refrs or [],
            })

    # --- Interior cells (mirror _build_cell_groups ordering) ---
    interior_cells = [c for c in cells if not get_formid(c, 'ParentWRLD')]
    blocks = defaultdict(lambda: defaultdict(list))
    for cell in interior_cells:
        object_id = get_formid(cell, 'FormID') & 0xFFFFFF
        blocks[object_id % 10][(object_id // 10) % 10].append(cell)
    for block_num in sorted(blocks.keys()):
        for sub_block_num in sorted(blocks[block_num].keys()):
            for cell_rec in blocks[block_num][sub_block_num]:
                _emit(cell_rec, None)  # interiors have no LAND

    # --- Exterior cells (mirror _build_world_groups ordering) ---
    worlds = by_type.get('WRLD', [])
    ext_cells_by_wrld = defaultdict(list)
    for cell in cells:
        wrld_fid = get_formid(cell, 'ParentWRLD')
        if wrld_fid:
            ext_cells_by_wrld[wrld_fid].append(cell)

    for wrld_rec in sorted(worlds, key=lambda w: get_formid(w, 'FormID')):
        wrld_fid = get_formid(wrld_rec, 'FormID')
        exterior_cells = [c for c in ext_cells_by_wrld.get(wrld_fid, [])
                          if not (get_int(c, 'RecordFlags') & 0x400)]
        # Persistent cells have no PGRDs generated (builder skips them), so skip.
        ext_blocks = defaultdict(lambda: defaultdict(list))
        for cell in exterior_cells:
            grid_x = get_int(cell, 'XCLC.X')
            grid_y = get_int(cell, 'XCLC.Y')
            block_label = struct.pack('<hh', grid_y // 32, grid_x // 32)
            sub_label = struct.pack('<hh', grid_y // 8, grid_x // 8)
            ext_blocks[block_label][sub_label].append(cell)
        for block_label in sorted(ext_blocks.keys()):
            for sub_label in sorted(ext_blocks[block_label].keys()):
                for cell_rec in sorted(
                        ext_blocks[block_label][sub_label],
                        key=lambda c: (get_int(c, 'XCLC.Y'), get_int(c, 'XCLC.X'))):
                    cell_fid = get_formid(cell_rec, 'FormID')
                    cell_lands = land_by_cell.get(cell_fid, [])
                    _emit(cell_rec, cell_lands[0] if cell_lands else None,
                          pers_doors_by_grid.get(
                              (wrld_fid, get_int(cell_rec, 'XCLC.X'),
                               get_int(cell_rec, 'XCLC.Y')), []))

    return jobs


def _navmesh_geom_cache(collision_cache: str):
    """(cache_dir, tag) for the on-disk navmesh geometry cache, or None.

    The tag hashes the navmesh generator SOURCES plus the collision cache's
    identity, so editing any navmesh code (params included) or rebuilding the
    collision cache invalidates every entry automatically — no version
    constant to forget to bump, no stale-geometry debugging sessions.
    """
    if not collision_cache or not os.path.exists(collision_cache):
        return None
    import glob
    import hashlib
    h = hashlib.sha1()
    pkg = os.path.dirname(os.path.abspath(__file__))
    srcs = sorted(glob.glob(os.path.join(pkg, 'navmesh', '*.py')))
    srcs.append(os.path.join(pkg, 'pgrd_to_navm.py'))
    for src in srcs:
        try:
            with open(src, 'rb') as fh:
                h.update(fh.read())
        except OSError:
            return None
    st = os.stat(collision_cache)
    h.update(repr((st.st_size, int(st.st_mtime))).encode())
    cache_dir = os.path.join(os.path.dirname(collision_cache),
                             'navmesh_geom_cache')
    os.makedirs(cache_dir, exist_ok=True)
    return cache_dir, h.hexdigest()


def _navm_worker_count(job_count: int) -> int:
    """Pick a worker count bounded by the pipeline budget and job count."""
    return min(worker_count(), max(1, job_count))


# Below this many LAND records a process pool costs more than it saves.
_LAND_PARALLEL_MIN = 64
_LAND_CHUNK = 24


def _precompute_land(by_type: dict, export_dir: str) -> dict:
    """Convert every LAND record across a process pool; {fid: (ok, payload)}.

    convert_LAND is by far the heaviest per-record converter (~1 ms each,
    ~16k records — landscape heights/normals/colors/layers all re-packed), and
    it is a pure function of the record dict, so it parallelises cleanly.
    Other cell children (REFR/ACHR/CELL) convert in single-digit microseconds —
    for those the pickle round-trip would cost more than the conversion, so
    they stay serial in the builders.

    Returns None when there are too few LANDs to be worth a pool; builders
    then call convert_LAND directly.
    """
    lands = by_type.get('LAND', [])
    if len(lands) < _LAND_PARALLEL_MIN:
        return None

    from . import convert_worker
    from .locations import WORLD_NAMES
    from .record_types import items as items_mod
    from .record_types import world as world_mod

    initargs = (
        get_formid_index_offset(),
        dict(world_mod._CELL_LOCATION),
        dict(world_mod._GRID_LOCATION),
        dict(world_mod._WORLD_LOCATION),
        dict(WORLD_NAMES),
        dict(items_mod._BASE_ORIGIN_SHIFT),
        os.path.join(export_dir, 'mesh_bounds_cache.json'),
        get_injected_formids(),
    )

    chunks = [[('LAND', rec) for rec in lands[i:i + _LAND_CHUNK]]
              for i in range(0, len(lands), _LAND_CHUNK)]
    workers = _navm_worker_count(len(chunks))
    print(f"  Converting {len(lands)} LAND records across {workers} processes...")
    t0 = time.time()

    cache: dict = {}
    with ProcessPoolExecutor(max_workers=workers,
                             initializer=convert_worker.init_worker,
                             initargs=initargs) as ex:
        for results in ex.map(convert_worker.convert_chunk, chunks):
            for (kind, fid), ok, payload in results:
                cache[fid] = (ok, payload)
    print(f"    LAND conversion: {len(lands)} records in {time.time() - t0:.2f}s")
    return cache


def _land_bytes(land_cache: dict, land_rec: dict) -> bytes:
    """Converted bytes for a LAND record, from the precompute cache if present.

    Failed precomputes re-raise here so the builders' existing per-cell error
    handling reports them exactly as the serial path would.
    """
    if land_cache is not None:
        entry = land_cache.pop(get_formid(land_rec, 'FormID'), None)
        if entry is not None:
            ok, payload = entry
            if not ok:
                raise RuntimeError(payload)
            return payload
    return convert_LAND(land_rec)


def _precompute_navmeshes(by_type: dict, writer: PluginWriter,
                          base_model_by_fid: dict, door_fids: set,
                          collision_cache: str = '') -> dict:
    """Run every PGRD→NAVM conversion in parallel; return {key: (bytes, meta)}.

    FormIDs are pre-allocated serially in builder-visit order so results are
    byte-identical to the single-threaded path regardless of completion order.

    A *process* pool (not threads) is used because convert_PGRD is dominated by
    pure-Python work (edge graph building, coverage masking, adjacency) that
    holds the GIL — only the scipy Delaunay call releases it, so threads
    serialise on the GIL and pin one core.  Processes give true N-core scaling.

    The worker lives in the light-weight `navm_worker` module (NOT this one) so
    each spawned child avoids re-importing the whole import pipeline; it takes
    no writer (FormIDs are pre-assigned) so nothing unpicklable crosses the
    process boundary.  `max_tasks_per_child` recycles workers periodically so
    scipy allocator fragmentation can't grow unbounded across 8k+ cells.
    """
    from . import navm_worker

    jobs = _gather_navm_jobs(by_type, door_fids)
    if not jobs:
        return {}

    # The load-order master-index offset is a text_reader module global set once
    # in this (parent) process; spawned workers start at 0, so capture it and
    # replay it in each child's init or their get_formid() calls mis-map every
    # PathingCell parent FormID (→ navmesh-load null-deref crash).
    formid_offset = get_formid_index_offset()

    # Deterministic FormID assignment (matches serial alloc_formid order).
    for job in jobs:
        job['navm_fid'] = writer.alloc_formid()

    n_workers = _navm_worker_count(len(jobs))
    geom_cache = _navmesh_geom_cache(collision_cache)
    print(f"  Generating {len(jobs)} navmeshes (PGRD->NAVM) "
          f"across {n_workers} processes...")
    t0 = time.time()
    cache: dict = {}

    # A single tiny job isn't worth a process pool's spin-up cost.
    if len(jobs) == 1 or n_workers == 1:
        navm_worker.init_worker(base_model_by_fid, door_fids, collision_cache,
                                formid_offset, geom_cache,
                                get_injected_formids())
        for job in jobs:
            key, result = navm_worker.run_job(job)
            cache[key] = result
    else:
        # chunksize amortises IPC over many small jobs.
        chunksize = max(1, len(jobs) // (n_workers * 8))
        with ProcessPoolExecutor(
                max_workers=n_workers,
                initializer=navm_worker.init_worker,
                initargs=(base_model_by_fid, door_fids, collision_cache,
                          formid_offset, geom_cache,
                          get_injected_formids()),
                max_tasks_per_child=500) as ex:
            for key, result in ex.map(navm_worker.run_job, jobs,
                                      chunksize=chunksize):
                cache[key] = result

    hits = sum(1 for (_b, m) in cache.values()
               if m and m.get('geom_cached'))
    print(f"    Navmesh generation: {len(jobs)} cells in "
          f"{time.time() - t0:.2f}s ({n_workers} workers, "
          f"{hits} geometry-cache hits)")
    return cache


def _build_cell_groups(by_type: dict, writer: PluginWriter,
                       navm_metas: list = None, base_model_by_fid: dict = None,
                       door_fids: set = None, navm_cache: dict = None,
                       land_cache: dict = None):
    """Build CELL group hierarchy (interior cells only — exterior in WRLD)."""
    if navm_metas is None:
        navm_metas = []
    if base_model_by_fid is None:
        base_model_by_fid = {}
    if navm_cache is None:
        navm_cache = {}
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    achrs = by_type.get('ACHR', []) + by_type.get('ACRE', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])

    # Group children by parent CELL
    refr_by_cell = defaultdict(list)
    for rec in refrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        refr_by_cell[cell_fid].append(rec)

    achr_by_cell = defaultdict(list)
    for rec in achrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        achr_by_cell[cell_fid].append(rec)

    land_by_cell = defaultdict(list)
    for rec in lands:
        cell_fid = get_formid(rec, 'ParentCELL')
        land_by_cell[cell_fid].append(rec)

    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        cell_fid = get_formid(rec, 'ParentCELL')
        pgrd_by_cell[cell_fid].append(rec)

    # Interior cells = those NOT in a worldspace
    interior_cells = [c for c in cells if not get_formid(c, 'ParentWRLD')]

    if not interior_cells:
        return

    print(f"  Building CELL hierarchy ({len(interior_cells)} interior cells)...")

    # Group interior cells into blocks/sub-blocks by the last two DECIMAL
    # digits of the ObjectID (FormID with the master-index byte stripped):
    # block = ones digit, sub-block = tens digit (xEdit wbImplementation
    # CheckPosition; verified against Skyrim.esm). The index byte must be
    # excluded so every file computes the same bucket for the same record —
    # the engine re-locates a master's cell through this bucket walk when a
    # plugin wins the CELL record, and a cell in the wrong bucket loses all
    # its temporary children the moment it is overridden.
    blocks = defaultdict(lambda: defaultdict(list))
    for cell in interior_cells:
        object_id = get_formid(cell, 'FormID') & 0xFFFFFF
        block_num = object_id % 10
        sub_block_num = (object_id // 10) % 10
        blocks[block_num][sub_block_num].append(cell)

    # Accumulate group contents in lists and b''.join at each wrap point:
    # bytes += on multi-MB buffers reallocates the whole buffer every append
    # (quadratic); list-append + join is linear.
    all_cell_parts = []
    converted = 0

    for block_num in sorted(blocks.keys()):
        block_parts = []
        for sub_block_num in sorted(blocks[block_num].keys()):
            sub_block_parts = []
            for cell_rec in blocks[block_num][sub_block_num]:
                cell_fid = get_formid(cell_rec, 'FormID')
                try:
                    cell_bytes = convert_CELL(cell_rec)
                    sub_block_parts.append(cell_bytes)

                    # Cell children
                    children_parts = []

                    # Persistent children (group type 8)
                    persistent = []

                    def is_persistent(r):
                        return get_int(r, 'RecordFlags') & 0x400  # Persistent flag
                    for refr_rec in refr_by_cell.get(cell_fid, []):
                        if is_persistent(refr_rec):
                            persistent.append(convert_REFR(refr_rec))
                            converted += 1
                    for achr_rec in achr_by_cell.get(cell_fid, []):
                        if is_persistent(achr_rec):
                            persistent.append(convert_ACHR(achr_rec))
                            converted += 1
                    if persistent:
                        children_parts.append(pack_group(8, struct.pack('<I', cell_fid), b''.join(persistent)))

                    # Temporary children (group type 9)
                    temporary = []
                    for refr_rec in refr_by_cell.get(cell_fid, []):
                        if not is_persistent(refr_rec):
                            temporary.append(convert_REFR(refr_rec))
                            converted += 1
                    for achr_rec in achr_by_cell.get(cell_fid, []):
                        if not is_persistent(achr_rec):
                            temporary.append(convert_ACHR(achr_rec))
                            converted += 1
                    for land_rec in land_by_cell.get(cell_fid, []):
                        temporary.append(_land_bytes(land_cache, land_rec))
                        converted += 1
                    # PGRD → NAVM (interior cells have no LAND; Z from node heights)
                    # Precomputed in parallel by _precompute_navmeshes.
                    for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
                        navm_bytes, meta = navm_cache.get(
                            (cell_fid, get_formid(pgrd_rec, 'FormID')),
                            (None, None))
                        if navm_bytes:
                            temporary.append(navm_bytes)
                            navm_metas.append(meta)
                            converted += 1
                    if temporary:
                        children_parts.append(pack_group(9, struct.pack('<I', cell_fid), b''.join(temporary)))

                    if children_parts:
                        sub_block_parts.append(pack_group(6, struct.pack('<I', cell_fid), b''.join(children_parts)))

                    converted += 1
                except Exception as e:
                    print(f"  ERROR building CELL group for {get_str(cell_rec, 'EditorID', '?')}: {e}")

            if sub_block_parts:
                block_parts.append(pack_group(3, struct.pack('<i', sub_block_num), b''.join(sub_block_parts)))
        if block_parts:
            all_cell_parts.append(pack_group(2, struct.pack('<i', block_num), b''.join(block_parts)))

    if all_cell_parts:
        writer.add_raw_group('CELL', b''.join(all_cell_parts))

    print(f"    Interior cells: {len(interior_cells)}, children: {converted}")


def _build_world_groups(by_type: dict, writer: PluginWriter,
                        navm_metas: list = None, base_model_by_fid: dict = None,
                        door_fids: set = None, navm_cache: dict = None,
                        land_cache: dict = None):
    """Build WRLD group hierarchy (worldspaces + exterior cells)."""
    if navm_metas is None:
        navm_metas = []
    if base_model_by_fid is None:
        base_model_by_fid = {}
    if door_fids is None:
        door_fids = set()
    if navm_cache is None:
        navm_cache = {}
    worlds = by_type.get('WRLD', [])
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    achrs = by_type.get('ACHR', []) + by_type.get('ACRE', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])

    if not worlds:
        return

    # Index exterior cells by worldspace
    ext_cells_by_wrld = defaultdict(list)
    for cell in cells:
        wrld_fid = get_formid(cell, 'ParentWRLD')
        if wrld_fid:
            ext_cells_by_wrld[wrld_fid].append(cell)

    # Index children by parent cell
    refr_by_cell = defaultdict(list)
    for rec in refrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        refr_by_cell[cell_fid].append(rec)

    achr_by_cell = defaultdict(list)
    for rec in achrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        achr_by_cell[cell_fid].append(rec)

    # Re-home misplaced exterior refs.  Oblivion.esm ships a handful of
    # temporary refs attached to a grid cell that does not match their
    # coordinates (the TES4 CS tolerated it; 11 in Tamriel).  The Skyrim CK
    # does not: on load it warns "Reference attached to wrong cell for its
    # location" for each and relocates them — and hangs there.  Attach each
    # such ref to the cell its position actually falls in.  Persistent refs
    # and refs in persistent (dummy) cells keep their cells: the engine loads
    # those by worldspace, not by grid.
    grid_cell = {}   # (wrld, gx, gy) -> cell FormID, non-persistent cells only
    cell_grid = {}   # cell FormID -> (wrld, gx, gy)
    for cell in cells:
        if get_int(cell, 'RecordFlags') & 0x400:
            continue
        if not get_str(cell, 'XCLC.X'):
            continue
        key = (get_formid(cell, 'ParentWRLD'),
               get_int(cell, 'XCLC.X'), get_int(cell, 'XCLC.Y'))
        fid = get_formid(cell, 'FormID')
        grid_cell.setdefault(key, fid)
        cell_grid[fid] = key
    rehomed = 0
    for by_cell in (refr_by_cell, achr_by_cell):
        for cell_fid in list(by_cell):
            grid = cell_grid.get(cell_fid)
            if grid is None:
                continue
            wrld_fid, cx, cy = grid
            kept = []
            for rec in by_cell[cell_fid]:
                if (not (get_int(rec, 'RecordFlags') & 0x400)
                        and get_str(rec, 'PosX')):
                    # Same floor semantics as world._ref_grid.
                    gx = int(get_float(rec, 'PosX') // 4096.0)
                    gy = int(get_float(rec, 'PosY') // 4096.0)
                    if (gx, gy) != (cx, cy):
                        target = grid_cell.get((wrld_fid, gx, gy))
                        if target and target != cell_fid:
                            by_cell[target].append(rec)
                            rehomed += 1
                            continue
                kept.append(rec)
            by_cell[cell_fid] = kept
    if rehomed:
        print(f"  Re-homed {rehomed} misplaced exterior refs to their position's cell")

    land_by_cell = defaultdict(list)
    for rec in lands:
        cell_fid = get_formid(rec, 'ParentCELL')
        land_by_cell[cell_fid].append(rec)

    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        cell_fid = get_formid(rec, 'ParentCELL')
        pgrd_by_cell[cell_fid].append(rec)

    print(f"  Building WRLD hierarchy ({len(worlds)} worldspaces)...")
    converted = 0
    # List-append + join instead of bytes += — Tamriel's children total
    # ~600 MB, and quadratic reallocation on buffers that size dominates the
    # whole phase (see _build_cell_groups).
    all_wrld_parts = []

    for wrld_rec in sorted(worlds, key=lambda w: get_formid(w, 'FormID')):
        wrld_fid = get_formid(wrld_rec, 'FormID')
        try:
            wrld_bytes = convert_WRLD(wrld_rec)
            wrld_children = []

            wrld_cells = ext_cells_by_wrld.get(wrld_fid, [])

            # Separate the persistent worldspace cell from regular exterior cells.
            # The persistent cell has RecordFlags & 0x400 (Persistent bit) set and is
            # placed directly under the WRLD type=1 group without block/sub-block wrapping.
            # It often has XCLC=(0,0) so the old empty-string check was wrong.
            # Some worldspaces have multiple persistent cells (IC districts, Oblivion planes).
            persistent_cells = []
            exterior_cells = []
            for cell in wrld_cells:
                if get_int(cell, 'RecordFlags') & 0x400:
                    persistent_cells.append(cell)
                else:
                    exterior_cells.append(cell)

            # Persistent worldspace cells (group type 6 per cell)
            def is_persistent(r):
                return get_int(r, 'RecordFlags') & 0x400
            for persistent_cell in persistent_cells:
                pcell_fid = get_formid(persistent_cell, 'FormID')
                pcell_bytes = convert_CELL(persistent_cell)
                wrld_children.append(pcell_bytes)

                # Persistent cell children
                pcell_children = []
                persistent = []

                for refr in refr_by_cell.get(pcell_fid, []):
                    if is_persistent(refr):
                        persistent.append(convert_REFR(refr))
                        converted += 1
                for achr in achr_by_cell.get(pcell_fid, []):
                    if is_persistent(achr):
                        persistent.append(convert_ACHR(achr))
                        converted += 1
                if persistent:
                    pcell_children.append(pack_group(8, struct.pack('<I', pcell_fid), b''.join(persistent)))

                temporary = []
                for refr in refr_by_cell.get(pcell_fid, []):
                    if not is_persistent(refr):
                        temporary.append(convert_REFR(refr))
                        converted += 1
                for achr in achr_by_cell.get(pcell_fid, []):
                    if not is_persistent(achr):
                        temporary.append(convert_ACHR(achr))
                        converted += 1
                if temporary:
                    pcell_children.append(pack_group(9, struct.pack('<I', pcell_fid), b''.join(temporary)))

                if pcell_children:
                    wrld_children.append(pack_group(6, struct.pack('<I', pcell_fid), b''.join(pcell_children)))

            # Exterior cells — grouped by block/sub-block
            if exterior_cells:
                ext_blocks = defaultdict(lambda: defaultdict(list))
                for cell in exterior_cells:
                    grid_x = get_int(cell, 'XCLC.X')
                    grid_y = get_int(cell, 'XCLC.Y')
                    # Block = floor(grid / 32), Sub-block = floor(grid / 8)
                    # Use Python // which is floor division (correct for negatives)
                    block_x = grid_x // 32
                    block_y = grid_y // 32
                    sub_x = grid_x // 8
                    sub_y = grid_y // 8
                    block_label = struct.pack('<hh', block_y, block_x)
                    sub_label = struct.pack('<hh', sub_y, sub_x)
                    ext_blocks[block_label][sub_label].append(cell)

                for block_label in sorted(ext_blocks.keys()):
                    block_parts = []
                    for sub_label in sorted(ext_blocks[block_label].keys()):
                        sub_parts = []
                        for cell_rec in sorted(ext_blocks[block_label][sub_label],
                                               key=lambda c: (get_int(c, 'XCLC.Y'), get_int(c, 'XCLC.X'))):
                            cell_fid = get_formid(cell_rec, 'FormID')
                            cell_bytes = convert_CELL(cell_rec)
                            sub_parts.append(cell_bytes)

                            cell_children = []
                            persistent = []
                            for refr in refr_by_cell.get(cell_fid, []):
                                if get_int(refr, 'RecordFlags') & 0x400:
                                    persistent.append(convert_REFR(refr))
                                    converted += 1
                            for achr in achr_by_cell.get(cell_fid, []):
                                if get_int(achr, 'RecordFlags') & 0x400:
                                    persistent.append(convert_ACHR(achr))
                                    converted += 1
                            if persistent:
                                cell_children.append(pack_group(8, struct.pack('<I', cell_fid), b''.join(persistent)))

                            temporary = []
                            for refr in refr_by_cell.get(cell_fid, []):
                                if not (get_int(refr, 'RecordFlags') & 0x400):
                                    temporary.append(convert_REFR(refr))
                                    converted += 1
                            for achr in achr_by_cell.get(cell_fid, []):
                                if not (get_int(achr, 'RecordFlags') & 0x400):
                                    temporary.append(convert_ACHR(achr))
                                    converted += 1
                            cell_lands = land_by_cell.get(cell_fid, [])
                            for land in cell_lands:
                                temporary.append(_land_bytes(land_cache, land))
                                converted += 1
                            # PGRD → NAVM for exterior cells (LAND gives Z, CELL gives water)
                            # Precomputed in parallel by _precompute_navmeshes.
                            for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
                                navm_bytes, meta = navm_cache.get(
                                    (cell_fid, get_formid(pgrd_rec, 'FormID')),
                                    (None, None))
                                if navm_bytes:
                                    temporary.append(navm_bytes)
                                    navm_metas.append(meta)
                                    converted += 1
                            if temporary:
                                cell_children.append(pack_group(9, struct.pack('<I', cell_fid), b''.join(temporary)))

                            if cell_children:
                                sub_parts.append(pack_group(6, struct.pack('<I', cell_fid), b''.join(cell_children)))

                            converted += 1
                        if sub_parts:
                            block_parts.append(pack_group(5, sub_label, b''.join(sub_parts)))
                    if block_parts:
                        wrld_children.append(pack_group(4, block_label, b''.join(block_parts)))

            # Wrap in world children group (type 1)
            all_wrld_parts.append(wrld_bytes)
            if wrld_children:
                all_wrld_parts.append(pack_group(1, struct.pack('<I', wrld_fid), b''.join(wrld_children)))

            converted += 1

        except Exception as e:
            print(f"  ERROR building WRLD group for {get_str(wrld_rec, 'EditorID', '?')}: {e}")

    if all_wrld_parts:
        writer.add_raw_group('WRLD', b''.join(all_wrld_parts))

    print(f"    Worldspaces: {len(worlds)}, children: {converted}")


def main():
    parser = argparse.ArgumentParser(
        description="TES5 Import — Convert TES4 exports to Skyrim SE plugin"
    )
    parser.add_argument("export_dir", help="Directory containing per-type export .txt files")
    parser.add_argument("-o", "--output", required=True, help="Output .esm/.esp path")
    parser.add_argument("-m", "--masters", nargs="+", default=["Skyrim.esm"],
                        help="Master files (default: Skyrim.esm)")
    parser.add_argument("--esp", action="store_true", help="Create ESP instead of ESM")
    parser.add_argument("--skip", nargs="+", default=[],
                        help="Additional record types to skip")

    args = parser.parse_args()

    if not os.path.isdir(args.export_dir):
        print(f"Error: Export directory not found: {args.export_dir}", file=sys.stderr)
        sys.exit(1)

    import_plugin(
        export_dir=args.export_dir,
        output_path=args.output,
        masters=args.masters,
        is_esm=not args.esp,
        skip_types=set(args.skip),
    )


if __name__ == "__main__":
    main()
