"""
TES5 Import Orchestrator — Reads TES4 exports and writes TES5 ESM/ESP files.

Handles:
- Reading per-type export files from a directory
- Converting each record using tes5_import converters
- Building proper group hierarchies (CELL/WRLD/DIAL)
- FormID remapping (load order adjustment)
- Writing the final binary file

Usage:
    python -m tes5_import export/Oblivion.esm -o output/Oblivion.esm
"""

import argparse
import os
import struct
import sys
import time
from collections import defaultdict
from concurrent.futures import ProcessPoolExecutor, ThreadPoolExecutor, as_completed

from .constants import IMPORT_DISPATCH, SKIP_TYPES, TYPE_MAP
from .magic_effects import set_tes4_effect_names
from .dialog_converter import (
    build_dialog_groups,
    build_npc_to_vtyp_map,
    convert_QUST,
)
from .record_types.dialog_misc import convert_SOUN
from .skyrim_overrides import (
    CUSTOM_VTYP_EDIDS,
    TES4_RACE_FID_TO_EDID,
    VOICE_TYPE_MAP,
    set_voice_type,
)
from .navi_builder import build_navi_record
from .locations import build_marker_locations
from .record_types.world import (
    convert_ACHR,
    convert_CELL,
    convert_LAND,
    convert_LTEX,
    convert_REFR,
    convert_WRLD,
    set_cell_locations,
)
from .text_reader import (
    get_float,
    get_formid,
    get_formid_index_offset,
    get_int,
    get_str,
    group_records_by_type,
    parse_export_directory,
    set_formid_index_offset,
)
from .writer import (
    PluginWriter,
    pack_group,
    pack_record,
    pack_string_subrecord,
    pack_subrecord,
    pack_uint32_subrecord,
)

# Well-known property names that are generated by the script converter for
# TES4-specific systems with no Skyrim equivalent. These records must be
# created in the output ESM so VMAD properties can reference them.
_WELL_KNOWN_PROPERTIES: dict[str, int] = {}   # populated by _create_tes4_special_records


def _create_tes4_special_records(writer: PluginWriter):
    """Create globals and factions needed by converted Papyrus scripts.

    TES4Fame / TES4Infamy: Replace Oblivion's GetPCFame/GetPCInfamy system.
    TES4CyrodiilCrimeFaction: Replace Oblivion's single crime faction system.

    FormIDs are stored in _WELL_KNOWN_PROPERTIES so VMAD builders can inject
    them as property values, eliminating the "fill in CK" step.
    """
    # TES4Fame — GlobalVariable (Float, initial 0.0)
    fame_fid = writer.alloc_formid()
    fame_subs = pack_string_subrecord('EDID', 'TES4Fame')
    fame_subs += pack_subrecord('FNAM', struct.pack('<B', ord('f')))
    fame_subs += pack_subrecord('FLTV', struct.pack('<f', 0.0))
    writer.add_record('GLOB', pack_record('GLOB', fame_fid, 0, fame_subs))
    _WELL_KNOWN_PROPERTIES['TES4Fame'] = fame_fid

    # TES4Infamy — GlobalVariable (Float, initial 0.0)
    infamy_fid = writer.alloc_formid()
    infamy_subs = pack_string_subrecord('EDID', 'TES4Infamy')
    infamy_subs += pack_subrecord('FNAM', struct.pack('<B', ord('f')))
    infamy_subs += pack_subrecord('FLTV', struct.pack('<f', 0.0))
    writer.add_record('GLOB', pack_record('GLOB', infamy_fid, 0, infamy_subs))
    _WELL_KNOWN_PROPERTIES['TES4Infamy'] = infamy_fid

    # TES4CyrodiilCrimeFaction — Faction with crime flags
    crime_fid = writer.alloc_formid()
    crime_subs = pack_string_subrecord('EDID', 'TES4CyrodiilCrimeFaction')
    crime_subs += pack_string_subrecord('FULL', 'Cyrodiil Crime Faction')
    # DATA: CanBeOwner(0x8000) + all crime flags
    crime_flags = 0x8000 | 0x0080 | 0x0100 | 0x0200 | 0x0400 | 0x0800 | 0x2000 | 0x10000
    crime_subs += pack_subrecord('DATA', struct.pack('<I', crime_flags))
    # CRVA — Crime Values (defaults)
    crime_subs += pack_subrecord('CRVA', struct.pack('<HHHHIfI', 0, 0, 0, 0, 0, 1.0, 0))
    writer.add_record('FACT', pack_record('FACT', crime_fid, 0, crime_subs))
    _WELL_KNOWN_PROPERTIES['TES4CyrodiilCrimeFaction'] = crime_fid

    print(f"  Created TES4 special records: "
          f"TES4Fame={fame_fid:08X}, TES4Infamy={infamy_fid:08X}, "
          f"TES4CyrodiilCrimeFaction={crime_fid:08X}")


def _create_vtyp_records(writer: PluginWriter):
    """Create custom VTYP records for all Oblivion races in the output plugin.

    All voice types are created from scratch — we never reference Skyrim.esm
    VTYPs.  Voice files go in Sound/Voice/<plugin>/<EditorID>/ and must match
    the EditorIDs created here (TES4Male*, TES4Female*).

    Updates VOICE_TYPE_MAP at runtime so NPC_ converters pick the right FormID.

    DNAM flags: bit 0 = AllowDefaultDialogue, bit 1 = Female
      Male   voices: DNAM = 1
      Female voices: DNAM = 3
    """
    for vtyp_edid, (race_edid, gender) in CUSTOM_VTYP_EDIDS.items():
        fid = writer.alloc_formid()
        dnam = 3 if gender == 'Female' else 1
        subs = pack_string_subrecord('EDID', vtyp_edid)
        subs += pack_subrecord('DNAM', struct.pack('<B', dnam))
        writer.add_record('VTYP', pack_record('VTYP', fid, 0, subs))
        set_voice_type(race_edid, gender, fid)


def import_plugin(export_dir: str, output_path: str, masters: list = None,
                  is_esm: bool = True, skip_types: set = None):
    """
    Main import entry point. Reads exports and writes a TES5 plugin.

    Args:
        export_dir: Directory containing per-type .txt export files
        output_path: Path for the output .esm/.esp file
        masters: List of master file names (e.g., ['Skyrim.esm'])
        is_esm: Whether to create an ESM (True) or ESP (False)
        skip_types: Additional types to skip
    """
    if masters is None:
        masters = ['Skyrim.esm']
    if skip_types is None:
        skip_types = set()
    all_skip = SKIP_TYPES | skip_types

    # Per-plugin output dirs are named after the plugin (output/Oblivion.esm/ is
    # a FOLDER); given the folder, write <folder>/<folder-name> inside it rather
    # than failing to overwrite a directory with a file at the end of the run.
    if os.path.isdir(output_path):
        output_path = os.path.join(
            output_path, os.path.basename(os.path.normpath(output_path)))
    plugin_out_dir = os.path.dirname(output_path)

    print(f"Reading exports from: {export_dir}")
    t0 = time.time()

    # Parse all records
    all_records = parse_export_directory(export_dir)
    by_type = group_records_by_type(all_records)

    t1 = time.time()
    print(f"  Parsed {len(all_records)} records in {len(by_type)} types ({t1-t0:.2f}s)")

    for sig in sorted(by_type.keys()):
        special_types = {'LTEX', 'SOUN', 'CELL', 'WRLD', 'REFR', 'ACHR', 'ACRE', 'LAND', 'DIAL', 'INFO'}
        status = "SKIP" if sig in all_skip else ("CONVERT" if sig in IMPORT_DISPATCH or sig in special_types else "UNKNOWN")
        print(f"  {sig}: {len(by_type[sig])} records [{status}]")

    # Create writer
    writer = PluginWriter(masters=masters, is_esm=is_esm,
                          description="Converted from TES4 by tes4_export")

    # Set FormID remapping: adding N new masters shifts all load order indices
    # For Oblivion.esm with masters=['Skyrim.esm'], offset=1:
    #   0x00XXXXXX (was index 0 in TES4) → 0x01XXXXXX (now index 1 in TES5)
    num_new_masters = len(masters)
    set_formid_index_offset(num_new_masters)

    # Determine next FormID from the maximum in the export (before remapping applies)
    # Must scan ALL FormIDs including those in cross-references to avoid collisions
    max_formid = 0
    for rec in all_records:
        fid_raw = int(rec.get('FormID', '0'), 16)
        low = fid_raw & 0x00FFFFFF
        if low > max_formid:
            max_formid = low
    file_index = num_new_masters  # Our file's index in the TES5 master list
    # Start well above the highest FormID to avoid collision with companion records
    writer.next_object_id = (file_index << 24) | (max_formid + 0x1000)

    # Register TES4 effect display names so synthesized aimed MGEF clones can
    # be named what Oblivion called them (see tes5_import/magic_effects.py).
    set_tes4_effect_names(by_type.get('MGEF', []))

    # --- Phase 0: Create custom VTYP records for voice types not in Skyrim.esm ---
    _create_vtyp_records(writer)

    # --- Phase 0a: Create TES4-specific globals/factions for converted scripts ---
    _create_tes4_special_records(writer)

    # --- Phase 0b: Pre-scan for dialogue conversion ---
    # Build NPC FormID → VTYP FormID mapping for voice type injection, and
    # register it so convert_NPC_/convert_CREA stamp the SAME VNAM-resolved
    # voice on VTCK (an actor whose VTCK disagrees with the dialogue pass's
    # GetIsVoiceType gates never plays its lines).
    npc_to_vtyp = build_npc_to_vtyp_map(by_type, num_new_masters)
    from .record_types.actors import set_npc_voice_map
    set_npc_voice_map(npc_to_vtyp)

    # AddTopic unlock plan: gated topics get GetGlobalValue conditions and one
    # GLOB each; revealer INFO/stage fragments set the globals (must exist
    # before the QUST pass so quest VMADs can bind them as properties).
    from .dialog_unlocks import build_unlock_plan, create_unlock_globals
    unlock_plan = build_unlock_plan(by_type)
    unlock_globals = create_unlock_globals(writer, unlock_plan)
    print(f"  AddTopic unlocks: {len(unlock_globals)} gated topics, "
          f"{len(unlock_plan['info_reveals'])} revealer INFOs, "
          f"{len(unlock_plan['stage_reveals'])} revealer quest stages")

    # --- Phase 0b2: Build FormID → EditorID map for VMAD property resolution ---
    # Scripts reference external records via SCRO FormIDs. To populate VMAD
    # property values (so CK isn't needed), we need EditorIDs to generate
    # property names that match the compiled .psc files.
    fid_to_edid = {}
    for rec in all_records:
        fid_str = rec.get('FormID', '')
        edid_str = rec.get('EditorID', '')
        if fid_str and edid_str:
            try:
                fid_to_edid[int(fid_str, 16)] = edid_str
            except ValueError:
                pass
    print(f"  Built FormID->EditorID map: {len(fid_to_edid)} entries")

    # Build CrossRefGraph for INFO script property type detection.
    # INFO result scripts reference factions/quests/etc. as bare EditorID tokens.
    # ScriptConverter needs xref.edid_to_formid + xref.record_type to classify
    # these tokens (Quest/Faction/Actor/etc.) and register them as property refs.
    # Without this, properties like FightersGuild stay unbound (None at runtime).
    from script_convert.cross_ref import CrossRefGraph
    xref = CrossRefGraph()
    for rec in all_records:
        fid_str = rec.get('FormID', '')
        edid_str = rec.get('EditorID', '')
        sig = rec.get('Signature', '')
        if not fid_str:
            continue
        if edid_str:
            edid_low = edid_str.lower()
            xref.edid_to_formid[edid_low] = fid_str
            xref.formid_to_edid[fid_str] = edid_str
            if sig == 'QUST':
                xref.quest_edids.add(edid_low)
        xref.record_type[fid_str] = sig
        # SCPT type/EditorID (needed for get_extends_class + object-script binding)
        if sig == 'SCPT':
            if edid_str:
                xref.script_formid_to_edid[fid_str] = edid_str
            schr_type = rec.get('SCHR.Type')
            if schr_type is not None:
                try:
                    xref.script_formid_to_type[fid_str] = int(schr_type)
                except ValueError:
                    pass
        # Attached-script + placed-ref base chains (get_extends_class, ref typing)
        scri = rec.get('SCRI', '')
        if scri:
            xref.record_scri[fid_str] = scri
        if sig in ('NPC_', 'CREA'):
            xref.npc_formids.add(fid_str)
        if sig in ('ACHR', 'ACRE', 'REFR'):
            name_fid = rec.get('NAME', '')
            if name_fid:
                xref.record_base[fid_str] = name_fid
    # Populate per-script variable tables + ref-as-int analysis so the object
    # script converter can type its properties (same pass the CLI runs).
    scpt_path = os.path.join(export_dir, 'SCPT.txt')
    if os.path.exists(scpt_path):
        xref.build_ref_as_int_map(scpt_path)
    print(f"  Built CrossRefGraph: {len(xref.edid_to_formid)} entries, "
          f"{len(xref.quest_edids)} quests, {len(xref.script_formid_to_edid)} scripts")

    # --- Phase 0b3: Bind converted object scripts (SCPT via SCRI) to records ---
    # Each scriptable object record gets a VMAD naming its compiled TES4_<script>
    # Papyrus script + FormID bindings for the script's external references.
    # Without this the OnActivate/OnLoad/GameMode handlers never run in-game
    # (altars showed no message/effect, nirnroots never stopped their sound).
    from .object_scripts import build_object_script_plan, build_quest_script_plan
    n_obj_scripts = build_object_script_plan(by_type, xref, fid_to_edid)
    print(f"  Object scripts: attached {n_obj_scripts} SCPT scripts to records via VMAD")
    n_qust_scripts = build_quest_script_plan(by_type, xref, fid_to_edid)
    print(f"  Quest scripts: planned {n_qust_scripts} SCRI attachments for QUST VMADs")

    # --- Phase 0c: Create vendor factions for merchant NPCs, plus the
    # trainer faction + per-trainer CLAS clones for the training service ---
    from .record_types.actors import create_trainer_records, create_vendor_factions
    create_vendor_factions(by_type, writer)
    create_trainer_records(by_type, writer)

    # --- Phase 0d: Load mesh bounds for accurate OBND computation ---
    # Bounds cache normally comes from convert.py's mesh-bounds phase (after
    # mesh+speedtree conversion, so it includes speedtree NIFs too). If it's
    # missing — e.g. running the import step standalone — scan it here from
    # the already-converted output meshes so callers never have to run a
    # separate step for this.
    # Cache lives in the export directory: export/<plugin>/mesh_bounds_cache.json
    from .mesh_bounds import load_mesh_bounds, scan_mesh_bounds
    cache_path = os.path.join(export_dir, 'mesh_bounds_cache.json')
    mesh_dir = os.path.join(plugin_out_dir, 'meshes')
    if not os.path.exists(cache_path) and os.path.isdir(mesh_dir):
        print(f"  Mesh bounds cache not found, scanning {mesh_dir}...")
        scan_mesh_bounds(mesh_dir, cache_path)
    load_mesh_bounds(cache_path)
    # Havok collision soups (walkable/blocking triangles) the navmesh is built
    # from, extracted from the CONVERTED meshes. Same fallback as above.
    from asset_convert.collision_extract import load_collision, scan_collision
    col_path = os.path.join(export_dir, 'collision_cache.bin')
    if not os.path.exists(col_path) and os.path.isdir(mesh_dir):
        print(f"  Collision cache not found, scanning {mesh_dir}...")
        scan_collision(mesh_dir, col_path)
    load_collision(col_path)

    # --- Phase 0e: Compute furniture seat lists from source NIF markers ---
    # FURN MNAM/FNPR must index the converted NIF's clustered seat positions,
    # and REFRs of re-origined furniture models need z compensation
    # (shared algorithm in asset_convert/furniture_markers.py).
    from .record_types.items import load_furniture_models
    load_furniture_models(os.path.join(export_dir, 'meshes'), by_type)

    # --- Phase 0f: Generated creature RACE/ARMA/ARMO chains ---
    # One race per unique (creature folder, body-part set) among CREA records
    # whose folder was converted by the creature pipeline (creatures step).
    # convert_CREA then points RNAM at the generated race; NPC_ humanoids
    # keep the Skyrim playable-race override system.
    from .creature_races import build_creature_races
    build_creature_races(by_type, writer, export_dir)

    # --- Phase 0g: plan AI packages -------------------------------------
    # TES4 PACK records convert to TES5 template instances (pack_converter).
    # Quest-owned packages must hang off a QUST reference alias (ALPC) to
    # outrank the actor's standing schedule, so the alias indices have to be
    # decided BEFORE either QUST or PACK is written — both read this one plan.
    from .pack_aliases import (PackagePlan, build_script_var_map,
                               build_scriptvar_owner_map)
    from .packages import load_package_types
    load_package_types(by_type)

    _script_vars = build_script_var_map(by_type)
    _sv_owner = build_scriptvar_owner_map(by_type, fid_to_edid)
    pack_plan = PackagePlan()
    pack_plan.build(by_type,
                    {get_formid(r, 'FormID') for r in by_type.get('QUST', [])},
                    _sv_owner)
    print(f"  Package plan: {pack_plan.summary()}")

    # Quest packages live on a QUST alias (ALPC), not in the actor's PKID list.
    from .packages import set_quest_packages
    set_quest_packages(pack_plan.owner_quest.keys())

    from .pack_converter import PackContext
    pack_ctx = PackContext(plan=pack_plan, script_vars=_script_vars)

    # --- Phase 0h: placed leveled creatures (REFR→LVLC) ---
    # Skyrim only spawns actors from ACHR→NPC_, so each placed LVLC becomes an
    # ACHR aimed at a generated shell NPC_ whose TPLT points at the LVLN.
    # Must run after 0f (needs the generated creature races) and before the
    # CELL/WRLD builders, which read by_type['REFR'] / by_type['ACHR'].
    from .leveled_actors import build_leveled_actor_shells
    n_lvl_achr = build_leveled_actor_shells(by_type, writer)
    print(f"  Leveled creature placements: {n_lvl_achr} REFR -> ACHR "
          f"via generated shell NPCs")

    # --- Phase 0i: index inventory item types for the outfit split ---
    # A TES4 actor equips out of one mixed CNTO inventory; TES5 needs the
    # wearables moved to a DOFT outfit and everything else left in CNTO
    # (see outfits.py). Classifying an item needs its record type and biped
    # slot, so index them before the actor converters run in Phase 1.
    from .outfits import load_item_index
    load_item_index(by_type)

    # --- Phase 1: Simple record types (flat top-level groups) ---
    print("\nConverting records...")
    t2 = time.time()

    simple_types = set()
    for sig in sorted(by_type.keys()):
        if sig in all_skip:
            continue
        if sig in ('CELL', 'WRLD', 'DIAL', 'INFO', 'REFR', 'ACHR', 'ACRE', 'LAND',
                    'LTEX', 'SOUN', 'PGRD', 'QUST'):
            continue  # Handled separately
        if sig not in IMPORT_DISPATCH:
            continue
        simple_types.add(sig)

    # Types that need the writer passed in (for companion record generation)
    _WRITER_TYPES = {'ARMO', 'CLOT', 'WEAP', 'AMMO', 'NPC_', 'CREA', 'BOOK',
                     'ENCH', 'SPEL', 'SGST'}

    converted = 0
    errors = 0

    # Build work items: list of (sig, target_sig, rec) tuples
    work_items = []
    for sig in sorted(simple_types):
        target_sig = TYPE_MAP.get(sig, sig)
        for rec in by_type[sig]:
            work_items.append((sig, target_sig, rec))

    _worker_count = max(1, (os.cpu_count() or 4) - 1)

    def _convert_one(item):
        sig, target_sig, rec = item
        converter = IMPORT_DISPATCH[sig]
        if sig in _WRITER_TYPES:
            record_bytes = converter(rec, writer=writer)
        else:
            record_bytes = converter(rec)
        return sig, target_sig, record_bytes, None, None

    with ThreadPoolExecutor(max_workers=_worker_count) as ex:
        future_map = {ex.submit(_convert_one, item): item for item in work_items}
        for future in as_completed(future_map):
            sig, target_sig, rec = future_map[future]
            try:
                _, target_sig, record_bytes, _, _ = future.result()
                writer.add_record(target_sig, record_bytes)
                converted += 1
            except Exception as e:
                edid = get_str(rec, 'EditorID', '?')
                print(f"  ERROR converting {sig} '{edid}': {e}")
                errors += 1

    # --- Phase 2: LTEX (creates TXST companion records) ---
    ltex_records = by_type.get('LTEX', [])
    if ltex_records:
        print(f"  Converting {len(ltex_records)} LTEX records (with TXST creation)...")
        for rec in ltex_records:
            try:
                ltex_bytes, txst_bytes, txst_fid = convert_LTEX(rec, writer)
                writer.add_record('LTEX', ltex_bytes)
                if txst_bytes:
                    writer.add_record('TXST', txst_bytes)
                converted += 1
            except Exception as e:
                print(f"  ERROR converting LTEX '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3: SOUN (creates SNDR companion records) ---
    soun_records = by_type.get('SOUN', [])
    if soun_records:
        print(f"  Converting {len(soun_records)} SOUN records (with SNDR creation)...")
        for rec in soun_records:
            try:
                soun_bytes, sndr_bytes, sndr_fid = convert_SOUN(rec, writer)
                writer.add_record('SOUN', soun_bytes)
                if sndr_bytes:
                    writer.add_record('SNDR', sndr_bytes)
                converted += 1
            except Exception as e:
                print(f"  ERROR converting SOUN '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3b: QUST ---
    # Track all StartGameEnabled quest FormIDs for .seq file generation
    sge_quest_fids = set()
    qust_records = by_type.get('QUST', [])
    if qust_records and 'QUST' not in all_skip:
        print(f"  Converting {len(qust_records)} QUST records...")
        for rec in qust_records:
            try:
                qust_bytes = convert_QUST(rec, fid_to_edid=fid_to_edid,
                                          well_known_props=_WELL_KNOWN_PROPERTIES,
                                          unlock_plan=unlock_plan,
                                          unlock_globals=unlock_globals,
                                          pack_plan=pack_plan)
                writer.add_record('QUST', qust_bytes)
                converted += 1
                # Track SGE quests for .seq generation
                fid = get_formid(rec, 'FormID')
                flags = get_int(rec, 'DATA.Flags')
                # Quest has SGE if TES4 flag bit 0 set (no longer force all dialogue quests)
                if flags & 0x01:
                    sge_quest_fids.add(fid)
            except Exception as e:
                print(f"  ERROR converting QUST '{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3b2: PACK AI packages ---
    # Must run AFTER QUST: convert_QUST allocates the reference-alias indices
    # that a quest package's PTDA/PLDT point at (PackagePlan holds them), so the
    # aliases have to exist before the packages that reference them are written.
    pack_records = by_type.get('PACK', [])
    if pack_records and 'PACK' not in all_skip:
        from .pack_converter import convert_PACK
        print(f"  Converting {len(pack_records)} PACK records...")
        for rec in pack_records:
            try:
                writer.add_record('PACK', convert_PACK(rec, pack_ctx))
                converted += 1
            except Exception as e:
                print(f"  ERROR converting PACK "
                      f"'{get_str(rec, 'EditorID', '?')}': {e}")
                errors += 1

    # --- Phase 3c: LCTN Locations ---
    # Skyrim only reveals a map marker when the player discovers the Location it
    # belongs to, and it reads an exterior cell's displayed name off that same
    # Location — Oblivion has neither, so build them here, before the cells are
    # written, since every cell needs an XLCN pointing at one.
    set_cell_locations(*build_marker_locations(by_type, writer))

    # --- Phase 4: CELL/WRLD hierarchy (+ PGRD→NAVM navmeshes) ---
    # Base-object model index for navmesh static-footprint carving. Only
    # blocking base types contribute; keyed by raw low-24 FormID so lookups
    # work regardless of load-order remapping.
    base_model_by_fid = _build_base_model_index(by_type)
    # Raw low-24 DOOR base FormIDs, so the navmesh can choke + link at doorways.
    door_fids = _build_door_fid_set(by_type)
    # NAVM metadata accumulated across interior + exterior cells, used to build
    # the single top-level NAVI (Navmesh Info Map) the engine needs.
    navm_metas: list = []

    # Navmesh generation (scipy Delaunay + footprint carving) is the heaviest
    # CPU work in the import and is independent per cell, so run it up front
    # across a thread pool.  FormIDs are pre-allocated in deterministic cell
    # order first, so the output stays byte-identical to the single-threaded
    # path regardless of completion order.  The group builders below then just
    # look up the precomputed (navm_bytes, meta) instead of calling convert_PGRD.
    navm_cache = _precompute_navmeshes(
        by_type, writer, base_model_by_fid, door_fids,
        collision_cache=os.path.join(export_dir, 'collision_cache.bin'))

    _build_cell_groups(by_type, writer, navm_metas, base_model_by_fid, door_fids,
                       navm_cache)
    _build_world_groups(by_type, writer, navm_metas, base_model_by_fid, door_fids,
                        navm_cache)

    # Build the NAVI record indexing every generated navmesh.
    if navm_metas:
        navi_fid = writer.alloc_formid()
        navi_bytes = build_navi_record(navi_fid, navm_metas)
        if navi_bytes:
            writer.add_raw_group('NAVI', navi_bytes)
        print(f"  Built NAVI: {len(navm_metas)} navmeshes registered")

    # --- Phase 5: DIAL/INFO hierarchy ---
    voice_map = {}
    dialog_sge_fids = build_dialog_groups(by_type, writer, npc_to_vtyp, fid_to_edid=fid_to_edid, xref=xref, well_known_props=_WELL_KNOWN_PROPERTIES, voice_map=voice_map, unlock_plan=unlock_plan, unlock_globals=unlock_globals, script_vars=_script_vars)
    sge_quest_fids |= dialog_sge_fids
    _write_voice_map(output_path, voice_map)
    from .dialog_converter import get_lip_texts
    _write_lip_text(output_path, get_lip_texts())

    t3 = time.time()
    print(f"\nConverted {converted} records ({errors} errors) in {t3-t2:.2f}s")

    # Write output
    os.makedirs(os.path.dirname(output_path) or '.', exist_ok=True)
    writer.write(output_path)
    file_size = os.path.getsize(output_path)
    print(f"Wrote {output_path} ({file_size:,} bytes)")

    # Generate .seq file for StartGameEnabled quests
    _write_seq_file(output_path, sge_quest_fids)

    # Reset FormID remapping
    set_formid_index_offset(0)

    return converted, errors


def _write_voice_map(output_path: str, voice_map: dict):
    """Write the INFO FormID -> voice filename prefix map next to the ESM.

    The audio pipeline (organize_voice_files) uses it to name extracted voice
    files the way the Skyrim engine resolves them at runtime: the prefix is
    built from the CONVERTED records' owning-quest + topic EditorIDs, so the
    Oblivion filename prefix cannot be trusted.
    """
    if not voice_map:
        return
    map_path = output_path + '.voicemap.txt'
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write('# InfoFormID(low24,hex)=prefix[\\tVTYP1,VTYP2] '
                '(questEDID_topicEDID; optional tab-separated target voice-type '
                'folders for NPC-specific lines whose speaker VTYP differs from '
                'the Oblivion source race folder)\n')
        for fid in sorted(voice_map):
            f.write(f'{fid:06X}={voice_map[fid]}\n')
    print(f"  Wrote {map_path} ({len(voice_map)} voice filename prefixes)")


def _write_lip_text(output_path: str, lip_texts: dict):
    """Write the {(info_fid24, resp_num): spoken text} map next to the ESM.

    The audio pipeline pairs each voice WAV with its transcript and runs the
    Creation Kit's LipGenerator to produce the .lip sync track, packing both
    into a .fuz (SSE only reads lip data from .fuz containers).

    Format: one line per response — `<fid24 hex6>_<resp_num>=<text>` with
    backslash escapes for \\ \n \r \t (same scheme as the text export).
    """
    if not lip_texts:
        return
    map_path = output_path + '.liptext.txt'
    with open(map_path, 'w', encoding='utf-8') as f:
        f.write('# InfoFormID(low24,hex)_ResponseNumber=spoken text '
                '(for .lip generation; escapes: \\\\ \\n \\r \\t)\n')
        for (fid, num) in sorted(lip_texts):
            text = (lip_texts[(fid, num)]
                    .replace('\\', '\\\\').replace('\n', '\\n')
                    .replace('\r', '\\r').replace('\t', '\\t'))
            f.write(f'{fid:06X}_{num}={text}\n')
    print(f"  Wrote {map_path} ({len(lip_texts)} response transcripts)")


def _write_seq_file(output_path: str, sge_quest_fids: set):
    """Write a .seq file listing all StartGameEnabled quest FormIDs.

    The Skyrim engine reads this file on game start to initialize SGE quests.
    Without it, quests with the StartGameEnabled flag don't actually start,
    which means dialogue quests never run and no dialog appears.

    Format: raw binary array of uint32 FormIDs (little-endian), no header.
    Path:   <Data>/seq/<PluginName>.seq  (next to the ESM in Data folder)
    """
    if not sge_quest_fids:
        print("  No StartGameEnabled quests — skipping .seq generation")
        return

    output_dir = os.path.dirname(output_path)
    plugin_name = os.path.basename(output_path)
    seq_dir = os.path.join(output_dir, 'seq')
    os.makedirs(seq_dir, exist_ok=True)

    seq_path = os.path.join(seq_dir, os.path.splitext(plugin_name)[0] + '.seq')
    sorted_fids = sorted(sge_quest_fids)
    with open(seq_path, 'wb') as f:
        for fid in sorted_fids:
            f.write(struct.pack('<I', fid))

    print(f"  Wrote {seq_path} ({len(sorted_fids)} SGE quests, "
          f"{len(sorted_fids) * 4} bytes)")


# Base record types whose placed footprint should carve holes in a navmesh.
# Doors/lights/markers/actors are intentionally excluded.
_NAVM_BLOCKING_BASE_TYPES = frozenset({'STAT', 'CONT', 'FURN', 'ACTI', 'TREE'})


def _navm_model_key(model: str) -> str:
    """Normalise a TES4 model path to the mesh_bounds cache key.

    Mirrors mesh_bounds' key format: lowercase, forward slashes, 'tes4/' prefix,
    '.nif' suffix.  e.g. 'Furniture\\ChairNoble01.NIF' -> 'tes4/furniture/chairnoble01.nif'.
    """
    p = model.lower().replace('\\', '/').lstrip('/')
    if p.startswith('textures/'):
        p = p[len('textures/'):]
    if not p.startswith('tes4/'):
        p = 'tes4/' + p
    if not p.endswith('.nif'):
        p += '.nif'
    return p


def _build_base_model_index(by_type: dict) -> dict:
    """Map raw low-24 base-object FormID -> normalised model key.

    Only blocking base types are indexed, so navmesh carving never removes
    triangles under doors, lights, or markers.
    """
    index = {}
    for sig in _NAVM_BLOCKING_BASE_TYPES:
        for rec in by_type.get(sig, []):
            model = get_str(rec, 'Model.MODL') or get_str(rec, 'MODL')
            if not model:
                continue
            fid_str = rec.get('FormID')
            if not fid_str:
                continue
            try:
                low = int(fid_str, 16) & 0x00FFFFFF
            except ValueError:
                continue
            index[low] = _navm_model_key(model)
    return index


def _build_door_fid_set(by_type: dict) -> set:
    """Raw low-24 FormIDs of all DOOR base records (for navmesh door handling)."""
    out = set()
    for rec in by_type.get('DOOR', []):
        fid_str = rec.get('FormID')
        if not fid_str:
            continue
        try:
            out.add(int(fid_str, 16) & 0x00FFFFFF)
        except ValueError:
            continue
    return out


def _gather_navm_jobs(by_type: dict):
    """Enumerate PGRD→NAVM jobs in the exact order the group builders visit them.

    Order is: interior cells (block/sub-block, same key order as
    _build_cell_groups) first, then exterior cells per worldspace (persistent
    cells have no PGRDs, then block/sub-block exterior cells, same key order as
    _build_world_groups).  Keeping this identical to the builders means the
    FormIDs handed out below match the single-threaded allocation exactly.

    Yields job dicts with everything convert_PGRD needs plus a cache key
    (cell_fid, pgrd_fid) the builders use to look the result back up.
    """
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])

    refr_by_cell = defaultdict(list)
    for rec in refrs:
        refr_by_cell[get_formid(rec, 'ParentCELL')].append(rec)
    land_by_cell = defaultdict(list)
    for rec in lands:
        land_by_cell[get_formid(rec, 'ParentCELL')].append(rec)
    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        pgrd_by_cell[get_formid(rec, 'ParentCELL')].append(rec)

    jobs = []

    def _emit(cell_rec, land_rec):
        cell_fid = get_formid(cell_rec, 'FormID')
        cell_refrs = refr_by_cell.get(cell_fid, [])
        for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
            jobs.append({
                'key': (cell_fid, get_formid(pgrd_rec, 'FormID')),
                'pgrd_rec': pgrd_rec,
                'land_rec': land_rec,
                'cell_rec': cell_rec,
                'refr_recs': cell_refrs,
            })

    # --- Interior cells (mirror _build_cell_groups ordering) ---
    interior_cells = [c for c in cells if not get_formid(c, 'ParentWRLD')]
    blocks = defaultdict(lambda: defaultdict(list))
    for cell in interior_cells:
        fid = get_formid(cell, 'FormID')
        blocks[fid % 10][(fid // 10) % 10].append(cell)
    for block_num in sorted(blocks.keys()):
        for sub_block_num in sorted(blocks[block_num].keys()):
            for cell_rec in blocks[block_num][sub_block_num]:
                _emit(cell_rec, None)  # interiors have no LAND

    # --- Exterior cells (mirror _build_world_groups ordering) ---
    worlds = by_type.get('WRLD', [])
    ext_cells_by_wrld = defaultdict(list)
    for cell in cells:
        wrld_fid = get_formid(cell, 'ParentWRLD')
        if wrld_fid:
            ext_cells_by_wrld[wrld_fid].append(cell)

    for wrld_rec in sorted(worlds, key=lambda w: get_formid(w, 'FormID')):
        wrld_fid = get_formid(wrld_rec, 'FormID')
        exterior_cells = [c for c in ext_cells_by_wrld.get(wrld_fid, [])
                          if not (get_int(c, 'RecordFlags') & 0x400)]
        # Persistent cells have no PGRDs generated (builder skips them), so skip.
        ext_blocks = defaultdict(lambda: defaultdict(list))
        for cell in exterior_cells:
            grid_x = get_int(cell, 'XCLC.X')
            grid_y = get_int(cell, 'XCLC.Y')
            block_label = struct.pack('<hh', grid_y // 32, grid_x // 32)
            sub_label = struct.pack('<hh', grid_y // 8, grid_x // 8)
            ext_blocks[block_label][sub_label].append(cell)
        for block_label in sorted(ext_blocks.keys()):
            for sub_label in sorted(ext_blocks[block_label].keys()):
                for cell_rec in sorted(
                        ext_blocks[block_label][sub_label],
                        key=lambda c: (get_int(c, 'XCLC.Y'), get_int(c, 'XCLC.X'))):
                    cell_fid = get_formid(cell_rec, 'FormID')
                    cell_lands = land_by_cell.get(cell_fid, [])
                    _emit(cell_rec, cell_lands[0] if cell_lands else None)

    return jobs


def _navmesh_geom_cache(collision_cache: str):
    """(cache_dir, tag) for the on-disk navmesh geometry cache, or None.

    The tag hashes the navmesh generator SOURCES plus the collision cache's
    identity, so editing any navmesh code (params included) or rebuilding the
    collision cache invalidates every entry automatically — no version
    constant to forget to bump, no stale-geometry debugging sessions.
    """
    if not collision_cache or not os.path.exists(collision_cache):
        return None
    import glob
    import hashlib
    h = hashlib.sha1()
    pkg = os.path.dirname(os.path.abspath(__file__))
    srcs = sorted(glob.glob(os.path.join(pkg, 'navmesh', '*.py')))
    srcs.append(os.path.join(pkg, 'pgrd_to_navm.py'))
    for src in srcs:
        try:
            with open(src, 'rb') as fh:
                h.update(fh.read())
        except OSError:
            return None
    st = os.stat(collision_cache)
    h.update(repr((st.st_size, int(st.st_mtime))).encode())
    cache_dir = os.path.join(os.path.dirname(collision_cache),
                             'navmesh_geom_cache')
    os.makedirs(cache_dir, exist_ok=True)
    return cache_dir, h.hexdigest()


def _navm_worker_count(job_count: int) -> int:
    """Pick a worker count bounded by CPU count and job count."""
    cpu = max(1, (os.cpu_count() or 4) - 1)
    return min(cpu, max(1, job_count))


def _precompute_navmeshes(by_type: dict, writer: PluginWriter,
                          base_model_by_fid: dict, door_fids: set,
                          collision_cache: str = '') -> dict:
    """Run every PGRD→NAVM conversion in parallel; return {key: (bytes, meta)}.

    FormIDs are pre-allocated serially in builder-visit order so results are
    byte-identical to the single-threaded path regardless of completion order.

    A *process* pool (not threads) is used because convert_PGRD is dominated by
    pure-Python work (edge graph building, coverage masking, adjacency) that
    holds the GIL — only the scipy Delaunay call releases it, so threads
    serialise on the GIL and pin one core.  Processes give true N-core scaling.

    The worker lives in the light-weight `navm_worker` module (NOT this one) so
    each spawned child avoids re-importing the whole import pipeline; it takes
    no writer (FormIDs are pre-assigned) so nothing unpicklable crosses the
    process boundary.  `max_tasks_per_child` recycles workers periodically so
    scipy allocator fragmentation can't grow unbounded across 8k+ cells.
    """
    from . import navm_worker

    jobs = _gather_navm_jobs(by_type)
    if not jobs:
        return {}

    # The load-order master-index offset is a text_reader module global set once
    # in this (parent) process; spawned workers start at 0, so capture it and
    # replay it in each child's init or their get_formid() calls mis-map every
    # PathingCell parent FormID (→ navmesh-load null-deref crash).
    formid_offset = get_formid_index_offset()

    # Deterministic FormID assignment (matches serial alloc_formid order).
    for job in jobs:
        job['navm_fid'] = writer.alloc_formid()

    worker_count = _navm_worker_count(len(jobs))
    geom_cache = _navmesh_geom_cache(collision_cache)
    print(f"  Generating {len(jobs)} navmeshes (PGRD->NAVM) "
          f"across {worker_count} processes...")
    t0 = time.time()
    cache: dict = {}

    # A single tiny job isn't worth a process pool's spin-up cost.
    if len(jobs) == 1 or worker_count == 1:
        navm_worker.init_worker(base_model_by_fid, door_fids, collision_cache,
                                formid_offset, geom_cache)
        for job in jobs:
            key, result = navm_worker.run_job(job)
            cache[key] = result
    else:
        # chunksize amortises IPC over many small jobs.
        chunksize = max(1, len(jobs) // (worker_count * 8))
        with ProcessPoolExecutor(
                max_workers=worker_count,
                initializer=navm_worker.init_worker,
                initargs=(base_model_by_fid, door_fids, collision_cache,
                          formid_offset, geom_cache),
                max_tasks_per_child=500) as ex:
            for key, result in ex.map(navm_worker.run_job, jobs,
                                      chunksize=chunksize):
                cache[key] = result

    hits = sum(1 for (_b, m) in cache.values()
               if m and m.get('geom_cached'))
    print(f"    Navmesh generation: {len(jobs)} cells in "
          f"{time.time() - t0:.2f}s ({worker_count} workers, "
          f"{hits} geometry-cache hits)")
    return cache


def _build_cell_groups(by_type: dict, writer: PluginWriter,
                       navm_metas: list = None, base_model_by_fid: dict = None,
                       door_fids: set = None, navm_cache: dict = None):
    """Build CELL group hierarchy (interior cells only — exterior in WRLD)."""
    if navm_metas is None:
        navm_metas = []
    if base_model_by_fid is None:
        base_model_by_fid = {}
    if navm_cache is None:
        navm_cache = {}
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    achrs = by_type.get('ACHR', []) + by_type.get('ACRE', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])

    # Group children by parent CELL
    refr_by_cell = defaultdict(list)
    for rec in refrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        refr_by_cell[cell_fid].append(rec)

    achr_by_cell = defaultdict(list)
    for rec in achrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        achr_by_cell[cell_fid].append(rec)

    land_by_cell = defaultdict(list)
    for rec in lands:
        cell_fid = get_formid(rec, 'ParentCELL')
        land_by_cell[cell_fid].append(rec)

    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        cell_fid = get_formid(rec, 'ParentCELL')
        pgrd_by_cell[cell_fid].append(rec)

    # Interior cells = those NOT in a worldspace
    interior_cells = [c for c in cells if not get_formid(c, 'ParentWRLD')]

    if not interior_cells:
        return

    print(f"  Building CELL hierarchy ({len(interior_cells)} interior cells)...")

    # Group interior cells into blocks/sub-blocks
    # Block = formID last 2 bytes >> 12, Sub-block = formID >> 8 & 0xF (simplified)
    blocks = defaultdict(lambda: defaultdict(list))
    for cell in interior_cells:
        fid = get_formid(cell, 'FormID')
        block_num = fid % 10  # Simplified block assignment
        sub_block_num = (fid // 10) % 10
        blocks[block_num][sub_block_num].append(cell)

    all_cell_content = b''
    converted = 0

    for block_num in sorted(blocks.keys()):
        block_content = b''
        for sub_block_num in sorted(blocks[block_num].keys()):
            sub_block_content = b''
            for cell_rec in blocks[block_num][sub_block_num]:
                cell_fid = get_formid(cell_rec, 'FormID')
                try:
                    cell_bytes = convert_CELL(cell_rec)
                    sub_block_content += cell_bytes

                    # Cell children
                    children_content = b''

                    # Persistent children (group type 8)
                    persistent = b''

                    def is_persistent(r):
                        return get_int(r, 'RecordFlags') & 0x400  # Persistent flag
                    for refr_rec in refr_by_cell.get(cell_fid, []):
                        if is_persistent(refr_rec):
                            persistent += convert_REFR(refr_rec)
                            converted += 1
                    for achr_rec in achr_by_cell.get(cell_fid, []):
                        if is_persistent(achr_rec):
                            persistent += convert_ACHR(achr_rec)
                            converted += 1
                    if persistent:
                        children_content += pack_group(8, struct.pack('<I', cell_fid), persistent)

                    # Temporary children (group type 9)
                    temporary = b''
                    for refr_rec in refr_by_cell.get(cell_fid, []):
                        if not is_persistent(refr_rec):
                            temporary += convert_REFR(refr_rec)
                            converted += 1
                    for achr_rec in achr_by_cell.get(cell_fid, []):
                        if not is_persistent(achr_rec):
                            temporary += convert_ACHR(achr_rec)
                            converted += 1
                    for land_rec in land_by_cell.get(cell_fid, []):
                        temporary += convert_LAND(land_rec)
                        converted += 1
                    # PGRD → NAVM (interior cells have no LAND; Z from node heights)
                    # Precomputed in parallel by _precompute_navmeshes.
                    for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
                        navm_bytes, meta = navm_cache.get(
                            (cell_fid, get_formid(pgrd_rec, 'FormID')),
                            (None, None))
                        if navm_bytes:
                            temporary += navm_bytes
                            navm_metas.append(meta)
                            converted += 1
                    if temporary:
                        children_content += pack_group(9, struct.pack('<I', cell_fid), temporary)

                    if children_content:
                        sub_block_content += pack_group(6, struct.pack('<I', cell_fid), children_content)

                    converted += 1
                except Exception as e:
                    print(f"  ERROR building CELL group for {get_str(cell_rec, 'EditorID', '?')}: {e}")

            if sub_block_content:
                block_content += pack_group(3, struct.pack('<i', sub_block_num), sub_block_content)
        if block_content:
            all_cell_content += pack_group(2, struct.pack('<i', block_num), block_content)

    if all_cell_content:
        writer.add_raw_group('CELL', all_cell_content)

    print(f"    Interior cells: {len(interior_cells)}, children: {converted}")


def _build_world_groups(by_type: dict, writer: PluginWriter,
                        navm_metas: list = None, base_model_by_fid: dict = None,
                        door_fids: set = None, navm_cache: dict = None):
    """Build WRLD group hierarchy (worldspaces + exterior cells)."""
    if navm_metas is None:
        navm_metas = []
    if base_model_by_fid is None:
        base_model_by_fid = {}
    if door_fids is None:
        door_fids = set()
    if navm_cache is None:
        navm_cache = {}
    worlds = by_type.get('WRLD', [])
    cells = by_type.get('CELL', [])
    refrs = by_type.get('REFR', [])
    achrs = by_type.get('ACHR', []) + by_type.get('ACRE', [])
    lands = by_type.get('LAND', [])
    pgrds = by_type.get('PGRD', [])

    if not worlds:
        return

    # Index exterior cells by worldspace
    ext_cells_by_wrld = defaultdict(list)
    for cell in cells:
        wrld_fid = get_formid(cell, 'ParentWRLD')
        if wrld_fid:
            ext_cells_by_wrld[wrld_fid].append(cell)

    # Index children by parent cell
    refr_by_cell = defaultdict(list)
    for rec in refrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        refr_by_cell[cell_fid].append(rec)

    achr_by_cell = defaultdict(list)
    for rec in achrs:
        cell_fid = get_formid(rec, 'ParentCELL')
        achr_by_cell[cell_fid].append(rec)

    land_by_cell = defaultdict(list)
    for rec in lands:
        cell_fid = get_formid(rec, 'ParentCELL')
        land_by_cell[cell_fid].append(rec)

    pgrd_by_cell = defaultdict(list)
    for rec in pgrds:
        cell_fid = get_formid(rec, 'ParentCELL')
        pgrd_by_cell[cell_fid].append(rec)

    print(f"  Building WRLD hierarchy ({len(worlds)} worldspaces)...")
    converted = 0
    all_wrld_content = b''

    for wrld_rec in sorted(worlds, key=lambda w: get_formid(w, 'FormID')):
        wrld_fid = get_formid(wrld_rec, 'FormID')
        try:
            wrld_bytes = convert_WRLD(wrld_rec)
            wrld_children = b''

            wrld_cells = ext_cells_by_wrld.get(wrld_fid, [])

            # Separate the persistent worldspace cell from regular exterior cells.
            # The persistent cell has RecordFlags & 0x400 (Persistent bit) set and is
            # placed directly under the WRLD type=1 group without block/sub-block wrapping.
            # It often has XCLC=(0,0) so the old empty-string check was wrong.
            # Some worldspaces have multiple persistent cells (IC districts, Oblivion planes).
            persistent_cells = []
            exterior_cells = []
            for cell in wrld_cells:
                if get_int(cell, 'RecordFlags') & 0x400:
                    persistent_cells.append(cell)
                else:
                    exterior_cells.append(cell)

            # Persistent worldspace cells (group type 6 per cell)
            def is_persistent(r):
                return get_int(r, 'RecordFlags') & 0x400
            for persistent_cell in persistent_cells:
                pcell_fid = get_formid(persistent_cell, 'FormID')
                pcell_bytes = convert_CELL(persistent_cell)
                wrld_children += pcell_bytes

                # Persistent cell children
                pcell_children = b''
                persistent = b''

                for refr in refr_by_cell.get(pcell_fid, []):
                    if is_persistent(refr):
                        persistent += convert_REFR(refr)
                        converted += 1
                for achr in achr_by_cell.get(pcell_fid, []):
                    if is_persistent(achr):
                        persistent += convert_ACHR(achr)
                        converted += 1
                if persistent:
                    pcell_children += pack_group(8, struct.pack('<I', pcell_fid), persistent)

                temporary = b''
                for refr in refr_by_cell.get(pcell_fid, []):
                    if not is_persistent(refr):
                        temporary += convert_REFR(refr)
                        converted += 1
                for achr in achr_by_cell.get(pcell_fid, []):
                    if not is_persistent(achr):
                        temporary += convert_ACHR(achr)
                        converted += 1
                if temporary:
                    pcell_children += pack_group(9, struct.pack('<I', pcell_fid), temporary)

                if pcell_children:
                    wrld_children += pack_group(6, struct.pack('<I', pcell_fid), pcell_children)

            # Exterior cells — grouped by block/sub-block
            if exterior_cells:
                ext_blocks = defaultdict(lambda: defaultdict(list))
                for cell in exterior_cells:
                    grid_x = get_int(cell, 'XCLC.X')
                    grid_y = get_int(cell, 'XCLC.Y')
                    # Block = floor(grid / 32), Sub-block = floor(grid / 8)
                    # Use Python // which is floor division (correct for negatives)
                    block_x = grid_x // 32
                    block_y = grid_y // 32
                    sub_x = grid_x // 8
                    sub_y = grid_y // 8
                    block_label = struct.pack('<hh', block_y, block_x)
                    sub_label = struct.pack('<hh', sub_y, sub_x)
                    ext_blocks[block_label][sub_label].append(cell)

                for block_label in sorted(ext_blocks.keys()):
                    block_content = b''
                    for sub_label in sorted(ext_blocks[block_label].keys()):
                        sub_content = b''
                        for cell_rec in sorted(ext_blocks[block_label][sub_label],
                                               key=lambda c: (get_int(c, 'XCLC.Y'), get_int(c, 'XCLC.X'))):
                            cell_fid = get_formid(cell_rec, 'FormID')
                            cell_bytes = convert_CELL(cell_rec)
                            sub_content += cell_bytes

                            cell_children = b''
                            persistent = b''
                            for refr in refr_by_cell.get(cell_fid, []):
                                if get_int(refr, 'RecordFlags') & 0x400:
                                    persistent += convert_REFR(refr)
                                    converted += 1
                            for achr in achr_by_cell.get(cell_fid, []):
                                if get_int(achr, 'RecordFlags') & 0x400:
                                    persistent += convert_ACHR(achr)
                                    converted += 1
                            if persistent:
                                cell_children += pack_group(8, struct.pack('<I', cell_fid), persistent)

                            temporary = b''
                            for refr in refr_by_cell.get(cell_fid, []):
                                if not (get_int(refr, 'RecordFlags') & 0x400):
                                    temporary += convert_REFR(refr)
                                    converted += 1
                            for achr in achr_by_cell.get(cell_fid, []):
                                if not (get_int(achr, 'RecordFlags') & 0x400):
                                    temporary += convert_ACHR(achr)
                                    converted += 1
                            cell_lands = land_by_cell.get(cell_fid, [])
                            for land in cell_lands:
                                temporary += convert_LAND(land)
                                converted += 1
                            # PGRD → NAVM for exterior cells (LAND gives Z, CELL gives water)
                            # Precomputed in parallel by _precompute_navmeshes.
                            for pgrd_rec in pgrd_by_cell.get(cell_fid, []):
                                navm_bytes, meta = navm_cache.get(
                                    (cell_fid, get_formid(pgrd_rec, 'FormID')),
                                    (None, None))
                                if navm_bytes:
                                    temporary += navm_bytes
                                    navm_metas.append(meta)
                                    converted += 1
                            if temporary:
                                cell_children += pack_group(9, struct.pack('<I', cell_fid), temporary)

                            if cell_children:
                                sub_content += pack_group(6, struct.pack('<I', cell_fid), cell_children)

                            converted += 1
                        if sub_content:
                            block_content += pack_group(5, sub_label, sub_content)
                    if block_content:
                        wrld_children += pack_group(4, block_label, block_content)

            # Wrap in world children group (type 1)
            wrld_group_content = wrld_bytes
            if wrld_children:
                wrld_group_content += pack_group(1, struct.pack('<I', wrld_fid), wrld_children)

            all_wrld_content += wrld_group_content
            converted += 1

        except Exception as e:
            print(f"  ERROR building WRLD group for {get_str(wrld_rec, 'EditorID', '?')}: {e}")

    if all_wrld_content:
        writer.add_raw_group('WRLD', all_wrld_content)

    print(f"    Worldspaces: {len(worlds)}, children: {converted}")


def main():
    parser = argparse.ArgumentParser(
        description="TES5 Import — Convert TES4 exports to Skyrim SE plugin"
    )
    parser.add_argument("export_dir", help="Directory containing per-type export .txt files")
    parser.add_argument("-o", "--output", required=True, help="Output .esm/.esp path")
    parser.add_argument("-m", "--masters", nargs="+", default=["Skyrim.esm"],
                        help="Master files (default: Skyrim.esm)")
    parser.add_argument("--esp", action="store_true", help="Create ESP instead of ESM")
    parser.add_argument("--skip", nargs="+", default=[],
                        help="Additional record types to skip")

    args = parser.parse_args()

    if not os.path.isdir(args.export_dir):
        print(f"Error: Export directory not found: {args.export_dir}", file=sys.stderr)
        sys.exit(1)

    import_plugin(
        export_dir=args.export_dir,
        output_path=args.output,
        masters=args.masters,
        is_esm=not args.esp,
        skip_types=set(args.skip),
    )


if __name__ == "__main__":
    main()
